### ISSUE TITLE
mmstats page is reporting wrong numbers

### ISSUE THREAD

**Issue by rossengeorgiev** [odota/core#1047]
Hello, I've spotted an error on the MM Stats page.  
If you look at the page now it is showing 0 for Singapore(SEA) and Brazil (South America). That wrong, it should be China and South Korea. The region with most players searching should be SEA, followed by EU West.

Currently the mmstats message would return an array like this:

`[490,1966,8725,7607,0,1901,0,8955,7085,181,221,1014,548,234,68,179,110,807,1009,581,1139]`

Notice the 0's are at index `4` and `6`. See `matchgroups.txt` below for the mappings:

https://github.com/SteamDatabase/GameTracking/blob/master/dota/game/dota/pak01_dir/scripts/matchgroups.txt

Also, the page should use the names from `matchgroups.txt`, since those are the ones displayed in the client, rather than the region names.

**Comment by howardchung** [comment]
Thanks.  Unfortunately I have very little context on this.  @albertcui is out until August.  We can wait for him to come back, or we can accept a PR that fixes this issue.

**Comment by howardchung** [comment]
Moving to backlog since @albertcui probably won't have time to fix this in the near future.  We may retire the mmstats feature.

**Comment by delfwag** [comment]
maybe just retire per country stats? the general mmr stats are still somewhat useful i feel.

**Comment by howardchung** [comment]
This is a separate issue, it's the mmstats page that shows currently queuing players in each region.

**Comment by delfwag** [comment]
it still gives an idea of the general trends of region specific population depending on time, maybe just have a message indicating its only for general trend information and not fully working for now?

**Comment by howardchung** [comment]
I haven't ported this feature to the new UI yet.  If @albertcui chooses to do so he should also fix this issue, otherwise I think we will retire it.

**Comment by rossengeorgiev** [comment]
@delfwag not really

Compare https://www.opendota.com/mmstats and https://dota.rgp.io

**Comment by howardchung** [comment]
We are retiring this feature.  Use https://dota.rgp.io for all your MMStats needs :)
