### ISSUE TITLE
Option to enable aggregation on insignificant matches

### ISSUE THREAD

**Issue by davejkish** [odota/core#1079]
Hi,

I play primarily ability draft games.  I've found that adding a filter for ability draft game mode works only on the "matches" page.
For example (my player id: 29492429):
[Matches](https://yasp.co/players/29492429/matches?limit=&game_mode=18) - this works fine.
[Heroes](https://yasp.co/players/29492429/heroes?limit=&game_mode=18) - this does not work.
[Records](https://yasp.co/players/29492429/records?limit=&game_mode=18) - this does not work
The other tabs (Counts, trends, wardmap, items, etc) also do not work.

Thanks for the great service!

**Comment by howardchung** [comment]
This isn't a bug but the behavior can be confusing.  Basically, we don't count certain modes toward aggregations.  If you filter to only a non-counting mode, all of the counts will be 0.

**Comment by davejkish** [comment]
Ah, I see.  Is there any possibility of including these modes by request only?  (They wouldn't show up on default aggregations).

**Comment by howardchung** [comment]
Possible, maybe a checkbox to "include insignificant matches'

**Comment by howardchung** [comment]
This parameter is now present in the API, but the UI needs to add an element to use it.
