### ISSUE TITLE
Extra analysis categories

### ISSUE THREAD

**Issue by Trike27** [odota/core#1107]
Hi,

while Yasp analyses the games I would appreciate some tipps on how to get better in DOTA/with specific heros.

Even tipps like "more farm with this hero" or "play this hero jungle not lane" etc.

Would be great! :+1:

Thanks in advance!

**Comment by howardchung** [comment]
There's room to add further analysis categories, but things like laning decisions are often game-specific.

**Comment by gu3st** [comment]
Well we could just replace offlane with "Buy Iron Talon, go jungle :P"

**Comment by howardchung** [comment]
preferably the advice would also be patch-agnostic, unless someone wants to update the strings with each new meta shift :)

With the benchmarks data, it is possible to do some more hero-specific stuff.  Right now the efficiencies are just based off the (assumed) player role/lane.

**Comment by howardchung** [comment]
It would also be cool if we featured hero tips such as those on http://howdoiplay.com/

Perhaps they could even be triggered by particular stats in the given match (although there'd be a lot of manual grunt work to set the triggers for each string).

**Comment by howardchung** [comment]
analysis code is moving to UI repo.
