### ISSUE TITLE
Damage tab categorizes Witch Doctor spell Death Ward "auto-attacks" as hero autoattacks

### ISSUE THREAD

**Issue by mkings01** [odota/core#1123]
I think YASP is categorizing WD death ward damage (which are sort of right clicks/autoattacks) as hero right clicks/autoattacks on the damage tab. I do see some small amount of damage counted for the ward, my guess is that this is from bounces from level 3 or aghs WD ult.

For example, check out this game where my WD autoattacks did 14x as much damage as my ult. It shows <1k damage for the ult, but I killed multiple heroes with it from near full HP, and didn't build any kind of right click items.

https://yasp.co/matches/2513569398/damage

![image](https://cloud.githubusercontent.com/assets/2534141/16939560/a5438728-4d37-11e6-8735-6046d568d2b3.png)

**Comment by howardchung** [comment]
Did this issue just show up?  For some reason I've never seen it?!

You're probably right, but this is computed based on the combat log data.  If the inflictor key is set incorrectly for the damage event, it'll get grouped incorrectly.  I am not sure why some of it seems to be set correctly.
