### ISSUE TITLE
Creep ability images

### ISSUE THREAD

**Issue by howardchung** [odota/core#115]
We don't have images for creep abilities used by heroes (mainly Doom's devour abilities).

We can either ignore these abilities completely, or find images for them ourselves.

"dark_troll_warlord_ensnare"
"ogre_magi_frost_armor"	
"polar_furbolg_ursa_warrior_thunder_clap"
"centaur_khan_war_stomp"
dark_troll_warlord_raise_dead
enraged_wildkin_tornado
satyr_trickster_purge
satyr_soulstealer_mana_burn	
satyr_hellcaller_shockwave
harpy_storm_chain_lightning
keeper_of_the_light_spirit_form_illuminate_end

**Comment by howardc93** [comment]
also kotl has one ability that doesnt have image.

**Comment by howardc93** [comment]
brewmaster_earth_hurl_boulderbrewmaster_storm_cyclone

**Comment by howardc93** [comment]
"dark_troll_warlord_ensnare"	
"ogre_magi_frost_armor"	
"polar_furbolg_ursa_warrior_thunder_clap"		
"centaur_khan_war_stomp"
dark_troll_warlord_raise_dead		
enraged_wildkin_tornado					
satyr_trickster_purge	
satyr_soulstealer_mana_burn		
satyr_hellcaller_shockwave		
harpy_storm_chain_lightning

**Comment by howardc93** [comment]
This is something nick can do--find out the text string for that kotl ability and hunt down pictures for each of these abilities.

**Comment by howardc93** [comment]
Finally got bored and ran a query to find the kotl ability:
keeper_of_the_light_spirit_form_illuminate_end

**Comment by howardc93** [comment]
Although, with the new server-side sort of these details, these strings wont even show up to the user.  We can still do the creep abilities if we want to, otherwise they just wont be displayed.

**Comment by howardc93** [comment]
@lemongod is clearly not doing this :P

**Comment by howardc93** [comment]
This issue still appears on aggregated skill usages within "Advanced" on player profiles

**Comment by dylanking42** [comment]
Do we still need the pictures? I can just get these tomorrow. Also the photos would only be used on the combat and performances pages?

**Comment by howardchung** [comment]
just performances on match pages and skills on player pages, I think.

**Comment by dylanking42** [comment]
Cool what size and format for the pics? I'm on my phone right now or I
would check.

On Thursday, November 5, 2015, Howard Chung <notifications@github.com>
wrote:

> just performances on match pages and skills on player pages, I think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yasp-dota/yasp/issues/115#issuecomment-154176164>.
>


-- 
Dylan Warner
401 749 9449
dylanking42@gmail.com

**Comment by howardchung** [comment]
It shouldn't really matter since we scale the images to the appropriate
size.  We're just using the images from the valve CDN.

**Comment by dylanking42** [comment]
alright hopefully this works, all 13 in an imgur album.

http://imgur.com/a/vgGAQ

Not sure how to employ the valve CDN but at least the images are here? If you need them some other way or if I messed them up just let me know

**Comment by howardchung** [comment]
Could you name each with the corresponding ability name, and submit a pull request putting the images in https://github.com/yasp-dota/yasp/tree/master/public/images

**Comment by serifith** [comment]
Do you still need help with this?

**Comment by howardchung** [comment]
Fairly low priority, but you can do it if you want to.

**Comment by serifith** [comment]
what exactly do you need tho? Im still quite confuse

**Comment by howardchung** [comment]
For the abilities listed in the OP we don't have images.  Usually we get them from Valve:
http://cdn.dota2.com/apps/dota2/images/abilities/doom_bringer_infernal_blade_md.png

However I don't believe there are images for these creep abilities.

**Comment by serifith** [comment]
Alright , i'll try gather all the creep abilities image except the passives. 

You need to guide me tho because im fairly new to this ui and github stuff

**Comment by howardchung** [comment]
@dylanking42 already seems to have found them.  However they need to put into the repo with the correct names for each.

After that we need to update `constants.js` to map those abilities to the correct images.  I can do that (or show you how to do it if you prefer to be more hands-on).

**Comment by serifith** [comment]
I need to read the github guide first tho. I'll try help when I figured some stuff out.

Javascript is abit above my paygrade. But am curious to learn more.

**Comment by howardchung** [comment]
reopen in UI
