### ISSUE TITLE
Show building destroy timings in the overview page

### ISSUE THREAD

**Issue by eblis** [odota/core#1150]
Now that I'm thinking about [timings to show in the overview page](https://github.com/yasp-dota/yasp/issues/1149) I was thinking maybe you could also show the timings for each collapsed/destroyed building in the overview page, in the map section ?
Something like a hover text thing, you only see the time the building fell at when you hover over the building icon on the map (so as not to clutter the map otherwise).

**Comment by eblis** [comment]
Hmm, maybe for buildings that haven't been completely destroyed you could show the current health on hover ?

**Comment by howardchung** [comment]
Might be possible by looking at the combat log, but this is restricted to structures killed by heroes.

For health, we'd need to look at the entities.  I think they would have to manually mapped to icons by position, though.

**Comment by howardchung** [comment]
@blukai are you interested in porting this to match overview in new UI?

**Comment by blukai** [comment]
Why not? I guess it's a good idea. 🍀

**Comment by howardchung** [comment]
I'll open a new issue in UI then
