### ISSUE TITLE
Detect if player randomed/repicked

### ISSUE THREAD

**Issue by lomash** [odota/core#1175]
Can be helpful to know and Dotabuff already does this for plus members.

**Comment by howardchung** [comment]
Yeah the replay player entities have hasrandomed and hasrepicked properties.  We can extract them and persist them to player_matches

**Comment by howardchung** [comment]
IIRC you did the dn@10, so you can probably do this yourself too.  You might want the clarity entity inspector to find the names of the properties https://github.com/spheenik/clarity-analyzer

**Comment by howardchung** [comment]
I found the names of the entities and put them in comments in the parser (which is now in a separate repo).

Remaining steps:
* extract the data
* add to parse schema
* add to cassandra/postgres schemas
* display it on match pages

**Comment by lomash** [comment]
I'll take a look at it when I get some free time.

**Comment by KenBeanNet** [comment]
@howardchung Muted will never be true.  Its not sent in the replays.  Tried it already.

**Comment by howardchung** [comment]
Thanks, I'll remove it from the title.

**Comment by howardchung** [comment]
Do you know if hasPredictedVictory is valid?
