### ISSUE TITLE
log rune pickups

### ISSUE THREAD

**Issue by youbloodywombat** [odota/core#1189]
Hi,

I've noticed that the yasp api doesn't include the time's players died and time the players grabbed runes. is this something obtainable?

I'm trying to do some analysis on dota and these timings would be pretty nice to have.

Regards

**Comment by howardchung** [comment]
* Deaths: You can back-compute this from the kills_log.
* Runes: We have the counts of each rune, but aren't currently logging each pickup.  Could be added for future matches if you want it.

If anyone's interested in working on that I can get them started.

**Comment by youbloodywombat** [comment]
I'd be happy to help

**Comment by howardchung** [comment]
The Java parser already extracts these events.  See `svc/parser.js` for the Javascript that handles the output log.  Functions acting on the event logs are in `processors`.

The parse schema already has several examples of logged events (kills, buybacks).  You can add "runes_log" as another one.

**Comment by howardchung** [comment]
Hacktoberfest is over, but this is still a relatively simple change if someone wants to take it

**Comment by leviroth** [comment]
I'm interested in tackling this.

**Comment by howardchung** [comment]
Go for it!  Feel free to ask here or Discord if you need any help.
