### ISSUE TITLE
where to start if I want to add something to API

### ISSUE THREAD

**Issue by gerlaic** [odota/core#1203]
HI!

I want to add some new API calls to API (http://beta.opendota.com/api/). Where shall I start from?

**Comment by howardchung** [comment]
First implement the endpoint in the API: https://github.com/odota/yasp/blob/master/routes/api.js

Then update the spec: https://github.com/odota/api/blob/gh-pages/openapi.json

**Comment by howardchung** [comment]
When you know what you want to add, please change the name of this issue to describe that :)

**Comment by howardchung** [comment]
Will close for now since the question is answered.  Please reopen/create a new issue when you know what endpoints you want to add.
