### ISSUE TITLE
Doom's infernal blade recording bugged

### ISSUE THREAD

**Issue by ThomasLynn** [odota/core#1205]
I just played a game, I was looking at the the [damage tab](https://www.opendota.com/matches/2635585378/damage) and there is two seperate damage inflicters for doom's rightclick. Upon looking at the [performances tab](https://www.opendota.com/matches/2635585378/performances), there was one attack called "parsererror: SyntaxError: Unexpected end of JSON input". Presumably both of this were caused by doom manually casting his Infernal Blade.

Upon looking at the [skill builds section](https://www.opendota.com/matches/2635585378/), Infernal Blade was also using Lvl death's icon.

**Comment by howardchung** [comment]
* The first is likely due to creep abilities.  Since Valve's ability data doesn't have entries for these, the API returns a bad response.

* The second is a known issue.  https://github.com/odota/core/issues/807
