### ISSUE TITLE
Track alchemist aghs (again)

### ISSUE THREAD

**Issue by eblis** [odota/core#1209]
I seem to remember seeing the Aghanim's Scepter that heroes receive from Alchemist pop up a while ago, hopefully i'm not imagining things. I searched for issues related to this and there are 2, one from me a while ago and another one, issue #815 which is still open.

It would be nice if consumed aghanim's showed up in players inventories on the main page, but they currently do not appear there. You can see how many scepters alchemist consumed but you can't tell who he gave them to.

From what I can tell scepters stopped appearing in DotaBuff (they had this feature too IIRC) and also from the new post-game UI in the Dota2 game itself.

**Comment by howardchung** [comment]
I don't think any progress has been made on this issue and as far as I know it never was implemented.  #815 is still open if anyone wants to work on it.

**Comment by eblis** [comment]
I was probably imagining things then, I remember seeing the aghs in the overview page :(
I thought it might be something that happened recently and broke it again, as it looks as though it's currently broken in the game and dotabuff.
