### ISSUE TITLE
Player search doesn't find the correct user

### ISSUE THREAD

**Issue by Proyoyo** [odota/core#1225]
Username: Proyoyo
Search String: Proyoyo
Result: 
<img width="1177" alt="screen shot 2016-09-20 at 9 53 57 am" src="https://cloud.githubusercontent.com/assets/11515661/18653619/66274bec-7f1e-11e6-8601-0a5d6cb153d3.png">

**Comment by Proyoyo** [comment]
Player profile: https://www.opendota.com/players/55268262

**Comment by howardchung** [comment]
fixed in https://github.com/odota/core/commit/e908e01eb15ad90393a1b3cc435a627fa0c45f43

Web instances won't be updated until the next deployment, though.
