### ISSUE TITLE
add mmr_estimate and competitive_rank to match players

### ISSUE THREAD

**Issue by aeosynth** [odota/core#1257]
if a player does not show his mmr, show the mmr estimate, perhaps in parenthesis

**Comment by howardchung** [comment]
Could be done.  Would likely want to refactor out the code that computes the estimate so it can be reused.

**Comment by Bubblemelon** [comment]
Hi, it seems that this issue has been open for almost a year now. Can I help in some way?

**Comment by howardchung** [comment]
Yes, if you want to add this to core we can then pass it down to the UI so it'll show up on the web page.

Let me know if you have any trouble getting the core dev environment started!  You may have to manually insert some data into the database in order to test your changes.

**Comment by moonrobin** [comment]
This can probably be closed with the addition of the new ranked system. I don't think there's any way to disable showing your medal/rank.

**Comment by howardchung** [comment]
yeah, we'll probably just replace solo_competitive_rank with rank_tier (medal) and not worry about the other fields.
