### ISSUE TITLE
Any idea about dotabuff's series feature

### ISSUE THREAD

**Issue by WuPei** [odota/core#1258]
The dotabuff released series feature, which contains BO1,BO2,BO3 and BO5.

I know we can get series_type from GetMatchHistory. 
However I found that series_type can only be 0, 1, 2, which represents BO1, BO3 and BO5.
Anyone have ideas about how they get type **BO2**?

Currently My idea is that if this match belongs to the same league same team with series_type=0, and if his next match's opponent remains unchanged then it's a **BO2**.
But this can only be detected  after the start of second game.

Anyone has better idea?

**Comment by howardchung** [comment]
I believe the GC call for requestMatchDetails contains some series information.

**Comment by WuPei** [comment]
GC call for requestMatchDetails contains same information as GetMatchHisotory API with league_id set, which lacks the type of BO2.
For BO1/BO2 series_id, series_type will all be 0.
For BO3/BO5, there will be a series_id set, and series type will be 1 for BO3 and 2 for BO5.

**Comment by howardchung** [comment]
Unfortunately, I don't know a whole lot about this, but if you investigate and want to share your findings, it would be appreciated!  

@Crazy-Duck is the node-dota2 expert and might have some idea on where the information might be found.

**Comment by Crazy-Duck** [comment]
As far as I've been able to determine, there exists no such thing as a BO2 in the Dota2 client, nor the GC. BO2's are played either as two consecutive BO1's or as a BO3 that's cut short after the second game...

**Comment by howardchung** [comment]
Closing since there is no action pending.  Feel free to update if you find out anything more!
