### ISSUE TITLE
Public Matches/Hero Win Rates with filtering

### ISSUE THREAD

**Issue by superfedja** [odota/core#1264]
Hey, 

A few weeks ago, I commented on a Reddit thread debating Dotabuff vs Opendota and I said I was only using Dotabuff cause they gave hero win rates for 5K+ games and someone sent me this link and told me that if I asked you guys to put this on Opendota you might do it. So here I am.

Basicly, what I'd like is to be able to see hero win rates in each MMR bracket and to be able to choose the time period. Kind of what Dotabuff and Dotamax do, but both of them have significant inconvenients. Dotamax doesn't show 5K+ MMR stats, they only show ''Very High'' which can be between 3.8k all the way to 9k, and Dotabuff doesn't let you choose the time period you want to analyze (unless you subscribe to their site), they only give you this month, which is useless after patches and since patches are dropped more and more often, it's not really good, unless you pay of course. So I told my self if I'm going to invest money I'd rather encourage a open source site like Opendota but, as I said, the stat I'm really looking for is hero win rates for different MMR brackets and date filters. Also, what would be cool is if we could see win rates for different line-ups or at least duos and trios. I know you guys used to do something similar but it was a global stat, not reserved to high MMR games if I remember correctly. And there were no date filters either. Anyways, it would be cool if we could choose the MMR bracket and time period for which we wanted to see how a certain hero performed when paired with other heroes, or against them for that matter.

Anyways, I hope you guys can make this happen. I'd appreciate it A LOT. Peace.

**Comment by howardchung** [comment]
This is possible, but we'll need to make some changes.

* Win rates by bracket:
Filtering generally requires us to put the data in PostgreSQL, but this is not feasible for massive amounts of data, so we'll likely have to randomly sample.

We do already keep track of match_rating (average visible MMR in any match), but do not track the heroes played, so we'll probably need to add a table for that, and insert a random subset of the matches played (maybe 10% of matches).

* Hero combinations:
I'm planning to do hero peers and opponents (basically duos), probably in november/december after new UI is done.  #1227 However the way it is currently planned will not support partitioning by MMR.

**Comment by howardchung** [comment]
Proposed API design:
/public/matches
 * min_mmr
 * max_mmr
 * min_time
 * max_time
Uses public_matches table to return matches meeting the criteria

/public/winrates
 * min_mmr
 * max_mmr
 * min_time
 * max_time
Uses public_player_matches and public_matches to return heroes grouped by winrate meeting the criteria
