### ISSUE TITLE
Missing Solo MMR?

### ISSUE THREAD

**Issue by DeathTBO** [odota/core#1286]
So I noticed that my solo MMR shows N/A. I tried refreshing the match history (hoping it would also refresh that data). I also checked my MMR section and it shows my MMR all the way up until October 16th 2015. From there is completely disappears.

**Comment by howardchung** [comment]
You need to show your MMR in your ingame profile, then play a ranked game.

**Comment by DeathTBO** [comment]
So I have to display it on my profile. Alright well thanks. I figured the Yasp bot being in my friends list and my profile being public was enough.

**Comment by howardchung** [comment]
Valve disabled the old player profiles around the time Reborn was released, so the bots are no longer needed.
