### ISSUE TITLE
match feed

### ISSUE THREAD

**Issue by howardchung** [odota/core#1303]
Feature allowing users to find latest:
- [x] Pro matches
- [ ] matches by MMR range

**Comment by blukai** [comment]
@howardchung Also would be a cool thing if user can **follow** others players

**Comment by howardchung** [comment]
First is implemented with /proMatches endpoint

Second will be merged with #1264 as some kind of public data explorer feature, where the user can either get matches, or heroes grouped by win rate for some given criteria.
