### ISSUE TITLE
Sort purchases by time, then cost

### ISSUE THREAD

**Issue by TrentBartlem** [odota/core#1310]
e.g. https://www.opendota.com/matches/2737538170/purchases

Medusa buys items to complete Dragon Lance

<img width="139" alt="screen shot 2016-10-28 at 3 38 39 pm" src="https://cloud.githubusercontent.com/assets/171650/19796029/a7cd5f22-9d24-11e6-9983-b18cc2c88039.png">

Could the purchase order be tweaked, so if 2 items appear in the inventory at the same time, the cheaper one is listed first? Since the more expensive one is probably the item that was built from the first purchase...

**Comment by howardchung** [comment]
I think so, but can you reopen this in the UI repo since this is a UI issue?

**Comment by TrentBartlem** [comment]
Done. https://github.com/odota/ui/issues/351
