### ISSUE TITLE
Strange Plotting on MMR Graph 

### ISSUE THREAD

**Issue by jackb-p** [odota/core#1323]
http://i.imgur.com/rl7XQ0W.png

I have displayed/not displayed my party MMR on my profile a bit on-and-off and it seems to have caused a strange bug with the MMR graph. 

Link: https://www.opendota.com/players/93359457/rating

**Comment by howardchung** [comment]
Not sure what causes this, maybe inverted order on a couple points?  The c3 library handles the graphing so we don't control it directly.

**Comment by howardchung** [comment]
It looks like using spline can cause this occasionally.  https://github.com/odota/core/issues/241

**Comment by howardchung** [comment]
confirmed that using line fixes this issue, at the cost of the graph looking a bit more jagged.
