### ISSUE TITLE
meta parsing

### ISSUE THREAD

**Issue by howardchung** [odota/core#1333]
Valve provides a metadata file for each match (stored together with the replay file).  It appears to have no expiration, so we could possibly consider it a durable source (like the WebAPI).  This is the source of the extended data displayed in the client's post-game screen.

Example meta file:
http://replay111.valve.net/570/3080357861_1890072989.meta.bz2

Protobuf definition:
https://github.com/SteamDatabase/GameTracking-Dota2/blob/master/Protobufs/dota_match_metadata.proto

Example parsing code:
https://github.com/odota/core/blob/master/dev/scratch.js

Data contained within looks something like:
http://pastebin.com/47dTy6ns

There are some interesting fields such as:
```
            "fight_score": 0.75,
            "farm_score": 166.88368225097656,
            "support_score": 5050,
            "push_score": 469.25439453125,
```

The data is stored as a bzipped serialized protobuf message, so requires some CPU time to extract and process.  We could, however, let Valve host the source files and just grab them on demand.

We could grab some of the fields and persist them in Cassandra. 

This is less CPU-intensive than full replay parsing, and is available for longer.  A subset of the full replay parse data is available:
* Hero kill targets
* Purchase log
* cosmetics
* nw, gold, xp graphs
* inventory snapshots (30 second intervals)

Possibly, we can do this for all matches without raising server costs too much.

**Comment by dartharaknus** [comment]
I like this.

**Comment by RGBKnights** [comment]
I would love to get involved with this as it would mean having more stats for more matches by default.
1. How did you get started what was the endpoint involve?
a. I know that replays are stored at: http://replay{cluster}.valve.net/{APPID}/{match_id}_{replay_salt}.dem.bz2
2. where did you get the protobuf definitions?
a. Where they part of the this project or did you need to include full set from https://github.com/SteamRE/SteamKit/tree/master/Resources/Protobufs?

**Comment by howardchung** [comment]
Replace "dem" with "meta" in the replay URL.  I put an example in the OP.

Yeah, that's the correct proto file.  Traditionally I've used the GameTracking-Dota2 project for the files:
https://github.com/SteamDatabase/GameTracking-Dota2/blob/master/Protobufs/dota_match_metadata.proto

It should the same file though.

You can see the quick demo/prototype I did:
https://github.com/odota/core/blob/master/dev/scratch.js

That just parses the meta file and dumps the resulting structure to console.

**Comment by RGBKnights** [comment]
Thanks very much for the information. I will take a look and see what they come up with.

**Comment by howardchung** [comment]
This is an updated dump of a recent parsed meta file:
https://pastebin.com/z49CB8yY

I'm curious to know if there's pick order in this data.
