### ISSUE TITLE
Track player last match time

### ISSUE THREAD

**Issue by ammuench** [odota/core#1341]
Currently, when I go to use the `tracked_until` value, the Unix date value is returning dates in December.  It seems to be off by one month

https://api.opendota.com/api/players/7533510/
returns:
`tracked_until`: 1481088546

which is `2016-12-07T05:29:06+00:00 ` in ISO time.

**Comment by howardchung** [comment]
This is correct for donators.  We automatically refresh their tracked_until value a month from now every few minutes.  Otherwise, it gets set 2 weeks in the future on every visit.

**Comment by ammuench** [comment]
Gotcha.  Would it be possible to expand the base object to return a `lastmatch` value or something of the like showing the player's last match?  Or should we just use the last logged game's value for that

**Comment by howardchung** [comment]
We don't currently keep track of last match, but it wouldn't be too hard to add.  We'll just keep another redis zset that keys account_id to timestamps and update it whenever a match finishes.

Yeah, I didn't do a great job of documenting all the output fields.  The spec is available in `routes/spec.js` if you want to help :)

**Comment by ammuench** [comment]
I'd love to help :)  Can update

**Comment by howardchung** [comment]
@albertcui wrote some documentation for our old JSON data dump, which has a very similar structure to the current matches API.  Maybe we can combine the two:
https://github.com/odota/core/wiki/JSON-Data-Dump

**Comment by howardchung** [comment]
I would actually just suggest making a call to /players/:account_id/matches for this data, while this call is significantly more expensive, it shouldn't be a problem unless you need this data at a very high volume.
