### ISSUE TITLE
more information for 'firsts'

### ISSUE THREAD

**Issue by aeosynth** [odota/core#1347]
eg hovering over first blood should show who got fb, and who died. showing only the timer is very abstract.

**Comment by howardchung** [comment]
This is a client side issue.  Could you reopen it there?

**Comment by aeosynth** [comment]
done. btw i'm not entirely clear on which features would depend on backend changes and need to be opened here.

**Comment by howardchung** [comment]
As far as I'm aware all of the "first" information that is currently displayed is generated from the match data sent to the client.  If there is something specific desired, we can open a new issue for that.

**Comment by aeosynth** [comment]
i meant in general, it's not obvious which information is sent to the client, unless you open a console or dig through the code. a short section in the readme to clarify this would help me decide which repo to open an issue in.
