### ISSUE TITLE
Improve teamfight analysis

### ISSUE THREAD

**Issue by dartharaknus** [odota/core#1366]
> I have issues with some of the teamfight analysis, however.

> As an example, in https://www.opendota.com/matches/2759233818 is a match where I was playing AntiMage. I'm certain that the number of teamfights I was actually involved in is significantly less than the number that your algorithm thinks I was involved in.

> To give a specific example, that match shows a teamfight at 23:48. If you check the replay, it is clear that all of the fighting happens in the near vicinity of the Dire side T2 Bot tower. I am Antimage, and farming up the Dire jungle at this point. I presume that I got picked up in the teamfight because I healed up a tiny bit using lifesteal during the period of the fight itself.

**Comment by howardchung** [comment]
We can disable teamfight participation for healing, although this might negatively affect support players.

**Comment by dartharaknus** [comment]
Yup. But I think I have an idea on how to improve this. But I need to get familiar with backend code more.

**Comment by howardchung** [comment]
This calculation is actually done in the UI side (renderMatch).  The raw data just returns the healing/damage done by each hero in each time range (teamfight), and we decide if a player participated on the client side.

**Comment by dartharaknus** [comment]
What about the teamfights that take over long time with heroes chasing others and stuff? IIRC the teamfight analysis in parser is kinda wrong on that.

**Comment by howardchung** [comment]
The current criteria just starts a teamfight 10 seconds before a hero death and ends it if 10 seconds elapse without a hero death.

**Comment by dartharaknus** [comment]
Yeah, it can be improved. We have lots of data for this.

**Comment by srinath-v** [comment]
Care to point me towards the place where this part of the code resides?

I'd like to take a look.

That said, does the current version of teamfight analyser take 

- XP/gold gained into account?
- Spells used?
- Items used?

**Comment by howardchung** [comment]
https://github.com/odota/core/blob/master/processors/processTeamfights.js

The input is an array of log events.  We identify 10 seconds before/after hero deaths, and then aggregate the logs in each interval to produce the numbers for teamfights.

**Comment by howardchung** [comment]
There isn't really a specific ask here, and there haven't been any complaints for a while.
