### ISSUE TITLE
Player stats are affected by filter

### ISSUE THREAD

**Issue by vadi2** [odota/core#1370]
Player stats are affected by filter - see player stats for https://www.opendota.com/players/363588270/matches?included_account_id=158051717 and https://www.opendota.com/players/363588270.

**Comment by howardchung** [comment]
Do you mean the aggregations such as w/l count?  If so, it's intentional to allow the user to view the w/l count for the filtered range.

**Comment by vadi2** [comment]
That makes sense, but it's not intuitive. Maybe add a tooltip to explain that the stat has been affected by the filter?

**Comment by howardchung** [comment]
Open an issue in UI for this, since this is display-only.

**Comment by vadi2** [comment]
Okay. I don't think I'm vested in this enough to bother bouncing around
bugtrackers.
