### ISSUE TITLE
Chat messages are missing in old games

### ISSUE THREAD

**Issue by SomeSnm** [odota/core#1377]
Hello,

I was going through data dump and found that some games on the website do not show messages, only times when the messages were posted.
Example: https://www.opendota.com/matches/1139074642/chat 
Here are the messages: https://www.dotabuff.com/matches/1139074642/chat

**Comment by howardchung** [comment]
Probably incompatibility with an older format for the chat messages.  If you just need the content:
http://api.opendota.com/api/matches/1139074642

Alternatively we can update the UI to show `message.key || message.text`

**Comment by howardchung** [comment]
fixed in UI.  If you're using the API do analysis, you'll need to handle both cases.
