### ISSUE TITLE
solo_competitive_rank and competitive_rank should be ints rather than strings

### ISSUE THREAD

**Issue by GlassBil** [odota/core#1378]
No reason for them to be string as far as I can see. Especially since the estimated MMR is reported as an int.

**Comment by howardchung** [comment]
Yeah, this could be done.  The reason it's string is that the data is read from Redis and it comes out as a string since JavaScript Numbers don't cover the full range of 64-bit ints.

**Comment by AvoJFB** [comment]
Hi guys!
As I see from [this](https://api.opendota.com/api/players/142120687) query, solo_competitive_rank isn't a string, its an integer. Was this issue solved?

**Comment by howardchung** [comment]
Looks like you're right, it might have gotten fixed at some point.
