### ISSUE TITLE
Add parameter "match case" and "match exact words" to search function

### ISSUE THREAD

**Issue by FaridAhamat** [odota/core#1382]
As a user, I would like to search for username using their exact case and exact words persona name.

**Comment by howardchung** [comment]
Might require a separate query in the store/search.js file to handle this.

**Comment by FaridAhamat** [comment]
Would it work if you allow more parameter to the search function? Something like: https://api.opendota.com/api/search?q=whatever&sml=1

Because I saw the sml is hardcoded to 0.4, so allowing the user to specify how accurate they want the result could be better.

Disclaimer: I've no experience on backend, so feel free to ignore this message if you think my suggestion is crap :)

**Comment by howardchung** [comment]
that might work, perhaps a sml of 1.0 would force exact matches (I don't think casing is considered)
