### ISSUE TITLE
Change `picks_bans` column in `matches` table to be json object keyed by hero_id

### ISSUE THREAD

**Issue by akallu** [odota/core#1383]
Currently the picks_bans column in the matches table is a PostgreSQL array of json elements. This is clunky and does not lend itself for easy querying. Since hero_ids are unique keys anyways, it is better to have this column simply be a json object with hero_id keys (may be worth renaming the column to picks_bans_by_hero_id to provide some clarity). Example of proposed change:

OLD:
```
[
    {
        "team": 1, 
        "hero_id": 92, 
        "order": 0, 
        "is_pick": false
    }, 
    {
        "team": 0, 
        "hero_id": 77, 
        "order": 1, 
        "is_pick": false
    },
    ...
]
```

NEW:
```
{
    "92": {
        "is_pick": false, 
        "order": 0, 
        "team": 1
    }, 
    "77": {
        "is_pick": false, 
        "order": 1, 
        "team": 0
    },
    ...
}
```

**Comment by howardchung** [comment]
If you want to query on picks_bans you might want to use the dedicated table:
https://github.com/odota/core/blob/master/sql/create_tables.sql#L251

This only contains pro matches, though.

If you are interested in pairwise win rates in pub matches you may just want to join public_player_matches with itself.

**Comment by akallu** [comment]
Gotcha, if that's the design decision you guys have made for all tables, then it should be respected. Thanks for the followup!
