### ISSUE TITLE
API call for items?

### ISSUE THREAD

**Issue by MagnumDopus** [odota/core#1387]
I'd love to be able to use the open dota api to grab item information, I currently use it for everything else but it seems there is no items api.

It would be especially helpful since the web api that the dota 2 devs offer does not have any kind of localized name for the items.  If open dota added this functionality it would rule.

**Comment by howardchung** [comment]
Do you mean cosmetic or in-game items?

**Comment by MagnumDopus** [comment]
In game items.  Rapiers, blink daggers etc

**Comment by MagnumDopus** [comment]
To expand on what I mean, when I do a get on the /heroes api open dota provides I get, hero_id, name, and localized_name which is human readable, which makes it awesome from an automation stand point for my site.  Obviously there is no item API available from open dota, and the api provided by valve, though useful and somewhat thorough (gold, isRecipe, isSecret_Shop, etc) there is no localized name).  Which again is not the end of the world but sucks from an automation perspective (I've written scripts to automate building a sprite sheet of heroes/items and building a database of their respective information.

**Comment by howardchung** [comment]
If you pass &language=english to the GetGameItems endpoint it will provide the localized name.  Does that suit your needs?

**Comment by MagnumDopus** [comment]
I could kiss you.  I wish there were better documentation for this, using a tf2 wiki for information on the web api is annoying.  This does indeed solve the issue.  I will contend that the Open Dota api is still probably more reliable than Dota 2's api's but this indeed solves the issue I will close this thread!
