### ISSUE TITLE
new rune data source

### ISSUE THREAD

**Issue by howardchung** [odota/core#1391]
looks like the chat events don't have this anymore (CHAT_MESSAGE_RUNE_PICKUP)

**Comment by leviroth** [comment]
I'm seeing some indication that the `DOTA_COMBATLOG_PICKUP_RUNE` event from `skadistats.clarity.wire.common.proto.DotaUserMessages` isn't being used. I didn't get any console output when parsing a sample match with:

    if (e.type === 'DOTA_COMBATLOG_PICKUP_RUNE') {
      console.log(JSON.stringify(e, null, 4));
    }

In contrast, this code worked just fine if the event type was changed to `DOTA_COMBATLOG_PURCHASE`.

**Comment by howardchung** [comment]
what was the match ID of the match you tried?  Also where exactly did you try to insert that code snippet?

**Comment by howardchung** [comment]
The parser emits every combat log event.  However, it might not do it if the event is missing from the replay.

https://github.com/SteamDatabase/GameTracking-Dota2/blob/ce4961e3c4445f42cb97756c7f241a5b7ca4db5d/Protobufs/dota_gcmessages_common.proto

based on this PICKUP_RUNE is number 21.  I think last time I checked there is nothing above 19 in the replay file.  We might need to find another source for this data.

**Comment by howardchung** [comment]
alternatively valve may fix this if it was an unintentional change.  This has happened before (like first blood vanishing after reborn and getting added back later)

**Comment by howardchung** [comment]
valve seems to have fixed this with an update
