### ISSUE TITLE
Failed to parse replay

### ISSUE THREAD

**Issue by inShu** [odota/core#1398]
Hi,
I'm trying to request parse of replay - https://www.opendota.com/request#2928084343
And catching "Failed to get match data" error. You asked to report here in such case.

**Comment by inShu** [comment]
But as I can see actually parsing process was done - https://www.opendota.com/matches/2928084343

**Comment by howardchung** [comment]
It's possible it just timed out on the request side.  Does it fail consistently?

**Comment by inShu** [comment]
No. I think this is because of match duration (about 94 minutes).

**Comment by howardchung** [comment]
Transient errors (unavailable replay salt, high load) can occur sometimes.  If it fails consistently, it may be a parser issue and then I'd investigate to see if there's a crash.
