### ISSUE TITLE
"Players Played With" section inaccuracy

### ISSUE THREAD

**Issue by inShu** [odota/core#1399]
https://www.opendota.com/players/77314199
For my profile it shows wrong numbers. For example if I take a look at "Teammates" section in dota profile will see that I've played about 500 (not 83) games with "Mamsel LS".

**Comment by howardchung** [comment]
If the player was anonymous during that match they will not be counted.  The in-game client does not have this restriction.  If they enable public match history and then their match history is refreshed (via link on their OpenDota profile) it should correct itself.
