### ISSUE TITLE
Policy to get URLs of replays

### ISSUE THREAD

**Issue by inShu** [odota/core#1400]
Hi,
I want to understand your policy in my case. I want to get a lot of replay's urls from your API - https://api.opendota.com/api/replays
As an API user and as developer I don't have opportunity to use this method because if game wasn't logged by opendota it wouldn't get replay URL. So for me there is only 1 scenario:
1) Call https://www.opendota.com/request to force OpenDota to parse replay
2) Call https://api.opendota.com/api/replays?match_id= to get replay details.

But this is not good way for your service, since I'm forcing you to parse unnecessary replay. But from other side your API (https://api.opendota.com/api/replays) is unusable from standalone point of view.
What would you suggest?

**Comment by howardchung** [comment]
If your volume is relatively low (several thousand replays a day), then you can request a parse for each and fetch the salt.

If it's high, you may want to set up your own service to fetch replay urls, using a steam client library such as node-dota2.  You can see `svc/retriever.js` as a reference.

**Comment by inShu** [comment]
Got it. Thank you.
