### ISSUE TITLE
Please add a list of SDKs for OpenDota APIs if available

### ISSUE THREAD

**Issue by cyberinferno** [odota/core#1406]
A section in README for SDK list would be useful for developers looking to consume APIs.

**Comment by howardchung** [comment]
If someone wants to assemble a list we can add it.

The OpenAPI/Swagger spec is available though, so it should be possible to autogenerate a library in many languages: http://swagger.io/swagger-codegen/

**Comment by howardchung** [comment]
Note: The project does not provide any official wrapper libraries, just the API spec and the API itself.  I know several users have written libraries in Ruby, R, JavaScript, etc, but these are all maintained independently by their authors (and may not necessarily be updated regularly).
