### ISSUE TITLE
npm failing to install while performing initial setup of environment

### ISSUE THREAD

**Issue by knorssman** [odota/core#1410]
looking to get started and contribute, running into some problems setting up

working in window 10 home

downloaded docker-toolbox/installed

downloaded git core-master repository to my user folder

created .env file in core-master with a steam api key from valve's website for the site opendota.com and steam username/pass for a second account

opened core-master folder in docker quickstart terminal and ran docker-compose up and i get some output until it stops as seen in the screenshot, it seems to be some issue with npm

![capture](https://cloud.githubusercontent.com/assets/6013248/23080948/66bcaf8c-f518-11e6-880b-2b909d2426be.PNG)

**Comment by howardchung** [comment]
@dartharaknus any ideas?  Might be a windows-only thing?

**Comment by dartharaknus** [comment]
fsevents won't install on docker. You need to mount the node_modules. But docker-compose should already be doing that.

**Comment by howardchung** [comment]
Fsevents is just a warning.  The issue appears to be the file not found error below it.  Are you able to repro this with a clean start on windows?

**Comment by dartharaknus** [comment]
Ah sorry, misunderstood. Is `steam-client` a recent addition to package.json? I havent been using windows for a long time.

**Comment by howardchung** [comment]
It's a sub dependency of steam-user which is actually not used in production, only in a dev script.  However eslint complains if it's left out of package.json

**Comment by howardchung** [comment]
@knorssman I removed a couple of dependencies from package.json.  Can you start with a clean clone, remove all your containers and try again?

**Comment by howardchung** [comment]
@knorssman is this still an issue?

**Comment by howardchung** [comment]
reopen if there are further install issues.
