### ISSUE TITLE
would be nice if we could get hero_id in public_matches

### ISSUE THREAD

**Issue by freecookiess** [odota/core#1412]
https://www.opendota.com/explorer
https://github.com/odota/core/blob/master/sql/create_tables.sql

**Comment by howardchung** [comment]
This is a player_match level field, but you can JOIN with matches table to get back rows with combined player_matches in them.

http://stackoverflow.com/questions/43870/how-to-concatenate-strings-of-a-string-field-in-a-postgresql-group-by-query
