### ISSUE TITLE
New hero images

### ISSUE THREAD

**Issue by MrYadro** [odota/core#1424]
Seems like Valve (as always) forgot to update default images:
![old](http://cdn.dota2.com/apps/dota2/images/heroes/slardar_full.png)
`http://cdn.dota2.com/apps/dota2/images/heroes/slardar_full.png`
![new](http://cdn.dota2.com/apps/dota2/images/heroes/slardar_full.png?)
`http://cdn.dota2.com/apps/dota2/images/heroes/slardar_full.png?`
They are the same here, but different for proxy or if you download it (seems like they check for referrer or something)

**Comment by howardchung** [comment]
Yeah, looks like the proxied version isn't updated yet.  Do we need to send some http header to get the new version?

http://api.opendota.com/apps/dota2/images/heroes/slardar_full.png

**Comment by MrYadro** [comment]
I'm not sure which one, but adding any parameter, even empty one fixes the issue even for your proxy.
`http://api.opendota.com/apps/dota2/images/heroes/slardar_full.png?`

**Comment by MrYadro** [comment]
I tried to copy all headers from http://www.dota2.com/hero/Slardar/ it looks like only ? hack is working.

**Comment by howardchung** [comment]
probably easiest fix is just to update dotaconstants to put ? in the path then:
https://github.com/odota/dotaconstants/blob/master/tasks/updateconstants.js#L125

**Comment by howardchung** [comment]
Done, this should take effect with the next UI deploy

**Comment by MrYadro** [comment]
Now you can revert "?", because valve saw that patchnotes had wrong avatar, and finally changed image.
