### ISSUE TITLE
/publicMatches returning a very small amount of matches?

### ISSUE THREAD

**Issue by MagnumDopus** [odota/core#1426]
Hey, I have been using OpenDota for a while now to power my site DotaEdge.com, and for a while it was working great but now it seems as though the api /publicMatches very rarely returns new matches where ti used to return a lot often.  Now it seems like the return set very very rarely updates.  As such it is no longer really a solution for my site.  I was wondering if this was a bug or is this intended?

Edit to be clear all I really need is a list of the most recent matches in dota 2, I imagine this list would be pretty fast updating with how many dota games are played, I store all of the information about public ranked matches in my database and then do my own calculations against my local copy.  Is there a better way to achieve this list other than publicMatches?

**Comment by howardchung** [comment]
I changed publicMatches to return the top matches sorted by MMR in the last 3 days.  Sorry, this was a breaking change and I probably should have incremented the semver major version.

If you need the latest matches I suggest the Steam endpoint GetMatchHistoryBySequenceNum.  That will return every match played, and you can sample as many as you want.

**Comment by MagnumDopus** [comment]
Damn I much preferred open dota for this as the requests are fulfilled more often than steams somewhat unreliable endpoint.  Also I believe for some reason there were better mmr informationals provided by public matches.  I will look to update my scripts shortly, thank you for the quick response.

**Comment by howardchung** [comment]
If you prefer, you can use the /explorer endpoint to make a custom query on the public_matches table.

However keep in mind that this isn't a true random sample because only matches with at least 3 players showing MMR are eligible for sampling.

**Comment by MagnumDopus** [comment]
That is probably preferable since I need to know the MMR of the match.  I know its a more limited selection of results but its still definitely what I want.  Is there a more verbose explanation of the explorer endpoint?  I don't quite grasp how to utilize it for my purpose.

**Comment by howardchung** [comment]
You can use the Explorer UI to compose your query:
https://www.opendota.com/explorer?sql=select%20*%20from%20public_matches%20limit%2010

Then click the JSON button to get the API endpoint:
https://api.opendota.com/api/explorer?sql=select%20*%20from%20public_matches%20limit%2010

**Comment by MagnumDopus** [comment]
Oh my understanding of that UI was that it was only returning pro tournaments or some level of league play, is that untrue?  Also you said that it would only show matches with 3 mmr showing but I see some where num_mmr is 2, is that zero based then?

Finally that example you provided, is that already replicating the old behavior of publicMatches?

**Comment by howardchung** [comment]
The graphical builder only supports pro match queries, but you can compose a custom SQL query and the public_matches and public_player_matches tables are also available.
,
I think I changed the criteria from 2 to 3 at some point.  It's not zero-based.

Not exactly, the old behavior was return 100 matches sorted by match_id descending.  However sorting by match_id descending is not a good random sample since shorter matches will be more likely to appear.

**Comment by MagnumDopus** [comment]
I will be cycling through the same query every so often to grab new ones as they come in, I can have blind spots since the site is best effort countering approximation with available data it doesn't have to be history complete.  

Can you expand on the differences between public_matches and public_player_matches?  Also are these automatically only valid lobby_types and gamemodes?

**Comment by howardchung** [comment]
public_player_matches is the players participating in a match.  You can use it to fetch the heroes of the players playing in a match.

Yes, only balanced game modes and lobby types are included in the sample.

**Comment by MagnumDopus** [comment]
Awesome, this is why I love opendota.  So would this effectively replicate the original function of publicMatches:

https://www.opendota.com/explorer?sql=select%20*%20from%20public_matches%20where%20num_mmr%20%3E%200%20order%20by%20start_time%20desc%20limit%20100

**Comment by howardchung** [comment]
it used to order by match_id, but functionally it should be basically the same.

If this is an endpoint you want to use consistently, you can also consider submitting a pull request to add it as an official endpoint (and so it'll show up in the docs)

**Comment by MagnumDopus** [comment]
I am a total github noob, and a noob in all things, which is why I am clearly so bad at all of this.  I have no idea what a pull request is or how to make one or submit one etc.  I will look into it though and consider it once I have used this system to effectively fix my match scraper.

**Comment by MagnumDopus** [comment]
Sorry to bother once again, but I am scratching my head now, in terms of getting the most up to date live matches, sorting by start_time could potentially miss some, as could match_seq_num, and match_id.  Is there any metric I can return the sorted list by which is the finished date of the match, so that I can just get matches listed as they're completed.

**Comment by moengke** [comment]
Hey there Kevin and Howard - I'm wondering if your query (select * from public_matches where num_mmr > 0 order by start_time desc limit 100) is up to date or not... 
I'm guessing num_mmr is deprecated? 
I also need to grab a lot of games without duplicating which I grab. And I want to use something like publicMatches because it gives both radiant and dire teams packaged as simple [1,2,3,4,5] arrays...
