### ISSUE TITLE
Missing kill event

### ISSUE THREAD

**Issue by coreymaher** [odota/core#1430]
Check out this match: https://www.opendota.com/matches/3075949719/log

If you look at the log the storm spirit gets first blood on riki, but the kill does not show up in the opendota log.
If you look at the replay the storm spirit hits riki, but then a tower gets the last hit. The game does give the kill credit to the storm though.

**Comment by howardchung** [comment]
I don't remember if the first blood event contains the data on who was killed.  I think it contains the slot index, so we could probably extract that and save it to a field.

**Comment by howardchung** [comment]
So the original issue seems to be that only kills made by a player/player-controlled unit show in the kills log, but the game will sometimes credit the kill to a player even if a tower/creep gets the last hit.

I don't have a solution for that issue, but I'm extracting an additional property from the firstblood event that should be the player index of the killed player, so we can use that instead.
