### ISSUE TITLE
429 error

### ISSUE THREAD

**Issue by inShu** [odota/core#1432]
Hi, 

Previously we had a conversation about how I want to use Open Dota API - https://github.com/odota/core/issues/1400
And you stated that it's ok to force your API to parse a several thousands of matches per day.
So I've implemented such mechanics and today started to catch 429 HTTP response (too many requests). I wonder why? Maybe I'm doing a lot of requests in short period of time? I'm pretty sure that I'm not requesting more than a hundred of matches per day at this moment.

**Comment by howardchung** [comment]
I haven't changed the rate limiting, it should still be 90 reqs per 60 seconds per IP address.  Is it possible that there are other clients requesting from your IP?

**Comment by inShu** [comment]
This rate limit is for GET and POST as well? I think then I found root cause of problem. Thank you for clarification.

**Comment by howardchung** [comment]
Yes all requests count toward the limit.
