### ISSUE TITLE
Matches not prase automaticly

### ISSUE THREAD

**Issue by RGBKnights** [odota/core#1437]
I am regularly logged in and I am a chess supporter but my matches are not being parsed automatically. I believe this because all of my matches are Ability Draft games. If you going to state something like "Cheese buyers are also indefinitely tracked. All your games from now on will be parsed, whether you visit or not." you should parse my games!

I hate having to come to the site and have to manually parse my matches ever time...

**Comment by howardchung** [comment]
During Dark Moon I disabled auto-parsing of non-standard game modes to reduce load.  I suppose now that the event is over we can turn it back on.

https://github.com/odota/core/blob/master/store/queries.js#L1038
