### ISSUE TITLE
Line Break

### ISSUE THREAD

**Issue by iamrenzx** [odota/core#1442]
![break](https://cloud.githubusercontent.com/assets/21088424/25121575/b15d6b92-2454-11e7-856f-0407ec9a6ffb.png)

**Comment by howardchung** [comment]
Thanks.  We need to fix this in this file:
https://github.com/odota/dotaconstants/blob/master/build/items.json

probably just replace the `<br />` with `\n`

**Comment by howardchung** [comment]
Fixed with @mdiller update to get the data from client files, should take effect with next UI deploy
