### ISSUE TITLE
No Hero, No Result game 48 years ago

### ISSUE THREAD

**Issue by Kartoffelshake** [odota/core#1460]
Looked at the profile of a friend and the most recent game (13.05.17 at 14:00-15:00)has this bug.

here a picture of the problem: http://i.imgur.com/tVx52bV.png
profile: https://www.opendota.com/players/99641082
Link of the match(gets stuck in loading): https://www.opendota.com/matches/3175596069
Dotabuff link to the match (works without problem): https://www.dotabuff.com/players/99641082

**Comment by howardchung** [comment]
This is fine now, and happens due to the skill service being ahead of the scanner service (which fetches match details).

I think I can add logic to the recent matches API endpoint to hide matches that don't have match details yet.

**Comment by howardchung** [comment]
I'm going to remove the matches returned from Cassandra that don't have a duration.  This might result in less than 20 matches in some cases, but should be generally fine, and avoids confusing users due to the incomplete data when the scanner is behind the skill service.
