### ISSUE TITLE
Feature request: average duration of won games for each hero

### ISSUE THREAD

**Issue by adrfantini** [odota/core#1468]
A nice addition to the "Heroes" panel would be the average duration of won games for each hero. This would help judging whether a hero is mostly an early-game powerhouse (e.g. maybe Bristleback, Ursa, Abaddon, QOP, Stalker, Cow, PA, Bloodseeker, Sky or whatever else you think is strong early-game) or late gamer (AM, PL, Dusa, Slark, Spectre, Troll, Morph...).

AFAIK none of the other major game analysers have this feature, which would be very handy.

**Comment by howardchung** [comment]
Like this?

https://www.opendota.com/explorer?select=duration&result=win&group=hero

**Comment by adrfantini** [comment]
Yeah, awesome! But for non-professional matches too, in the Heroes tab.
Unfortunately it's not necessarily true that Drow is as effective at
finishing early with pub matches as with pro matches.

2017-05-27 4:35 GMT+02:00 Howard Chung <notifications@github.com>:

**Comment by howardchung** [comment]
I put together this query using the public_matches tables (still uses the explorer UI, but different data).  This is an ~10% sample of public matches:

https://www.opendota.com/explorer?sql=select%20hero_id%2C%20count(1)%2C%20avg(duration)%20duration%0Afrom%20public_matches%20join%20public_player_matches%20using(match_id)%20%0Awhere%20match_id%20%3E%203200000000%20AND%20match_id%20%3C%203210000000%20AND%20(player_slot%20%3C%20128)%20%3D%20radiant_win%0Agroup%20by%20hero_id%0Aorder%20by%20duration%20desc&format=

**Comment by adrfantini** [comment]
That's great, I still find it'd be a very nice addition outside of the
(complex to use) data explorer tho.

2017-05-27 18:27 GMT+02:00 Howard Chung <notifications@github.com>:

**Comment by howardchung** [comment]
There is a proposal to include this in an enhanced hero data page:
https://github.com/odota/ui/issues/1143

It would only contain data from about 50k pro matches, hopefully that's sufficient.

Doing this for public matches is kind of tricky due to the data volumes involved, we have to end up sampling matches and it adds quite of a bit of disk space used.
