### ISSUE TITLE
Match analysis shouldn't count some items as unused

### ISSUE THREAD

**Issue by frozenspider** [odota/core#1469]
The following cases probably shouldn't be accounted as "unused items":
* Any item that was in inventory less than a minute, especially those purchased right before the game end
  * Example: https://www.opendota.com/matches/3208159551/analysis - I as Phoenix purchased Glimmer, disassembled it and sold immediately, but it was counted as 2 unused items
* Quelling blade
* RoB/Aquila (might be purchased for pushing purposes specifically)
* Linken's on cores? (a passive effect is usually enough)

**Comment by howardchung** [comment]
I'm not sure if we can handle the "less than a minute" case but we can exclude specific items from being counted.

Code is in:
https://github.com/odota/ui/blob/master/src/components/Match/analysis.js#L171

**Comment by TheOriginalSoni** [comment]
Apart from that, there's a side issue of "If ironwood branches/buckler is used, that does not count as mekanasm usage", which seems to be the case right now.

Suggested pseudocode to solve a number of these issues - 
`function numberofunuseditems():
    q={}
    for all items i:
        if (item i is purchased && game.endtiming - i.purchasetiming > 60)
        {
            maxcosti=i;
            for (all items i2 in itemgroup it of i)
            {
                if(i2 is purchased && i2.cost>maxcost && game.endtiming - i2.purchasetiming > 60)
                {
                    maxcosti=i2;
                }
            }
            if(i2.used == false) q.push(i2);
        }
    return q.size();`

This pseudocode always takes the highest cost item of a particular item_group (that the player has purchased), and considers that item's usage instead. Also all items that are bought less than a minute from the game end are ignored.

I think this should be good to solve most of these bugs

**Comment by howardchung** [comment]
Since code for this is in odota/ui, switching over to https://github.com/odota/ui/issues/974

Also tagged hacktoberfest to encourage someone to pick it up
