### ISSUE TITLE
verages/Maximumsin last 20 matches Calculating Siltbreaker Matches.

### ISSUE THREAD

**Issue by ItsCEED** [odota/core#1474]
As the title says,

Profile for example: https://www.opendota.com/players/160172314

**Comment by howardchung** [comment]
@blukai do you want to fix this?  Or should we just consider it a temporary issue that will fix itself when the event ends?

**Comment by blukai** [comment]
Probably the better solution is here https://github.com/odota/ui/issues/704, we should add an option to turn on/off events.

**Comment by howardchung** [comment]
For performance reasons though the recentMatches endpoint only fetches and returns 20 matches.  If we suppress matches from the returned 20 the user may see very few or no matches if they have been playing a lot of event matches.

**Comment by blukai** [comment]
Maybe in api can be added option that will allow to exclude some game modes?

**Comment by howardchung** [comment]
That option already exists for the /matches endpoint, and it's on by default.

The problem is that since recentMatches only fetches 20 matches from the database, if we use the same approach we may not get any matches at all (if the last 20 matches are all event)

**Comment by howardchung** [comment]
see https://github.com/odota/ui/issues/1040
