### ISSUE TITLE
Parser problem

### ISSUE THREAD

**Issue by BoreaWolf** [odota/core#1475]
Some matches are not correctly and fully parsed, leaving some hero data incomplete.
If you look at the Performance tab you can clearly see on which hero the parser starts having problems.

Here some matches showing this error:
https://www.opendota.com/matches/3233340300
https://www.opendota.com/matches/3233353908
https://www.opendota.com/matches/3233401600
https://www.opendota.com/matches/3233495802

I hope this could be helpful to you.

**Comment by howardchung** [comment]
Thanks!  I'm investigating these replays to see how they differ.  Seems like this doesn't affect all matches, only some, and only started about a week ago?

**Comment by howardchung** [comment]
I couldn't repro it locally so I just tried reparsing and it seems to have fixed the issue.

Not sure if Valve had broken replays for a while and then fixed the issue later.  Please reopen/comment if you find another match (in the future) that has this same issue.
