### ISSUE TITLE
XP sources CREEP/HERO swapped

### ISSUE THREAD

**Issue by rudidudi** [odota/core#1478]
by viewing a match stats,
on tab **FARM**
in the tables:

- Radiant-XP Sources
- Dire-XP Sources

the experience got by **creeps and hero is swapped**.

actually it can be a front-end or back-end problem.

**Comment by howardchung** [comment]
Investigating.  It could be just that we have our labels swapped (on the frontend).  The backend only counts the number of each type.

**Comment by howardchung** [comment]
You're correct!

Somehow the strings got mislabeled, fixing in this commit:
https://github.com/odota/ui/commit/d417ed93af7742acc8e65d8207b33a64d32788d3

Thanks for spotting this!
