### ISSUE TITLE
Story mode for live games

### ISSUE THREAD

**Issue by jume-dev** [odota/core#1479]
Hi
not sure if i am in the right project for this, but i thought about using the story mode for an automatic text based live game report (similar to a live ticker for sport games).
Could this be done with live games or is there a replay needed for it to work?
Have a nice day,
jume

**Comment by howardchung** [comment]
I think @Crazy-Duck has some experience with getting the combat log of a game currently being spectated, but I haven't done this myself.

**Comment by Crazy-Duck** [comment]
Not sure if you can retrieve the combat log of an on-going game. What you can do is look into game state integration, which allows you to obtain a lot of info on matches you're in/spectating. All you need is a config file named `gamestate_integration_*.cfg` like this:
```
"dota2-gsi Configuration"
{
    "uri"               "http://localhost:3000/"
    "timeout"           "5.0"
    "buffer"            "0.1"
    "throttle"          "0.1"
    "heartbeat"         "30.0"
    "data"
    {
        "provider"      "1"
        "map"           "1"
        "player"        "1"
        "hero"          "1"
        "abilities"     "1"
        "items"         "1"
    }
    "auth"
    {
        "token"         "hello1234"
    }
}
```
placed in `steamapps\common\dota 2 beta\game\dota\cfg\gamestate_integration\`. The token is optional iirc. If you run a web server on localhost:3000 you'll receive POST messages containing the elements you configured in the config.

**Comment by howardchung** [comment]
Closing since this is out of scope of the OpenDota project, but feel free to ask for additional help on our Discord channel.  There are probably a few people there who can help with GSI-related questions.
