### ISSUE TITLE
The problem to get requestMatchDetails(match_id, [callback]) with the requests limit

### ISSUE THREAD

**Issue by zyi1992** [odota/core#1482]
I was use the node-dota2 to get match detail for replay_url, but i got a problem when the request is out the limit , but when i use the opendota api , it seems like the opendota api can get many of match whitout limit , Is there any solution to solve the request limit for steam client api that you did in opendota api, Hope for you share.

**Comment by howardchung** [comment]
The limits are 100 requests/accounts/24 hours and 500 requests/IP/24 hours.

**Comment by zyi1992** [comment]
So the opendota api will change the steam account and proxy when touch the limit?

**Comment by howardchung** [comment]
The proxies are only used for Steam web API calls, not match details requests (from GC).

The number of accounts in use is dynamic and changes depending on current load.  Basically, create as many accounts as you think you'll need for peak load and work from there.

**Comment by zyi1992** [comment]
Ok ,Thanks for you replay
