### ISSUE TITLE
Authorize new users

### ISSUE THREAD

**Issue by SunlightBLR** [odota/core#1483]
Hi.
I'm new to working with API and I have a couple of questions.

1. Suppose I use your API in my application. In my application comes a person who is not authorized on your site. (i.e. He don`t have account_id for using OpenDota API). How to authorize it correctly?
2. There is a match that did not pass parsing. What is the correct way to get complete information about the match?

THX

**Comment by howardchung** [comment]
1.  A user does not need to have signed in in order to have data available.  We reuse Steam's account_id field.

2.  If the replay isn't available anymore (more than 10 days old) then we can't get the full data anymore.

**Comment by howardchung** [comment]
Feel free to comment if you have further questions (or find us on Discord!)
