### ISSUE TITLE
Paging support for players/{account_id}/mmr

### ISSUE THREAD

**Issue by doubliekill** [odota/core#1484]
your opendota api is very worked to me,thank you 

but i have a question :How to get account_id by user name

**Comment by howardchung** [comment]
There isn't a really good way to do it since Steam users can change their tag at any time.  You can try using the /search endpoint to attempt to find players by the last name we have on record for them.

**Comment by doubliekill** [comment]
thank you .but when i query  username = 123,there have too many results,but i want to get the results by page. is there have a good way to get?

**Comment by howardchung** [comment]
Unfortunately the server limits results to 500, so searching for common usernames may be difficult.  We do this because otherwise the search request might take too long.

**Comment by howardchung** [comment]
If the user logs in via Steam, your server can identify them and find their account_id that way.

**Comment by doubliekill** [comment]
thank you

**Comment by doubliekill** [comment]
how to get player's recent match by page? @howardchung

**Comment by doubliekill** [comment]
i want to build an app with your api, but most of them doesn't have the way to get data by page.i'm very hope you to add this method to me .thank you very match.

**Comment by howardchung** [comment]
What do you mean by recent match by page?

The /players/{account_id}/matches endpoint is a full listing of the matches the player has played.

/players/{account_id}/recentMatches returns only the last 20, but is faster.

**Comment by doubliekill** [comment]
like this，https://wiki.teamfortress.com/wiki/WebAPI/GetMatchHistory 
start_at_match_id (Optional) (string)
Start searching for matches equal to or older than this match ID
matches_requested (Optional) (string)
Amount of matches to include in results (default: 25).

**Comment by howardchung** [comment]
That should be covered by the /players/{account_id}/matches endpoint.  It returns all matches (there is no paging)

**Comment by howardchung** [comment]
If you want to page you can pass `limit` and `offset` parameters.  (This should be in the docs, let me know if it's not there)

**Comment by doubliekill** [comment]
ok

**Comment by doubliekill** [comment]
Hello my friend ，how to get hero's info by hero id?

**Comment by howardchung** [comment]
What info are you looking for?

**Comment by doubliekill** [comment]
for example，hero's icon,name,skills   and hero's other info the more the better

**Comment by howardchung** [comment]
See the dotaconstants project for this data:
https://github.com/odota/dotaconstants/tree/master/build

**Comment by doubliekill** [comment]
how can i know when the constants's data get updated?

**Comment by howardchung** [comment]
You can watch the repo for updates.  We run a script to update it after patches.

**Comment by doubliekill** [comment]
https://api.opendota.com/api/players/{account_id}/ratings
hey brother,can you add some params that can query the result by limit?

**Comment by howardchung** [comment]
example?

**Comment by doubliekill** [comment]
a params like start at match

**Comment by howardchung** [comment]
Any reason why this is needed?  You should be able to request the full data and get what you need from that.

**Comment by doubliekill** [comment]
i will store the rating data to my app's db.but i don't want to update the db every time,because when the player's has updated his match history,I only update a few new record usually

**Comment by howardchung** [comment]
You should be able to filter the data to only the new rows you want to insert.  The only concern would be the extra bandwidth usage but if you're not requesting too rapidly the few thousand extra bytes shouldn't be a major issue.

I'm not sure when I'll be able to work on this myself, but if you submit a PR I'd be happy to accept it.

**Comment by doubliekill** [comment]
https://api.opendota.com/api/players/{account_id}/heroes

can you add the hero's average kda to this url response?or how can i get the kda by another way?

**Comment by howardchung** [comment]
You can add the aggregation code to routes/spec.js for this endpoint, or request all the matches with the /matches endpoint and compute it yourself.

**Comment by howardchung** [comment]
Since MMR data no longer updates, I imagine its use will be slowly phased out.

**Comment by doubliekill** [comment]
Hello my friend，how to get the player's rank medal icon and star icon

**Comment by howardchung** [comment]
See the /players/{account_id} endpoint

**Comment by doubliekill** [comment]
I want to get the rank's medal icon ,not the rank_tier

**Comment by coreymaher** [comment]
The icons are in the web repo: https://github.com/odota/web/tree/master/public/assets/images/dota2/rank_icons

Or other places on the internet (like the dota 2 wiki: https://dota2.gamepedia.com/Matchmaking/Seasonal_Rankings)

**Comment by doubliekill** [comment]
Okay thank u very much

**Comment by KicKerBNU** [comment]
Hello, Can i limit the response of the heroes of players i get ? i want make a search who response with the first 3 most sucessfull heroes of that player but i get like 500 players with 140 heroes i want only the best ones... Like: https://api.opendota.com/api/players/105385807/rankings?**limit=3**

**Comment by howardchung** [comment]
Currently that endpoing doesn't support a limit parameter. Is the additional bandwidth an issue?

**Comment by KicKerBNU** [comment]
> Currently that endpoint doesn't support a limit parameter. Is the additional bandwidth an issue?

No, its working fine, thanks and nice job on the api.
