### ISSUE TITLE
Method to view all players (account_id) from match

### ISSUE THREAD

**Issue by neverperfect** [odota/core#1485]
Is it possible to list all players that are playing on a match, onto tables on OpenDota Explorer? Example on match_id 3279344693 if turned into a csv file:

`match_id, radi_1, radi_2, radi_3, radi_4, radi_5, dire_1, dire_2, dire_3, dire_4, dire_5`
`3279344693, 108376607, 135878232, 118134220, 142750189, 111114687, 88508515, 135384059, 139937922, 88553213, 107803494`

Also if I would like to search per players then list the players as team/opponent how would I do it?
Example (in this case I'm searching by 111114687 account_id (y` 's account))

`match_id, account_id, team_1, team_2, team_3, team_4, opp_1, opp_2, opp_3, opp_4, opp_5`
`3278894409, 111114687, 108376607, 135878232, 118134220, 142750189, 114239371, 119576842, 90882159, 148215639, 111189717`
`3279344693, 111114687, 108376607, 135878232, 118134220, 142750189, 88508515, 135384059, 139937922, 88553213, 107803494`

**Comment by howardchung** [comment]
Here's one quick way to do it if you don't need each column separately:
https://www.opendota.com/explorer?sql=select%20match_id%2C%20string_agg(account_id%3A%3Atext%2C%20%27%2C%27)%20from%20matches%20join%20player_matches%20using(match_id)%20where%20match_id%20%3D%203279344693%20group%20by%20match_id&format=

**Comment by howardchung** [comment]
If you need it split up by column here's one way to achieve that (kind of hacky):
https://www.opendota.com/explorer?sql=select%20match_id%2C%20%0Asum(case%20when%20player_slot%20%3D%200%20then%20account_id%20else%200%20end)%20rad1%2C%0Asum(case%20when%20player_slot%20%3D%201%20then%20account_id%20else%200%20end)%20rad2%2C%0Asum(case%20when%20player_slot%20%3D%202%20then%20account_id%20else%200%20end)%20rad3%2C%0Asum(case%20when%20player_slot%20%3D%203%20then%20account_id%20else%200%20end)%20rad4%2C%0Asum(case%20when%20player_slot%20%3D%204%20then%20account_id%20else%200%20end)%20rad5%2C%0Asum(case%20when%20player_slot%20%3D%20128%20then%20account_id%20else%200%20end)%20dire1%2C%0Asum(case%20when%20player_slot%20%3D%20129%20then%20account_id%20else%200%20end)%20dire2%2C%0Asum(case%20when%20player_slot%20%3D%20130%20then%20account_id%20else%200%20end)%20dire3%2C%0Asum(case%20when%20player_slot%20%3D%20131%20then%20account_id%20else%200%20end)%20dire4%2C%0Asum(case%20when%20player_slot%20%3D%20132%20then%20account_id%20else%200%20end)%20dire5%0Afrom%20matches%20%0Ajoin%20player_matches%20using(match_id)%20%0Awhere%20match_id%20%3D%203279344693%20%0Agroup%20by%20match_id&format=

**Comment by neverperfect** [comment]
If I wanted to search by an account id (to get all list of an account's match history) is it possible?

**Comment by howardchung** [comment]
You could do so with the subquery in the WHERE clause:
https://www.opendota.com/explorer?sql=select%20match_id%2C%20%0Asum(case%20when%20player_slot%20%3D%200%20then%20account_id%20else%200%20end)%20rad1%2C%0Asum(case%20when%20player_slot%20%3D%201%20then%20account_id%20else%200%20end)%20rad2%2C%0Asum(case%20when%20player_slot%20%3D%202%20then%20account_id%20else%200%20end)%20rad3%2C%0Asum(case%20when%20player_slot%20%3D%203%20then%20account_id%20else%200%20end)%20rad4%2C%0Asum(case%20when%20player_slot%20%3D%204%20then%20account_id%20else%200%20end)%20rad5%2C%0Asum(case%20when%20player_slot%20%3D%20128%20then%20account_id%20else%200%20end)%20dire1%2C%0Asum(case%20when%20player_slot%20%3D%20129%20then%20account_id%20else%200%20end)%20dire2%2C%0Asum(case%20when%20player_slot%20%3D%20130%20then%20account_id%20else%200%20end)%20dire3%2C%0Asum(case%20when%20player_slot%20%3D%20131%20then%20account_id%20else%200%20end)%20dire4%2C%0Asum(case%20when%20player_slot%20%3D%20132%20then%20account_id%20else%200%20end)%20dire5%0Afrom%20matches%20%0Ajoin%20player_matches%20using(match_id)%20%0Awhere%20match_id%20IN%20(select%20match_id%20from%20player_matches%20where%20account_id%20%3D%20111114687)%0Agroup%20by%20match_id&format=

**Comment by howardchung** [comment]
Reopen/comment if further questions (or ask on Discord)

**Comment by neverperfect** [comment]
Yes, can I add you on discord?
I'm working on a thesis at the moment and I might need some more help regarding OpenDota's SQL syntax usage..

**Comment by howardchung** [comment]
Sure
