### ISSUE TITLE
Match logs coordinate data is empty 

### ISSUE THREAD

**Issue by RickCSong** [odota/core#1491]
It seems that in the match logs table, the x, y coordinates is currently empty for "type = 'DOTA_COMBATLOG_MODIFIER_ADD'".  Would it be difficult to populate these?

This would make queries such as "Where does X team smoke" available which seems to be incredibly useful! 

Would be happy to help make a contribution if this seems doable. 

Aside: it also appears that the coordinates for player deaths is also empty

**Comment by howardchung** [comment]
Not all rows have position data.  Combat log data does not have position attached.  It's possible to retrieve the position of a player at the time a combat log event happened, but this would have to be emitted as a separate line.

**Comment by RickCSong** [comment]
I see.  What would be the best approach to determine where a Smoke occurred for a given team?

**Comment by howardchung** [comment]
This data currently isn't persisted to the match_logs table to save space and speed queries.

This is the list of event types currently persisted:
https://github.com/odota/core/blob/master/processors/processLogParse.js

If you can parse the replay yourself (using odota/parser) then there is a combat log event for item uses, and you can combine that with the entity position at the time that the item is used.

**Comment by RickCSong** [comment]
Perfect!  Thank you @howardchung :)
