### ISSUE TITLE
Format for gold_reasons

### ISSUE THREAD

**Issue by RickCSong** [odota/core#1493]
Hey!!

Thanks for the insanely quick responses.  I was wondering what the format of gold_reasons (in player_matches) is?

Example: 
`
{"0":788,"1":-1135,"5":162,"11":600,"12":1015,"13":2972}
`

What does 0, 1, 11, 12, 13 correspond with?  Are these actions?  

Also!  I was trying to find in the code how these are processed but were unable to.  Was wondering where I may be able to find that data.

**Comment by howardchung** [comment]
https://github.com/odota/ui/blob/master/src/lang/en-US.json#L222

**Comment by howardchung** [comment]
odota/core only handles the data plane.  Any display-related code (like mapping IDs to strings) is in ui or dotaconstants

**Comment by howardchung** [comment]
Please reopen/comment if any further questions (or ask on Discord!)
