### ISSUE TITLE
Data Explorer doesn't return heroes in order when limit is high

### ISSUE THREAD

**Issue by talhasaruhan** [odota/core#1494]
When limit is set to anything higher than 10^5, heroes don't return in the order they should (a dire player may be the first one in the list for ex.).
Edit: in chrome I get correct results up to 10^5 but when using python requests library I begin to get messed up results after 10^4, so I'm beginning to think this may be a client issue
Edit 2: I found 100  matches (limit = 1000) at a time to be reassuringly predictable

**Comment by howardchung** [comment]
If you need a specific ordering you have to specify `ORDER BY match_id, player_slot`

**Comment by howardchung** [comment]
postgres docs:
https://www.postgresql.org/docs/9.5/static/queries-order.html
