### ISSUE TITLE
GET /heroes add language option 

### ISSUE THREAD

**Issue by sh1tge** [odota/core#1496]
Hey,
is it possible to get the heroes in Simplified Chinese?
(using language option and using zh_cn for the language ).

**Comment by howardchung** [comment]
The OpenDota database only stores english, but you can fetch the hero list with localized names like this:
http://api.steampowered.com/IEconDOTA2_570/GetHeroes/v0001?key=X&language=zh

(replace X with your API key)

**Comment by sh1tge** [comment]
thx
