### ISSUE TITLE
Type of match_id and account_id

### ISSUE THREAD

**Issue by Seraphli** [odota/core#1502]
I think the type of these value should be `integer` not `number` in the api. Also there are other values which have the same problem.

**Comment by howardchung** [comment]
Sure, feel free to fix these in routes/spec.js

**Comment by Seraphli** [comment]
When I check the `spec.js`, I find in the response of `GET /players/{account_id}/heroes`, the return type of `hero_id` is `string`, not `integer`. For example:
```
[{"hero_id":"7","last_played":1494597469,"games":48,"win":24,"with_games":103,"with_win":59,"against_games":104,"against_win":49},{"hero_id":"84","last_played":1496838191,"games":47,"win":24,"with_games":54,"with_win":28,"against_games":80,"against_win":38},{"hero_id":"43","last_played":1496238832,"games":46,"win":22,"with_games":32,"with_win":21,"against_games":53,"against_win":19},{"hero_id":"12","last_played":1497020902,"games":45,"win":18,"with_games":49,"with_win":24,"against_games":66,"against_win":36}]
```

**Comment by howardchung** [comment]
Probably need to convert it if we want it to be an integer.

**Comment by Seraphli** [comment]
I changed the type of this `hero_id` from `string` to `integer`. I don't know if it helps.
https://github.com/odota/core/pull/1503/files#diff-c2cee7031a22fda44fd8793505722417L1293
Because I saw the type of other `hero_id` in `spec.js` were `number`, which I changed to `integer`.
