### ISSUE TITLE
Radiant and dire team score on pro matches.

### ISSUE THREAD

**Issue by AnujDutt2701** [odota/core#1505]
Please add radiant and dire team scores for /proMatches endpoint.

**Comment by AnujDutt2701** [comment]
Hi again. Sorry for being impatient but is there an approximate timeline for this?

**Comment by howardchung** [comment]
Sorry, I've just been busy working on other things.  If you submit a PR then I can merge it, otherwise will need to wait until I have some free time.

**Comment by AnujDutt2701** [comment]
Thank you so much for your time. :)
