### ISSUE TITLE
Hero Zeus has a typo in its name for /Hero & /HeroStats response objects

### ISSUE THREAD

**Issue by vreddi** [odota/core#1507]
![zuuserror](https://user-images.githubusercontent.com/6148930/28539458-94a830e6-7066-11e7-8fcc-a86ad3036d7a.PNG)

**zuus** should be **zeus**?

**Comment by coreymaher** [comment]
You'd think so, but no, that's how valve programmed it! ¯\_(ツ)_/¯

**Comment by gu3st** [comment]
Zeus is called "zuus" in DOTA's game files.

**Comment by vreddi** [comment]
All Hail Gaben. 
Closing in that case. 
We were making a hackathon project related to dota and stumbled upon this.
