### ISSUE TITLE
Datetime encoding?

### ISSUE THREAD

**Issue by MatthewRalston** [odota/core#1513]
Hi everyone,
I've been looking at the /explorer (mostly through the UI) and noticed the following.
The UI displays the match start time as a date, while the API encodes `matches.start_time` as an integer. I don't see any comments in the source's table definitions that describe the encoding.

I'd like to convert the integer encoding into the date and/or datetime, and I'm mostly using javascript.
Could you point me in the right direction, using javascript as an example?

Is it as simple as:
```javascript
var matchDate = new Date(match.start_time);
```

**Comment by howardchung** [comment]
I think it's `new Date(match.start_time * 1000)` since JS uses milliseconds

**Comment by MatthewRalston** [comment]
I will verify after hours and close issue. Thank you @howardchung for your help AND for working on this *awesome* tool.

**Comment by howardchung** [comment]
DId it work?

**Comment by howardchung** [comment]
I'll assume it worked, reopen or comment if further questions
