### ISSUE TITLE
The Profiles

### ISSUE THREAD

**Issue by jacobxy** [odota/core#1514]
How many times can a account parse the matches  one day?
When I  use a new account , I find that I can get the matchData at limit times through the function called "getGcMatchData".

**Comment by howardchung** [comment]
100 req/day/account

**Comment by jacobxy** [comment]
It's limited by  the core or by the game server . if I request more than 100 , how long can the account be used again.

**Comment by howardchung** [comment]
It's limited by the Steam server.  Reset period is around 24 hours
