### ISSUE TITLE
MMR on /proPlayers endpoint.

### ISSUE THREAD

**Issue by AnujDutt2701** [odota/core#1517]
Is it possible for you to add mmr information to the response of /proPlayers. Makes ordering rather easy because as of now there's no way to display these results into any other order than alphabetical.

**Comment by howardchung** [comment]
Technically yes, however there is no guarantee that these values would be up to date/available for any given player (since it's subject to the same conditions, such as that the player needs to be displaying MMR data on their profile and expose public match data)

**Comment by AnujDutt2701** [comment]
Do the official MMR leaderboards also have the same constraints?

**Comment by howardchung** [comment]
I think there are other constraints, such as not having the account_id to match and a player needs to have played within the last 14 days or something

**Comment by AnujDutt2701** [comment]
Is there another endpoint where I can get players(pro or not) ordered by their MMRs? I tried to access the players table through the Data Explorer on odota.com but permission was denied. Maybe if you could enable read access? Would that be possible?

**Comment by howardchung** [comment]
no, I think best approach is to implement a separate endpoint that fetches the top 100 players by MMR if that is what you need.

**Comment by howardchung** [comment]
I moved current MMR data to the solo_competitive_rank and competitive_rank postgres tables, so it should be pretty easy to write a SQL query for it and add it as an endpoint.  (might need to build an index on the rating to get the top 100 efficiently though)

**Comment by AnujDutt2701** [comment]
Looks good. I could see the results through the explorer. Thanks a lot. You're doing really good work here! :)
