### ISSUE TITLE
The search does not get all accounts

### ISSUE THREAD

**Issue by JamilHijjawi** [odota/core#1518]
As I know, the app should retrieve the full profile when I search by username or id. But I'm not able to get the profile for some account, You can try this id: `110866117`

**Comment by howardchung** [comment]
If a player has not enabled public match data and never signed into OpenDota through Steam then it's possible we may not have a record of that player.

**Comment by al1991i** [comment]
So we have to enabled public match data **AND** signed into OpenDota through Steam to get the data, or we can get it by enabled public match data only?

**Comment by howardchung** [comment]
either is fine.  The user needs to play matches after enabling public match data though.
