### ISSUE TITLE
I cant fetch data, 

### ISSUE THREAD

**Issue by iFenr1r** [odota/core#1520]
I'm making a chatbot using IBM Watson conversation integrated with OpenDota, but I cant get infos by OpenDota.
using this lane, I dont know if is right
`console.log(nodeDotaApi.playerStats(ID));` 
but give me this
![image](https://user-images.githubusercontent.com/24235361/29427629-c9737ee0-8360-11e7-85e9-4459a6751509.png)

**Comment by iFenr1r** [comment]
I'm using node.js

**Comment by coreymaher** [comment]
Looks like you're using promises and the node-dota-api npm module which is not provided by the open dota developers. You may want to ask the module creator how to use it.

If I had to guess I'd say you probably want something like this:

**Comment by iFenr1r** [comment]
Well, work, but something strange its happening, the program skips `console.log(result);` sommetimes
look
`// Example 1: sets up service wrapper, sends initial message, and
// receives response.ss
var prompt = require('prompt-sync')();
var ConversationV1 = require('watson-developer-cloud/conversation/v1');
var nodeDotaApi = require("node-dota-api")
var mmr;
// Set up Conversation service wrapper.
var conversation = new ConversationV1({
  username: 'a33eb2c9-d218-4e05-a8ff-a46b59c5c3b1', // replace with username from service key
  password: 'VATP3XEHsrPL', // replace with password from service key
  path: { workspace_id: '96cbce3b-2fd3-49b0-ad57-da62c33547ee' }, // replace with workspace ID
  version_date: '2016-07-11'
});

// Start conversation with empty message.
conversation.message({}, processResponse);
// Process the conversation response.
function processResponse(err, response) {
  if (err) {
    console.error(err); // something went wrong
    return;
  }
  var endConversation = false;

  // Check for action flags.
  if (response.output.text.length != 0) {
    console.log(response.output.text[0]);
  }

  if (response.intents.length > 0) {
    if(response.intents[0].intent == 'perfil'){
      if(response.entities.length > 0){

        intent = response.intents[0].intent;
        ID = response.entities[0].value;

        console.log('O ID SELECIONADO FOI: ' + ID); //mostra o ID
        console.log('INTENÇÃO SELECIONADA: ' + intent);

        nodeDotaApi.playerStats("83812302").then(function(result) {
            console.log(result.estMMR)
        });

      }
    }
  }
  // If we're not done, prompt for the next round of input.
  if (!endConversation) {
    var newMessageFromUser = prompt('>> ');
    conversation.message({
      input: { text: newMessageFromUser },
      // Send back the context to maintain state.
      context : response.context,
    }, processResponse)
  }
}`

**Comment by coreymaher** [comment]
It's not super clear to me what issue you're running into, but I bet it is because the `playerStats` promise is asynchronous.
Your prompt at the bottom is probably running before the player stats are fetched.
This is because `playerStats` does not block the thread. Your code continues to run, and then when a response comes back from open dota the function within the `then` is called.

You're probably going to have to move that prompt code so it is only run after you have handled the previous message. Try putting it within your `then` function.

**Comment by howardchung** [comment]
Closing the issue since it's not directly related to this project, but feel free to continue the thread with further questions (or ask on Discord)
