### ISSUE TITLE
No notification on open AI contribution?

### ISSUE THREAD

**Issue by saikrishnadeep** [odota/core#1521]
I think mentioning this sponsorship means a lot to all openAI users and contributors! :+1: 

https://blog.openai.com/more-on-dota-2/

Good job!

**Comment by howardchung** [comment]
We'll probably write an updated financial report (hopefully by the end of the month) and post it to the blog.

@albertcui

**Comment by howardchung** [comment]
I'm pressing @albertcui to add the OpenAI logo to our sponsor list on the home page.  Hopefully he'll get to it soon.

We may be phasing out the donation model and public financial reports soon (probably December timeframe)

**Comment by howardchung** [comment]
Added in https://github.com/odota/ui/pull/1279
