### ISSUE TITLE
Cannot access item ids

### ISSUE THREAD

**Issue by mobyte0** [odota/core#1524]
Hello, I am trying to find out where in the API that I can find the information regarding in-game item IDs (such as tangos, battle fury, blink dagger, etc). Similar to how you can find the up-to-date hero information with `https://api.opendota.com/api/heroes`, I was also hoping there is something similar in the essence of `https://api.opendota.com/api/items`. I found in the schema (https://api.opendota.com/api/schema) it says:
```
{"table_name":"items","column_name":"id","data_type":"integer"},{"table_name":"items","column_name":"name","data_type":"text"},{"table_name":"items","column_name":"cost","data_type":"integer"},{"table_name":"items","column_name":"secret_shop","data_type":"smallint"},{"table_name":"items","column_name":"side_shop","data_type":"smallint"},{"table_name":"items","column_name":"recipe","data_type":"smallint"},{"table_name":"items","column_name":"localized_name","data_type":"text"},
```
but I cannot find anything resembling this at `https://api.opendota.com/api/items`. I cannot find any information relating to this in the documentation, either. I was hoping I could be directed to where this information could be found.

**Comment by howardchung** [comment]
See the dotaconstants repo for "static" data that doesn't require an API to serve it:

https://github.com/odota/dotaconstants/blob/master/build/items.json

**Comment by mobyte0** [comment]
Ah, I see. Many thanks. Your work on these repos is much appreciated, keep it up.
