### ISSUE TITLE
Enemy team's spirit bear among damage dealt statistics

### ISSUE THREAD

**Issue by runfalk** [odota/core#1527]
I assume this is where this bug goes.

I was against a Lone Druid yesterday and the Spirit bear shows up as damage I've dealt. The same goes for all of my teammates. The bear also shows up as damage taken, for Lone druid himself.

https://www.opendota.com/matches/3413786602/combat

**Comment by howardchung** [comment]
Actual attack damage from the bear would be included in autoattacks

**Comment by runfalk** [comment]
I didn't think of that. That's probably it, though it's slightly confusing in the UI.
