### ISSUE TITLE
Attribute missing from /heroStats

### ISSUE THREAD

**Issue by AnujDutt2701** [odota/core#1533]
'pro_bans' attribute missing in Crystal Maiden's response object as of today.

**Comment by howardchung** [comment]
That probably means it's 0

**Comment by AnujDutt2701** [comment]
Shouldn't the response contain pro_ban with the value as 0? Or should I be checking this for all attributes returned?

**Comment by howardchung** [comment]
I made a fix to the SQL to always return a value (even if 0) for the pro_picks/pro_bans field.

I haven't done the same for the public pick stats, but hopefully those will never be 0.
