### ISSUE TITLE
Peers endpoint doesn't update

### ISSUE THREAD

**Issue by ktestpi** [odota/core#1534]
I have played with some friends last 30 days, and i use https://api.opendota.com/api/players/112840925/peers?date=30 to get last 30 days and i get a void object. 

Some new friends don't appear in https://api.opendota.com/api/players/112840925/peers

Friends IDs: 383385997 and 56691503

Is someone getting the same problem?

**Comment by howardchung** [comment]
Ah ok, there's probably a simple answer to this:

The backend filters out players unless they have at least 5 games with you.  Otherwise, there would be thousands of players listed :)

**Comment by howardchung** [comment]
If you want to find those friends you can still use the matches list and the included account ID filter:
https://www.opendota.com/players/112840925/matches?included_account_id=383385997

**Comment by ktestpi** [comment]
Thank you so much! 😄 That has sense.
