### ISSUE TITLE
XP advantage not equalising after all heros are 25?

### ISSUE THREAD

**Issue by TrentBartlem** [odota/core#1535]
In [this game](https://www.opendota.com/matches/3468896824), there is a net 2085xp Radiant advantage even after all heros are level 25, and I can't see a reason why.

**Comment by binhonglee** [comment]
Not exactly sure if this is an OpenDota problem. If you check this game in the Dota 2 client, I believe it shows the same numbers too.

**Comment by TrentBartlem** [comment]
I guess there's nothing that can be done, then :(

**Comment by howardchung** [comment]
Yeah what happens is that heroes stop accruing xp at level 25, but the point at which they stop is not the same (depending on how much xp they got in the final increment)

**Comment by TrentBartlem** [comment]
In that game, though, neither team chose +xp talents so it should have been equal.

**Comment by howardchung** [comment]
that's not the problem, for example, it has to do with the last tick of experience received by the player.

Say the level 25 threshold is at 60000 XP, and both player A and B are at level 24 with 59990 XP:

If player A kills a creep for 30xp, they get to level 25 with 60020 XP.
If player B kils la hero for 300 xp, they get to level 25 with 60290 XP.

**Comment by TrentBartlem** [comment]
oh ok. Odd but I guess that's just the way the data is.
