### ISSUE TITLE
Website goes blank after Trends/Graph has 0 entities

### ISSUE THREAD

**Issue by likered** [odota/core#1545]
I've noticed that in the Trends tab, for the graph, if you have 0 occurrences in the last 20 games you will be forced into an empty page with a ReactJS error: https://puu.sh/xUmrv/f8e2bbe438.png

A direct example can be seen on my OpenDota - Rapiers Purchased graph: https://www.opendota.com/players/107173931/trends/purchase_rapier

**Comment by howardchung** [comment]
Thanks, we just made a fix for this and will deploy it soon (it was an issue on odota/ui)
