### ISSUE TITLE
https://api.opendota.com/api/teams/{team_id}/matches - Data returned not matching response samples.

### ISSUE THREAD

**Issue by AnujDutt2701** [odota/core#1550]
{"match_id":3497871676,"radiant_win":false,"radiant":false,"duration":1919,"start_time":1507826158,"leagueid":5579,"league_name":"SL i-League Invitational Season 3","cluster":132}

Team names, ids, scores are missing.

**Comment by howardchung** [comment]
I reused the same match object as the documentation so not all fields will be available.

I will probably add the opponent's team name to the response though.

**Comment by AnujDutt2701** [comment]
team_id team_name and logo_url for the opponent, series_id to be able to group the games if possible please.
