### ISSUE TITLE
Patch Reset for Hero Top 100 Rankings

### ISSUE THREAD

**Issue by booshack** [odota/core#1558]
Asked several people this already, but is there a possibility anyone with more experience than me can make this happen? The current ranking system is nice for determining players who've performed the best on a hero of all time, but for practicality, a ranking system that reset every patch would super fasttrack the settling of meta-dust.

Using Dueling Fates as an example, everyone has no clue how good the reworked and new heroes really are - on paper, Tiny and Morphling seem like they suck, but there's so many different combinations of strategies that no one can be sure. I mean everyone is saying Pangolier sucks, but there are people on the OpenDota rankings (essentially a patch reset for the new heroes) who have 70-80% winrates on him, and iceiceice is performing exceptionally on him, so we now have a better idea of how he works and how to play him; thus I've been addicted to the hero rankings for the new heroes lately. Tinker was an average hero until Merlini thought of using BoTs on him. It'd be so exciting to be able to do the same with the other heroes who have abysmal winrates!

I think it would be fairly simple to duplicate the current ranking function, and change it to only fetch matches from the patch's match.start_time in dotaconstants (which is changed manually anyway)? Or even just call the getPatchIndex function from utility.js? I can't be sure though, started learning node.js from scratch a few days ago so it would take me a while to get anything done - I'm interested in starting a discussion with people more experienced than me or even getting some help to submit a PR for this?

**Comment by booshack** [comment]
Sorry just for clarification I mean a separate rankings from the existing one, not replacing it.

**Comment by howardchung** [comment]
Due to the time it takes for rankings to settle, and Valve's new model of shipping a new patch every 2 weeks, I don't think this is possible anymore.
