### ISSUE TITLE
Test new hero rankings algorithm (Elo-based)

### ISSUE THREAD

**Issue by kxxoling** [odota/core#1562]
This is my rankings: https://www.opendota.com/players/121230511/rankings

As I see, this is ranking of me at any heroes:

1. I played Bristleback many times, but it does not suit me well, I have only 43% winning rate when I play Bristleback. So I guess it should be a low rating while it's 4th!
2. I played QOP only a few times which I don't think there should be a stable ranking there, but it's 1st on my list.
3. Pudge is 1 of my favorite hero, 60% winning ranking (remove the training matches it would be higher.), 10 continuing winning twice! But it's on the second page!
4. Riki a hero I played with 68% winning rate! And it disappeared from the list...

**Comment by kxxoling** [comment]
I captured the request: https://api.opendota.com/api/players/121230511/rankings

There's only 61 heroes. Is this normal?

**Comment by howardchung** [comment]
You'll only have a ranking for heroes you've played since the rankings started.

The rankings are relative to other players playing the hero, so you should not compare rankings on different heroes against each other.  Depending on how popular the hero is, similar performance on different heroes will not produce the same results.

**Comment by kxxoling** [comment]
This is another ranking forecast from dotamax:
![img_5628](https://user-images.githubusercontent.com/1227139/32938072-945bd8ec-cb40-11e7-9f69-c16583230734.PNG)

I think it's much reasonable.

Though I played QOP a lot of time these days, but half of them are losing: https://www.opendota.com/players/121230511/matches?hero_id=39

I don't think a 47% winning rate could be 97% high level.

As it to Zeus which I got 55% winning rate, but most of the winning matches are more then 1 year ago at normal matches. I got a poor winning rate recently at high and very high level: https://www.opendota.com/players/121230511/matches?hero_id=22

But Zeus is 7th on my list. You may doubt that most of people plays Zeus worse then me. But as the statistical data says, Zeus is always one of the highest winning rate heroes in recent versions of Dota 2. I play Zeus worse than the average.

As a consult, Dotamax count your hero ranking based on your behavior in first 15 matches and their level, then you'll get a rough hero MMR. This hero MMR will increase or decrease based on match result and your hero MMR and average Match MMR. When you win a match with this hero much lower than match MMR, your hero MMR would Increase a lot:

![img_5630](https://user-images.githubusercontent.com/1227139/32939008-bb2fa306-cb43-11e7-9f7a-33772a89aeda.PNG)

**Comment by howardchung** [comment]
Hmm, that's an interesting idea, to start all players off at some base rating value (3000?) and use Elo rating on each match, where the average MMR of the match is considered the opponent.

I'll create a new rankings table and start testing it!

**Comment by howardchung** [comment]
I guess to account for MMR, players should start at a value based on the average MMR in the matches they're playing.

**Comment by howardchung** [comment]
If we're scaling to valve values I think valve uses a kfactor of 50 (expected +/- 25)

**Comment by kxxoling** [comment]
Maybe ``k`` could be a variable based on the matches count you played one hero, the more you played, the less ``k`` is.

As to base value, I guess a number which is a little less than player's MMR is reasonable.

BTW, I don't think the ranking page need a pagination, you can show all the heroes in one page as Dotamax did. It would be a trouble even on mobile devices.

**Comment by howardchung** [comment]
This has been implemented.  It is taking a while for the best players to float to the top, I may increase the k-value to move top players up more rapidly.
