### ISSUE TITLE
replace mmr_estimate with rank_tier_estimate

### ISSUE THREAD

**Issue by howardchung** [odota/core#1565]
Done
====
- [x] public_matches table needs a new column for avg_rank_tier since we don't have avg_mmr anymore (well we do but it will slowly get more and more inaccurate)
- [x] meta explorer needs to be updated to use ranks not mmr
- [x] create new postgres table to track current player ranks (rank_tier)

Need to wait for more data to come in
====
- [x] heroStats API/table needs to be updated to use ranks not MMRs
- [x] hero ranking algorithm needs to be reworked (was planning to do this anyway with #1562 )
- [ ] replace mmr_estimate with rank_tier_estimate

**Comment by daxim** [comment]
Accurate MMR is reportedly shown in the Dota2 client. For those users who want to keep tracking the number and look at the chart at `/players/?????????/mmr`, what options are there?

* Voluntary reporting via Web form?
* A small native application (running along-side the Dota2 client on each of the three supported operating systems) implementing [SteamKit](https://github.com/paralin/Dota2) and listening to the MMR protobuf message and automatically passing it on to the Yasp database?

**Comment by howardchung** [comment]
TBH I'm not really a fan of either approach, since both will suffer from much lower response rates.

**Comment by howardchung** [comment]
I don't think this is as necessary anymore with medals being public information.
