### ISSUE TITLE
priority parsing on pro matches

### ISSUE THREAD

**Issue by heqiuzhi** [odota/core#1567]

**Comment by howardchung** [comment]
Can this be mitigated by requesting manual parse on the desired matches?

**Comment by howardchung** [comment]
The queue does have priority logic, we could assign a priority of 0 (lower is higher priority) based on whether match.leagueid is set:
https://github.com/odota/core/blob/a1fff019514e6f6d7dc9b9949c6f8ad1dbcfecf0/store/queries.js#L1213

**Comment by howardchung** [comment]
This was implemented to work around parsing delays around TI 2023 time
