### ISSUE TITLE
Data Dump File Format

### ISSUE THREAD

**Issue by mattscchan** [odota/core#1568]
Hi, I'm trying to parse the most recent data dump and I realized that it's not in JSON format. Would you happen to be able to provide an easy way to parse the data? Specifically what seems to be like nested JSON-like objects that are used to represent the chats. For example, this is what I get after using a CSV-parser to get the chat column.

{"{\"time\":2728,\"type\":\"chat\",\"unit\":\"Darren\",\"key\":\"gg\",\"slot\":2,\"player_slot\":2}","{\"time\":2733,\"type\":\"chat\",\"unit\":\"haTaTiTla\",\"key\":\"gg\",\"slot\":1,\"player_slot\":1}"}

Thanks, 
Matt

**Comment by howardchung** [comment]
The chat should be an array of JSON objects (start and end with `[]`).  Are you sure your parser isn't processing this weirdly?

**Comment by mattscchan** [comment]
I had no trouble parsing the 2015 data with a slightly modified version of the code snippet on the information page. But the same code isn't working with the more recent data dump. Seeing as I can't  open the larger file in memory, I'm basing my parsing on the "matches_small.csv" file format which appears to be a weird combination of csv and JSON formatting.

**Comment by howardchung** [comment]
The 2015 data was in a different format so the same code won't work.

The new data is a CSV dump where some of the fields are JSON strings.

**Comment by mattscchan** [comment]
Would you be able to recommend a parsing library that could adequately parse the newer format? I'm unable to turn the JSON strings into JSON objects after trying to use many different CSV parsers followed by JSON parsing for the chat column.

**Comment by howardchung** [comment]
If you just read a line out of the csv file, you should be able to split it by commas, and then a JavaScript `JSON.parse()` should work on the column.

If you'd like me to investigate further, can you share an example line from one of the CSV files that has a JSON column?

**Comment by howardchung** [comment]
It's possible your CSV parsers are removing quotes that your JSON parser is expecting

**Comment by mattscchan** [comment]
I'm using the JS "fast-csv" library to parse the CSV rows and then I try to use the JSON.parse() on the resulting "chat" column. In file, this column looks like this: 

> "{""{\""time\"":2728,\""type\"":\""chat\"",\""unit\"":\""Darren\"",\""key\"":\""gg\"",\""slot\"":2,\""player_slot\"":2}"",""{\""time\"":2733,\""type\"":\""chat\"",\""unit\"":\""haTaTiTla\"",\""key\"":\""gg\"",\""slot\"":1,\""player_slot\"":1}""}","{""{\""time\"":174,\""type\"":\""CHAT_MESSAGE_FIRSTBLOOD\"",\""value\"":353,\""player1\"":2,\""player2\"":8,\""slot\"":2,\""player_slot\"":2}"",""{\""time\"":758,\""type\"":\""CHAT_MESSAGE_TOWER_KILL\"",\""value\"":3,\""player1\"":-1,\""player2\"":-1,\""team\"":3,\""slot\"":-1}"",""{\""time\"":1081,\""type\"":\""CHAT_MESSAGE_TOWER_KILL\"",\""value\"":3,\""player1\"":7,\""player2\"":-1,\""team\"":3,\""slot\"":7,\""player_slot\"":130}"",""{\""time\"":1183,\""type\"":\""CHAT_MESSAGE_TOWER_KILL\"",\""value\"":2,\""player1\"":-1,\""player2\"":-1,\""team\"":2,\""slot\"":-1}"",""{\""time\"":1196,\""type\"":\""CHAT_MESSAGE_TOWER_KILL\"",\""value\"":3,\""player1\"":-1,\""player2\"":-1,\""team\"":3,\""slot\"":-1}"",""{\""time\"":1402,\""type\"":\""CHAT_MESSAGE_TOWER_KILL\"",\""value\"":3,\""player1\"":7,\""player2\"":-1,\""team\"":3,\""slot\"":7,\""player_slot\"":130}"",""{\""time\"":1798,\""type\"":\""CHAT_MESSAGE_TOWER_KILL\"",\""value\"":3,\""player1\"":7,\""player2\"":-1,\""team\"":3,\""slot\"":7,\""player_slot\"":130}"",""{\""time\"":1829,\""type\"":\""CHAT_MESSAGE_TOWER_KILL\"",\""value\"":3,\""player1\"":-1,\""player2\"":-1,\""team\"":3,\""slot\"":-1}"",""{\""time\"":1849,\""type\"":\""CHAT_MESSAGE_TOWER_KILL\"",\""value\"":3,\""player1\"":7,\""player2\"":-1,\""team\"":3,\""slot\"":7,\""player_slot\"":130}"",""{\""time\"":2032,\""type\"":\""CHAT_MESSAGE_ROSHAN_KILL\"",\""value\"":200,\""player1\"":3,\""player2\"":-1,\""team\"":3}"",""{\""time\"":2035,\""type\"":\""CHAT_MESSAGE_AEGIS\"",\""value\"":0,\""player1\"":5,\""player2\"":-1,\""slot\"":5,\""player_slot\"":128}"",""{\""time\"":2159,\""type\"":\""CHAT_MESSAGE_TOWER_KILL\"",\""value\"":3,\""player1\"":7,\""player2\"":-1,\""team\"":3,\""slot\"":7,\""player_slot\"":130}"",""{\""time\"":2170,\""type\"":\""CHAT_MESSAGE_BARRACKS_KILL\"",\""value\"":512,\""player1\"":7,\""player2\"":-1,\""key\"":\""512\""}"",""{\""time\"":2390,\""type\"":\""CHAT_MESSAGE_BARRACKS_KILL\"",\""value\"":64,\""player1\"":7,\""player2\"":-1,\""key\"":\""64\""}"",""{\""time\"":2393,\""type\"":\""CHAT_MESSAGE_BARRACKS_KILL\"",\""value\"":128,\""player1\"":9,\""player2\"":-1,\""key\"":\""128\""}"",""{\""time\"":2406,\""type\"":\""CHAT_MESSAGE_BARRACKS_KILL\"",\""value\"":256,\""player1\"":7,\""player2\"":-1,\""key\"":\""256\""}"",""{\""time\"":2417,\""type\"":\""CHAT_MESSAGE_TOWER_KILL\"",\""value\"":3,\""player1\"":7,\""player2\"":-1,\""team\"":3,\""slot\"":7,\""player_slot\"":130}"",""{\""time\"":2577,\""type\"":\""CHAT_MESSAGE_TOWER_KILL\"",\""value\"":3,\""player1\"":7,\""player2\"":-1,\""team\"":3,\""slot\"":7,\""player_slot\"":130}"",""{\""time\"":2583,\""type\"":\""CHAT_MESSAGE_TOWER_KILL\"",\""value\"":3,\""player1\"":-1,\""player2\"":-1,\""team\"":3,\""slot\"":-1}"",""{\""time\"":2636,\""type\"":\""CHAT_MESSAGE_BARRACKS_KILL\"",\""value\"":1024,\""player1\"":-1,\""player2\"":-1,\""key\"":\""1024\""}"",""{\""time\"":2639,\""type\"":\""CHAT_MESSAGE_BARRACKS_KILL\"",\""value\"":2048,\""player1\"":9,\""player2\"":-1,\""key\"":\""2048\""}""}"

And the printing the parsed column to screen returns:

> {"{\"time\":174,\"type\":\"CHAT_MESSAGE_FIRSTBLOOD\",\"value\":353,\"player1\":2,\"player2\":8,\"slot\":2,\"player_slot\":2}","{\"time\":758,\"type\":\"CHAT_MESSAGE_TOWER_KILL\",\"value\":3,\"player1\":-1,\"player2\":-1,\"team\":3,\"slot\":-1}","{\"time\":1081,\"type\":\"CHAT_MESSAGE_TOWER_KILL\",\"value\":3,\"player1\":7,\"player2\":-1,\"team\":3,\"slot\":7,\"player_slot\":130}","{\"time\":1183,\"type\":\"CHAT_MESSAGE_TOWER_KILL\",\"value\":2,\"player1\":-1,\"player2\":-1,\"team\":2,\"slot\":-1}","{\"time\":1196,\"type\":\"CHAT_MESSAGE_TOWER_KILL\",\"value\":3,\"player1\":-1,\"player2\":-1,\"team\":3,\"slot\":-1}","{\"time\":1402,\"type\":\"CHAT_MESSAGE_TOWER_KILL\",\"value\":3,\"player1\":7,\"player2\":-1,\"team\":3,\"slot\":7,\"player_slot\":130}","{\"time\":1798,\"type\":\"CHAT_MESSAGE_TOWER_KILL\",\"value\":3,\"player1\":7,\"player2\":-1,\"team\":3,\"slot\":7,\"player_slot\":130}","{\"time\":1829,\"type\":\"CHAT_MESSAGE_TOWER_KILL\",\"value\":3,\"player1\":-1,\"player2\":-1,\"team\":3,\"slot\":-1}","{\"time\":1849,\"type\":\"CHAT_MESSAGE_TOWER_KILL\",\"value\":3,\"player1\":7,\"player2\":-1,\"team\":3,\"slot\":7,\"player_slot\":130}","{\"time\":2032,\"type\":\"CHAT_MESSAGE_ROSHAN_KILL\",\"value\":200,\"player1\":3,\"player2\":-1,\"team\":3}","{\"time\":2035,\"type\":\"CHAT_MESSAGE_AEGIS\",\"value\":0,\"player1\":5,\"player2\":-1,\"slot\":5,\"player_slot\":128}","{\"time\":2159,\"type\":\"CHAT_MESSAGE_TOWER_KILL\",\"value\":3,\"player1\":7,\"player2\":-1,\"team\":3,\"slot\":7,\"player_slot\":130}","{\"time\":2170,\"type\":\"CHAT_MESSAGE_BARRACKS_KILL\",\"value\":512,\"player1\":7,\"player2\":-1,\"key\":\"512\"}","{\"time\":2390,\"type\":\"CHAT_MESSAGE_BARRACKS_KILL\",\"value\":64,\"player1\":7,\"player2\":-1,\"key\":\"64\"}","{\"time\":2393,\"type\":\"CHAT_MESSAGE_BARRACKS_KILL\",\"value\":128,\"player1\":9,\"player2\":-1,\"key\":\"128\"}","{\"time\":2406,\"type\":\"CHAT_MESSAGE_BARRACKS_KILL\",\"value\":256,\"player1\":7,\"player2\":-1,\"key\":\"256\"}","{\"time\":2417,\"type\":\"CHAT_MESSAGE_TOWER_KILL\",\"value\":3,\"player1\":7,\"player2\":-1,\"team\":3,\"slot\":7,\"player_slot\":130}","{\"time\":2577,\"type\":\"CHAT_MESSAGE_TOWER_KILL\",\"value\":3,\"player1\":7,\"player2\":-1,\"team\":3,\"slot\":7,\"player_slot\":130}","{\"time\":2583,\"type\":\"CHAT_MESSAGE_TOWER_KILL\",\"value\":3,\"player1\":-1,\"player2\":-1,\"team\":3,\"slot\":-1}","{\"time\":2636,\"type\":\"CHAT_MESSAGE_BARRACKS_KILL\",\"value\":1024,\"player1\":-1,\"player2\":-1,\"key\":\"1024\"}","{\"time\":2639,\"type\":\"CHAT_MESSAGE_BARRACKS_KILL\",\"value\":2048,\"player1\":9,\"player2\":-1,\"key\":\"2048\"}"}

As you suggested, it seems that the CSV parser is removing quotes that the JSON parser is expecting, but not quite sure how to remedy this. Any help would be greatly appreciated. Thanks!

**Comment by howardchung** [comment]
You can try using a different library, or checking the documentation to see if there's a setting that will preserve the quotes.

Alternatively since the data was generated from postgres database, you could try importing the csv file into a postgres database and reading it back out
