### ISSUE TITLE
Dark Willow is not in captains mode

### ISSUE THREAD

**Issue by Turmfalke2** [odota/core#1572]
At least I am pretty sure of that, however https://www.opendota.com/heroes/119 states CM enabled: yes

**Comment by howardchung** [comment]
https://github.com/odota/dotaconstants/blob/master/build/heroes.json#L4066 indicates that dark willow is CM-enabled, is that not the case?

Can anyone confirm?

**Comment by bippum** [comment]
She's not in captains mode, she's grayed out.

**Comment by howardchung** [comment]
Is the issue with the d2vpkr data or the dotaconstants update task?

**Comment by howardchung** [comment]
https://github.com/dotabuff/d2vpkr/blob/master/dota/scripts/npc/npc_heroes.json#L19366

https://github.com/odota/dotaconstants/blob/master/tasks/updateconstants.js#L647

I think the dotaconstants code need to be fixed since "0" evaluates to true
