### ISSUE TITLE
False display of the ranking as Unknown

### ISSUE THREAD

**Issue by Alehandrow** [odota/core#1573]
Hi, I was looking at one of my Games played recently, while i noticed that the rankings of 3 players (Axe Legend 1, Undying -> Legend 0, Wraith King -> Legend 1) were displayed as Unknown although they had a ranking already (in original Replay). Is it because of Steam account privacy or maybe a mistake somewhere else, like a parsing mistake?

**Comment by howardchung** [comment]
match ID?

**Comment by Alehandrow** [comment]
Damn your fast in replying =), 3597698896.

**Comment by howardchung** [comment]
The ranks are not linked to the replay but to the account ID.  Since these players are anonymous in the match we don't display their ranks either.

**Comment by Alehandrow** [comment]
Thank you very much for the explanation.
