### ISSUE TITLE
Add API for scenarios data

### ISSUE THREAD

**Issue by howardchung** [odota/core#1575]
A "scenario" is a particular combination of factors that are present in a match.

We want to store the count of matches where this happens, and the number of matches that were wins.

Examples
====
For the following: How often does this happen and what is the winrate when it does?
* Hero: Earthshaker is picked
* Hero + Item: Earthshaker buys a blink dagger at any point
* Hero + Item + Time: Earthshaker buys blink dagger before 10 minutes.  
* Hero + Stat: Earthshaker gets 10 kills
* Hero + Lane: Earthshaker goes mid
* Hero + Item + Tier: Earthshaker buys blink dagger in a Herald game

Design
====
* We would want to add a new postgres table called "scenarios" with the following columns:
  * hero
  * item
  * lh10 (and another column for each stat we might want to use in a scenario)
  * time (in seconds, as a before condition)
  * games
  * wins

After each parsed match, as part of the insertion step, evaluate the list of conditions (they will be "true" or "false" for each match and "won" or "lost") and increment the counts accordingly.
  * If "true" and "won", increment both games and wins
  * If "true" and "lost", increment games but not wins
  * Otherwise, ignore

We can assemble a list of conditions to check by permuting a list of items with cost over 2000 (as an example) and heroes, and adding any additional scenarios such as LH10 that we might care about.

Eventually we should be able to establish a list of conditions with high winrates, as well as allow users to query for scenarios involving certain heroes/items/etc. and discover what the winrates for those scenarios are.

Considerations:
We might need to do something to avoid duplicating inserts if the match is requested for reparse.  Possibly only do this if the source is scanner.

Since this step might be somewhat expensive, we may want to implement this logic as a new service, and have the parse insertion randomly push match IDs into a redis list.  The new service can consume this list as a queue, request the match object (using `buildMatch`) and do the scenario checks on that.

**Comment by SheepD** [comment]
this sounds like a great epic.

some suggestions...

* i think keeping track of the games where the scenario isn't met is still a somewhat valuable metric. this would could give us an insight on how difficult it is to pull something like that off or ratio at which the scenario occurs in the wild.
* MMR might also be interesting to track in buckets(or mmr groups) so we can check if MMR plays a role in the success of a certain scenario

**Comment by howardchung** [comment]
a "base" scenario consisting of just `hero_id` and no other columns could serve as a value to divide against.  That would always evaluate to true for a match that contained that hero.

MMR data is slowly drifting out of date since the ranked change, but we could do something similar with rank tier.

**Comment by SheepD** [comment]
that sounds great. would love to work with you on some parts of this feature

**Comment by Syed21Habib** [comment]
For An Help i like to know, how i coverse my 2500 win and 5k match 8k hour
play to Medel Rank like Archone Or Legend, I Never Play Dota Seriously For
MMR And in the End I found Myself @ 1/2 medels, where my 22 lvl id got
legend :o ANy Way to fix the medel dota give to my original id?

**Comment by howardchung** [comment]
data collection implemented in #1585, we still need to add the APIs to read the data and decide how we want to display it on UI.
