### ISSUE TITLE
Replace 'team_id' with 'team_name' when exporting results from explorer

### ISSUE THREAD

**Issue by semenoffalex** [odota/core#1576]
Currently the results of a query are exported with 'team_id' instead of 'team_name' and the workaround is quite painful. It would be great if all the exports and API calls would return team/player names the same way Explorer returns them.

Here is an example query:
```
SELECT
team_match.team_id,
count(distinct player_matches.hero_id) distinct_heroes,
count(distinct matches.match_id) count
FROM matches
JOIN match_patch using(match_id)
JOIN leagues using(leagueid)
JOIN player_matches using(match_id)
JOIN heroes on heroes.id = player_matches.hero_id
LEFT JOIN notable_players ON notable_players.account_id = player_matches.account_id AND notable_players.locked_until = (SELECT MAX(locked_until) FROM notable_players)
LEFT JOIN teams using(team_id)
JOIN team_match ON matches.match_id = team_match.match_id AND (player_matches.player_slot < 128) = team_match.radiant
WHERE TRUE
AND player_matches.hero_id IS NOT NULL
AND matches.leagueid = 5504
AND matches.start_time >= extract(epoch from timestamp '2017-12-06T21:00:00.000Z')
GROUP BY team_match.team_id
HAVING count(distinct matches.match_id) >= 1
ORDER BY distinct_heroes DESC NULLS LAST
```

**Comment by howardchung** [comment]
We can probably change the query template to replace ID with team name, since we don't have team pages to link to anyway.

However, doing this loses the ID field which is required to link to a page, so if we did this for players it would break the player links in the table.

**Comment by howardchung** [comment]
fixed in odota/ui, you can test on https://stage.opendota.com
