### ISSUE TITLE
Lost league matches(ROG MASTERS 2017)

### ISSUE THREAD

**Issue by heqiuzhi** [odota/core#1578]
![image](https://user-images.githubusercontent.com/20917714/34022204-d9e169a6-e178-11e7-99ef-72a6649a00c4.png)
Can not find the last five matches in OPENDOTA's matches table.
![image](https://user-images.githubusercontent.com/20917714/34022230-02ff0d2a-e179-11e7-8ae1-b29913e59004.png)

![image](https://user-images.githubusercontent.com/20917714/34022245-204c1260-e179-11e7-85c1-153b6e6e34b0.png)

![image](https://user-images.githubusercontent.com/20917714/34022250-2e5d1642-e179-11e7-8eef-7312cfa6ba38.png)

**Comment by howardchung** [comment]
For some reason league 5506 seems to be missing from the GetLeagueListing endpoint:
http://api.steampowered.com/IDOTA2Match_570/GetLeagueListing/v1/

**Comment by heqiuzhi** [comment]
![image](https://user-images.githubusercontent.com/20917714/34027864-74368f9c-e19a-11e7-9c26-c11130d01d6a.png)
But the match(matchid = 3603282282) exists in OPENDOTA's matches table?
![image](https://user-images.githubusercontent.com/20917714/34027896-c32a8a90-e19a-11e7-8860-76f16ad52150.png)

**Comment by howardchung** [comment]
That match has a different league id: 5638

https://api.opendota.com/api/matches/3603282282
