### ISSUE TITLE
[DOCUMENTATION] describe object fields

### ISSUE THREAD

**Issue by howardchung** [odota/core#1581]
Our current documentation often has bare-bones descriptions of each field (mostly just the name of the field).  We should write out more detailed descriptions to improve the docs.

**Comment by MADLAB96** [comment]
I'm new to the project and I decided to try and make this my first contribution. I made a number of changes to the object field descriptions locally but git says I do not have permission to push my branch to origin. Is this intended? If so how could I get permission to push? Thanks.

**Comment by howardchung** [comment]
I've added you to the team, however, you can also submit a PR by forking the repo and making the change on your fork.

**Comment by MADLAB96** [comment]
Sounds good, pull request made.
