### ISSUE TITLE
[QUESTION] What does start_time stands for? 

### ISSUE THREAD

**Issue by ugenlik** [odota/core#1582]
Example 
When I request a match I get ` "start_time": 1513591882`  is that `timeIntervalSince1970` ? 

Is it in seconds?

**Comment by Syed21Habib** [comment]
Start Time MEans??? 1st Game ?

**Comment by coreymaher** [comment]
Yes that's a unix timestamp which is the number of seconds since 1970-01-01 00:00 UTC.

**Comment by ugenlik** [comment]
@Syed21Habib  why is not UTC , when I assume it is seconds 

```
var  finalTime = Date().timeIntervalSince1970  - start_time
var hours = finalTime/(360*24) 
```
hours should be correct but it doesn't seem to be correct. 

it is a simple question, has nothing to do if I play dota or not....

**Comment by coreymaher** [comment]
That calculation seems a bit off. There are 3600 seconds in an hour (60*60). It looks like you're trying to calculate the number of days since the match. That would be:

**Comment by ugenlik** [comment]
Ahhh correct, thanks @coreymaher
