### ISSUE TITLE
enable players table in explorer

### ISSUE THREAD

**Issue by MatthewRalston** [odota/core#1584]
I am getting [permission denied errors](https://api.opendota.com/api/explorer?sql=SELECT%0A%20%20%20%20matches.match_id%2C%0A%20%20%20%20matches.start_time%2C%0A%20%20%20%20((player_matches.player_slot%20%3C%20128)%20%3D%20matches.radiant_win)%20win%2C%0A%20%20%20%20player_matches.hero_id%2C%0A%20%20%20%20notable_players.name%2C%0A%20%20%20%20player_matches.account_id%2C%0A%20%20%20%20heroes.localized_name%2C%0A%20%20%20%20players.avatarfull%2C%0A%20%20%20%20leagues.name%20leaguename%2C%0A%20%20%20%20matches.radiant_team_name%2C%0A%20%20%20%20matches.dire_team_name%20FROM%20matches%0A%20%20%20%20JOIN%20match_patch%20using(match_id)%0A%20%20%20%20JOIN%20leagues%20using(leagueid)%0A%20%20%20%20JOIN%20player_matches%20using(match_id)%0A%20%20%20%20JOIN%20heroes%20on%20heroes.id%20%3D%20player_matches.hero_id%0A%20%20%20%20LEFT%20JOIN%20notable_players%20ON%20notable_players.account_id%20%3D%20player_matches.account_id%20AND%20notable_players.locked_until%20%3D%20(SELECT%20MAX(locked_until)%20FROM%20notable_players)%0A%20%20%20%20LEFT%20JOIN%20players%20ON%20players.account_id%20%3D%20player_matches.account_id%0A%20%20%20%20LEFT%20JOIN%20teams%20using(team_id)%20WHERE%20TRUE%20AND%20leagues.name%20%3D%20%27The%20International%202017%27%20ORDER%20BY%20matches.match_id%20DESC%20NULLS%20LAST) on a query that worked 3 months ago

```javascript
  function sqlQuery(year, team){
    var selection = `SELECT
    matches.match_id,
    matches.start_time,
    ((player_matches.player_slot < 128) = matches.radiant_win) win,
    player_matches.hero_id,
    notable_players.name,
    player_matches.account_id,
    heroes.localized_name,
    players.avatarfull,
    leagues.name leaguename,
    matches.radiant_team_name,
    matches.dire_team_name`;
    var from = ` FROM matches
    JOIN match_patch using(match_id)
    JOIN leagues using(leagueid)
    JOIN player_matches using(match_id)
    JOIN heroes on heroes.id = player_matches.hero_id
    LEFT JOIN notable_players ON notable_players.account_id = player_matches.account_id AND notable_players.locked_until = (SELECT MAX(locked_until) FROM notable_players)
    LEFT JOIN players ON players.account_id = player_matches.account_id
    LEFT JOIN teams using(team_id)`;
    var where = ` WHERE TRUE AND leagues.name = 'The International ${year}'`;
    if (team != null) {
      where += ` AND (notable_players.team_name = '${team}' OR notable_players.team_tag = '${team}')`;
    }
    return selection + from + where + " ORDER BY matches.match_id DESC NULLS LAST";
  };

```

In September 2017, it was possible to retrieve the avatar without any issue from this single SQL query to the explorer endpoint. Now, the players table seems locked w.r.t. the endpoint. What happened?

**Comment by howardchung** [comment]
Looks like I removed the players table from the whitelist in August:
https://github.com/odota/core/commit/a6f14521bea00559b919dd1bce8a29e256d3a3e1#diff-c834adb436e98b921981952dbc9f77b3

According to the commit message there were performance issues.  There have been a few requests to bring it back, I might do that in the future.

**Comment by MatthewRalston** [comment]
Can you describe the performance issues? Is this related to a common join process used by the explorer? I would think that performance issues related to a specific table is simply an optimization problem, not a whitelist/blacklist issue.

**Comment by howardchung** [comment]
I think it was due to some people querying too aggressively on the table.  I've since reduced the query timeout to 10 seconds, so hopefully it shouldn't be as bad now.
