### ISSUE TITLE
Placed wards on vision tab doesn't disappears if warder abandon

### ISSUE THREAD

**Issue by ADworld-AleD** [odota/core#1603]
In this game https://www.opendota.com/matches/3720103902/vision wards placed at 7:00 min stays until match end (36:33)

**Comment by Argn0** [comment]
Did you maybe post the wrong match ID? I don't see any ward in the ward log that was placed at 7:00

**Comment by ADworld-AleD** [comment]
Sorry I was wrong about ward at 7:00.
Match ID 3720103902
Open vision tab of this match (link in first post) and drag timeline slider to the end (36:33) you can see on map 5 wards placed by Lion at 18:11, 19:17, 20:00, 20:06, 20:25
Ward log shows that these wards expired but they still on map. Now I not sure this bug in core or in web interface.

**Comment by Argn0** [comment]
This appears to be an odota/parser issue. I'm saving the replay for debugging. https://github.com/Argn0/testfiles/blob/master/3720103902_1117790356.dem.bz2

**Comment by howardchung** [comment]
As far as I can see the ward left events are just handled OnEntityLeft, I'm not sure if players abandoning causes it to behave weirdly.

https://github.com/odota/parser/blob/master/src/main/java/opendota/Parse.java#L398

@spheenik may know the answer.

We can run this replay through the parser and inspect the output to see if the events are indeed not being emitted.
