### ISSUE TITLE
add series_id to matches table

### ISSUE THREAD

**Issue by AnujDutt2701** [odota/core#1604]

**Comment by howardchung** [comment]
What is the use case for this?  Generally implementating a dedicated API endpoint is the way to go for adding functionality.

**Comment by AnujDutt2701** [comment]
#1594 

I'm attempting to group matches based on series id in order to fetch their order in a series,

**Comment by howardchung** [comment]
series ID should probably actually be in the matches table, I'm not sure why it's not there.

**Comment by AnujDutt2701** [comment]
Is there some drawback to providing read permission? Looks like it may be a lot of work to alter the tables instead.

**Comment by howardchung** [comment]
The open permissions are intended primarily for use with the data for pro matches, which is smaller and quicker to query.

**Comment by howardchung** [comment]
I did some checking on this match ID: 
3372622939

It looks like out of the 3 data endpoints:
http://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/V001 (with league_id)
http://api.steampowered.com/IDOTA2Match_570/GetMatchDetails/V001 (with match_id)
http://api.steampowered.com/IDOTA2Match_570/GetMatchHistoryBySequenceNum/V001 (with start_at_match_seq_num)

Only the first endpoint returns a series ID.  The other two do not.  Currently the ingestion code doesn't use that first endpoint, so we'd have to add a service that continually checks all the leagues with GetMatchHistory and inserts the series_id for each match.
