### ISSUE TITLE
Player page errors when they have matches without a hero

### ISSUE THREAD

**Issue by beatyt** [odota/core#1624]
Hi,

Page(s) in error:
1. https://www.opendota.com/players/111473138
2. https://www.opendota.com/players/104888934
3. https://www.opendota.com/players/169141480

For comparison:
1. https://www.dotabuff.com/players/111473138

I think that it is due to this match:  
https://www.opendota.com/matches/3748333915 
where the parsed replay claims that the player had no hero.

If I click on some of the other player's profiles from that match https://www.opendota.com/players/104888934 or https://www.opendota.com/players/169141480 then those also error.

Thanks.

**Comment by howardchung** [comment]
fixed in https://github.com/odota/web/commit/0a8dda490de78dfe64f57562871a5b5d3d3a1af0
