### ISSUE TITLE
"No hero" in hero rankings

### ISSUE THREAD

**Issue by Irevall** [odota/core#1641]
![chrome_2018-04-23_20-23-33](https://user-images.githubusercontent.com/24963770/39145623-a23a3f2e-4734-11e8-980d-5384ba442bb3.png)
Sometimes I refresh and it disappears but most of the time it's there.
[Profile](https://www.opendota.com/players/97601572/rankings) where it's happening.

**Comment by howardchung** [comment]
Looks like this happens when a game is played where a player didn't select a hero.  I'll update the code to not change player rankings in these cases and clean the database
