### ISSUE TITLE
publicMatches query ignores less_than_match_id parameter

### ISSUE THREAD

**Issue by sanson87** [odota/core#1659]
Hello,
Sorry if I'm not using it properly, but it seems that publicMatches query ignores less_than_match_id parameter and always returns the latest 100 matches. For instance this request:

https://api.opendota.com/api/publicMatches?less_than_match_id=3926606507/

Returns 100 matches ranging from 3936710403 to 3936659105 which obviously isn't compliant with my filter.

Any idea?
Thanks a lot

**Comment by howardchung** [comment]
The issue is the trailing slash on your request.

https://api.opendota.com/api/publicMatches?less_than_match_id=3926606507 works fine

**Comment by sanson87** [comment]
Ho you're right, thanks a lot for looking into it.
