### ISSUE TITLE
processExpand / expand is directly called when entry doesn't have member unit

### ISSUE THREAD

**Issue by talhasaruhan** [odota/core#1666]
As far as I understand expand function expects entry to have unit as a member
```
const slot = ('slot' in e) ? e.slot : meta.hero_to_slot[e.unit];
```
but the player_slot type events don't have units as members. (output from the java parser:)
```
{"time":26,"type":"player_slot","key":"0","value":0}
```

And they're fed straight to the expand function:

```
 player_slot(e) {
      expand(e);
    }
```

note that player_slot is called from processExpand which is fed the direct output of the java parser. I believe there are other types that also don't have unit as member but fed to this function regardless. Can someone clarify whats going on here?

Thanks

**Comment by howardchung** [comment]
Hey, so it's not necessarily required for unit to be present, the function is there so that if an entry has unit (combat log entries), it can be translated into a slot value, but if it's not there, it'll just put undefined there.
