### ISSUE TITLE
add service to run rePatch script periodically to fix match patches

### ISSUE THREAD

**Issue by howardchung** [odota/core#1674]
Due to delay in updating the patch times file the patch assigned to a match may be off.

I wrote https://github.com/odota/core/blob/master/dev/rePatch.js to fix this, however this is currently run manually.  We could move that code to a service so it runs and fixes the patch values automatically

**Comment by builder-247** [comment]
How often would be an appropriate run interval? I could work on this.

**Comment by howardchung** [comment]
Probably once a day should be fine. Backend services already restart at least once a day, so you can just use utility.invokeInterval and put a delay of one day
