### ISSUE TITLE
No recent data dumps

### ISSUE THREAD

**Issue by Magisun** [odota/core#1684]
I have a model idea that I'd like to run but it'd require more recent data than the currently available match dumps. I also haven't found a way to pull large batches of recent non-pro data from the API.

Are there any plans to release a more recent dump?

I know there's a set loaded into [BigQuery already](https://github.com/odota/core/issues/924), and streaming the data into a table was discussed with @fhoffa. Was this idea dropped?

**Comment by howardchung** [comment]
Yeah, unfortunately we don't have a newer dump than the 2016 one.  

We generally advise users to just use the regular API to get the data they need, and offer discounts on a case-by-case basis for high-volume users.

**Comment by Magisun** [comment]
So I guess the core of my problem is that there isn't a good way to pull large blocks of public match data from the API in a principled way.

`/publicMatches` says that it samples from public matches, and `/explorer` only runs queries on professional games.

Is there a recommended way to do this, or is this not something the system was meant to do?

**Comment by howardchung** [comment]
You can use the Steam API's GetMatchHistoryBySequenceNum to get basic data for all matches, then use the OpenDota API to fetch additional parsed data for them.

Depending on what fields you need, the Steam API by itself might fit your needs.
