### ISSUE TITLE
Indicate that match is part of tournament

### ISSUE THREAD

**Issue by unsafePtr** [odota/core#1702]
Currently we can only indicate that match is part of league but can't check if match is part of tournament. I think that it will be a good idea to indicate that match is part of main event.

I checked [dotabaff epicenter xl](https://www.dotabuff.com/esports/events/250-epicenter-xl-major-2018/scores?date=all&hero=alchemist) for alchemist and [odota](https://www.opendota.com/explorer?sql=select%20leagues.name%2C%20player_matches.match_id%2C%20player_matches.hero_id%20from%20player_matches%0Ainner%20join%20matches%20on%20matches.match_id%20%3D%20player_matches.match_id%0Ainner%20join%20leagues%20on%20leagues.leagueid%20%3D%20matches.leagueid%0Awhere%20matches.leagueid%20%3D%209601%20and%20player_matches.hero_id%20%3D%2073&format=). We have one match in advance. Which is of course part of league. But I want somehow to filter only by tournament played matches.

**Comment by howardchung** [comment]
You could use the date filter to filter those matches.

**Comment by howardchung** [comment]
Unfortunately I don't think there's an API that provides the start dates of the tournaments
