### ISSUE TITLE
Swagger Spec Validation Errors

### ISSUE THREAD

**Issue by saip92** [odota/core#1703]
I don't think this blocks anyone but I just wanted to point out that when using `https://api.opendota.com/api` in [Swagger Editor](https://editor.swagger.io/), it throws a bunch of schema errors in the spec.

I'm not sure if it was once a valid spec but I see that the spec was manually composed [here](https://github.com/odota/core/blob/master/routes/spec.js) and is probably just not up to date?

**Comment by howardchung** [comment]
Did the official Swagger spec change/release a new version?  I'm not sure what the correct fix is.  We do manually compose it, but it seems to work fine with the API docs: https://docs.opendota.com

**Comment by Sheemap** [comment]
@howardchung I ran into this issue today, so its still around. I'm not sure why the doc generation works, but the spec doesn't appear to have changed, OpenDota's implementation just has always been invalid lol

I've scoured the [OpenApi 2.0 docs](https://swagger.io/specification/v2/), and here are the issues that cause the errors:

- GET /constants/{resource}
    - Path parameters must be required (Currently false)
    - The responses object is required. (Currently missing)
- dateTime type
    - This type doesnt exist, and should actually be of "string" with a format of "date-time"
- GET /players/{account_id}/rankings
    - The "properties" field is misspelled as "properies"

Another note on the dateTime type, according to the spec the "date-time" format should follow [RFC3339](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14), but I've noticed a comment in the spec that describe the time sent back as `Time in seconds of last login of the player`, I assume thats an epoch timestamp, which doesnt follow that RFC return value. 

So in fixing the spec, we would need to make sure that the underlying endpoints return the correct data types we indicate to send back.

I'm happy to help work on a PR for this, and potentially implement a unit test that verifies the spec's accuracy to prevent it from happening again.

**Comment by howardchung** [comment]
Sure, a PR fixing these issues would be very welcome!

For the date maybe we can just change the type to number

**Comment by Sheemap** [comment]
Sounds good to me, Ill submit that soon!

On dateTime, Im moving through some of the fields and finding that they return it in the correct RFC format, looks like thats just how Postgres naturally returns it from the database when its stored as `timestamp with time zone`. So Ill go through and change it to that, or integer depending on what the code returns.

Another thing Im finding, is these docs are pretty incorrect in some cases. For example on `GET /rankings`, it documents many fields that just aren't returned. In addition, it marks `hero_id` as a required parameter, but functions perfectly fine if you send nothing. Likely just sending a default hero ranking.

It may be worth going through and verifying each actual model against what is documented. Though I'm not sure how to do that programmatically, and ensure it doesn't continue happening. May just forever be a maintenance thing
