### ISSUE TITLE
Using the "request" API to be able to use "replays" API to be able to parse .dem file.. ?

### ISSUE THREAD

**Issue by cbt13** [odota/core#1706]
Hello,

I'm learning to parse demo files. And I've been using the replays API with a match ID to get the "replay_salt" to get the .dem file.

That works well but I've noticed I can't use the "replays" API on some recent matches. I'm guessing it's because the match is not parsed yet?

If I manually request (from webpage) for a match to be parsed, I can get the proper answer from the "replays" API. 

But I don't quite get how I can use the API to request a match to be parsed, and I don't understand how the track the parsing process from API. (https://docs.opendota.com/#tag/request) Can I get an example of how to use it?

Is there another way for me to get the replay_salt of a match without odota parsing it first?

**Comment by RylanSchaeffer** [comment]
@cbt13 did you ever find an example of how to download the .dem file of a replay?

**Comment by cbt13** [comment]
> @cbt13 did you ever find an example of how to download the .dem file of a replay?

I did, yes, by relying on another API. But I also know there is another way to do it, I just don't know how.

I used this iirc, been a long time since I used this;

https://docs.opendota.com/#tag/replays
