### ISSUE TITLE
Expose Fantasy points data to the API

### ISSUE THREAD

**Issue by kamikazechaser** [odota/core#1717]
It would be great to see the Fantasy points data being exposed to the API (`GET /matches/{match_id} `) in the match object.

**Comment by howardchung** [comment]
The formula is just:
```
    value: 'round((0.3 * kills + (3 - 0.3 * deaths) + 0.003 * (last_hits + denies) + 0.002 * gold_per_min + towers_killed + roshans_killed + 3 * teamfight_participation + 0.5 * observers_placed + 0.5 * camps_stacked + 0.25 * rune_pickups + 4 * firstblood_claimed + 0.05 * stuns)::numeric, 1)',
```

So you can calculate it from the existing fields.  We weren't sure if Valve would tune the values.

**Comment by kamikazechaser** [comment]
Oh great! I did notice that most fields were present but I couldn't see others, until I rechecked.
