### ISSUE TITLE
Why do we count abandoned match (win) in resulting winrate?

### ISSUE THREAD

**Issue by kiddick** [odota/core#1730]
In most of cases it is false positive game for win rate. Kind of rare situation when player returned after abandoning and clearly finished game.

**Comment by kiddick** [comment]
In most of cases it is false positive game for win rate. Kind of rare situation when player returned after abandoning and clearly finished game.

**Comment by howardchung** [comment]
basically abandon doesn't affect whether the game counts or not.  If a player abandons and the team still wins, it still counts as a win.  Almost all of the time though it will count as a loss.

**Comment by kiddick** [comment]
Could we use dotabuff approach? Separate category for abandoned games so we'll hava W(in)-L(ose)-A(bandon)
And to calculate winrate = W/W+L+A

**Comment by howardchung** [comment]
I don't really like this as abandons are not really a separate category, the game result is always win or lose.

**Comment by AndreyBar** [comment]
What about games that were abandoned before the first blood? Do we count them? In such games, everyone just leaves asap and the game ends.

**Comment by howardchung** [comment]
No, the Valve web API will indicate that these games should not count
