### ISSUE TITLE
View damage dealt/received to each hero by type

### ISSUE THREAD

**Issue by mobyte0** [odota/core#1736]
I think it could be useful to put damage types (physical, magical, pure) somewhere in the combat tab. It wouldn't replace any of the current systems set in place but I think that having that data at a glance could be beneficial.

**Comment by howardchung** [comment]
I don't remember if the combat log has this data, if it does not it will have to rely on mapping ability names to damage types which may be time consuming.

**Comment by mobyte0** [comment]
I could be willing to handle mapping the types to abilities if it isn't already set. I'll take a look at how abilities are currently set up.

**Comment by mobyte0** [comment]
I just checked, damage types are already listed in the [odota/dotaconstants](https://github.com/odota/dotaconstants) under [abilities.json](https://github.com/odota/dotaconstants/blob/master/build/abilities.json).

**Comment by coreymaher** [comment]
The "problem" with relying on the dotaconstants package is it only contains the most recent patch's values. That probably doesn't really matter in the case of damage type since that rarely changes between patches, but it is something to think about if you're relying on values that change between patches.

**Comment by howardchung** [comment]
Yeah, that might be a concern.

Looks like we could compute this client side though since we already have the damage dealt/received split by ability.

**Comment by mobyte0** [comment]
Perhaps this could be closed and just reopened under [odota/web](https://github.com/odota/core)? Going to do that for now since it makes more sense that way. Feel free to reopen if you'd like to implement it into the core system.
