### ISSUE TITLE
failed to using request GET ../peers

### ISSUE THREAD

**Issue by paveligorevich55** [odota/core#1755]
**Explain your question as detailed as possible**

I need help with ajax request to my ../peers (api)
I have only on this request CORS block. But i can see in console log all data. What is that problem? Why i cant use this data for my stats??
---
`Failed to load http://api.opendota.com/api/players/131389547/peers?api_key=706700BD62A6A2A65A14C30E3D1A7260: Redirect from 'http://api.opendota.com/api/players/131389547/peers?api_key=706700BD62A6A2A65A14C30E3D1A7260' to 'https://api.opendota.com/api/players/131389547/peers?api_key=706700BD62A6A2A65A14C30E3D1A7260' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access.`

If you have a support request or question please also check our Discord Server: https://discord.gg/opendota

**Comment by howardchung** [comment]
I think you just have to use https
