### ISSUE TITLE
Graph popups are not sorted by value in descending order

### ISSUE THREAD

**Issue by jagmeetb** [odota/core#1756]
In the Graphs page of a match, hovering over a graph will create a popup that shows the values for each player's XP/Gold/last-hits. They should be sorted in descending value of the relevant metric, but instead are sorted by player (blue>teal>purple...>brown)

example pic: 
![image](https://user-images.githubusercontent.com/16247626/46846338-686fe500-cdad-11e8-9c99-8567c58319fb.png)

Templar Assassin (olive) should be at the top of the list and Grimstroke (purple) should be last. It used to work correctly a while ago but recently became broken.

**Comment by jagmeetb** [comment]
Also, I am starting to contribute to open-source and I would to tackle this issue myself if possible.

**Comment by gu3st** [comment]
Issue filed in web. Closing as dupe
