### ISSUE TITLE
raw damage taken and reduce ratio

### ISSUE THREAD

**Issue by dota2heqiuzhi** [odota/core#1776]
![image](https://user-images.githubusercontent.com/36252196/47603287-ba0aa780-da1c-11e8-91ef-cf44c7744e1b.png)
@howardchung How can I get raw damage taken and reduce ratio in OpenDota ?

**Comment by dota2heqiuzhi** [comment]
@howardchung ：）

**Comment by coreymaher** [comment]
Much of the extra data from the post game screen is available in the metadata file which opendota does not currently parse. You should be able to parse it yourself with clarity: https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/metadata/Main.java

Also, you may have more luck asking questions in discord.

**Comment by howardchung** [comment]
I don't believe the damage reduction numbers are in the replay file

**Comment by dota2heqiuzhi** [comment]
@Crazy-Duck
