### ISSUE TITLE
Seems like using both params for /feed takes too long to process

### ISSUE THREAD

**Issue by MrYadro** [odota/core#1804]
`leagueid=10296&seq_num=3006926634`

API returning Bad Gateway, seem like it's timeout for request.

**Comment by howardchung** [comment]
What client are you using to connect?

**Comment by MrYadro** [comment]
Via browser and via curl, either way it takes very long to load or won't load at all.

And it's cloudflare error, not yours.

![image](https://user-images.githubusercontent.com/1587606/48830616-0c25bb00-ed86-11e8-8d70-4e794ec8240c.png)

**Comment by howardchung** [comment]
I think one of the layers in between, either cloudflare or google load balancer is timing out if no bytes are sent after a minute. The solution is probably to send "keepalive" newline characters every 15 seconds or something

**Comment by howardchung** [comment]
I added this in https://github.com/odota/core/commit/d201a61aab9a5b74c9e6cef4ef2b9888720a2fed
