### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by Mastik14** [odota/core#1806]
a lot of NULL params on https://api.opendota.com/api/matches/4230819740
may be on 1st try parse, replay(dem file) is not available, but now replay file is available and data remain NULL, after some calls

**Comment by howardchung** [comment]
This might have been a transient error, the match appears to be parsed now.

**Comment by Mastik14** [comment]
Same situation happens also by another id's, new id's for exemple 
https://ru.dotabuff.com/esports/series/1494566-kg-vs-serenity

**Comment by howardchung** [comment]
There was an issue fetching replay salts last week that should be resolved now. These replays now appear to be parsed
