### ISSUE TITLE
Games with no party size assigned

### ISSUE THREAD

**Issue by evilmtv** [odota/core#1808]
Not sure if this is a bug or the information is missing from valve's side.

**Comment by evilmtv** [comment]
For example:
![image](https://user-images.githubusercontent.com/19277738/49046170-2f30ee80-f20e-11e8-8776-c6cdbe772774.png)
It makes it hard to filter out stats for my solo/party matches

**Comment by coreymaher** [comment]
@evilmtv Are those unparsed matches? The solo/party information is only available for parsed matches.
