### ISSUE TITLE
Matches not being parsed automatically

### ISSUE THREAD

**Issue by Xarano-GIT** [odota/core#1824]
![image](https://user-images.githubusercontent.com/45671929/49610920-d2fd6580-f997-11e8-8389-3ac266c97774.png)

Even though I've logged in recently, my matches in the last couple of days aren't being parsed automatically.

I've had to manually do them.

https://www.opendota.com/players/94826473

**Comment by howardchung** [comment]
There's been an issue fetching replay salts for the last few days and we're still catching up.
