### ISSUE TITLE
Make recentMatches and matches return the same result?

### ISSUE THREAD

**Issue by Tsury** [odota/core#1843]
Currently `/recentMatches` and `/matches` are almost the same. Is it possible to make them return the same JSON structure? Is there any reason for why they're different in the first place? They both return matches afterall.
Specifically I would like lane info to also appear in `/matches/` and not only in `/recentMatches`.

**Comment by howardchung** [comment]
I guess these endpoints could have been combined. The original goal was to make an endpoint that always returned a maximum of 20 matches and did not support any filtering for performance reasons.

If you're looking to make matches return any field though, you can use the `project` query param to specify that field (i believe this is in the docs)

**Comment by Tsury** [comment]
I see, thanks. Does it say anywhere which fields are possible to project? And what is the syntax to project multiple fields?

**Comment by howardchung** [comment]
You can project fields that appear in: https://github.com/odota/core/blob/master/sql/create_tables.cql#L124

**Comment by Tsury** [comment]
Thanks, this helps a lot.
I wasn't able to find this in the docs, maybe you should consider adding it (or, if it's already there and I'm missing it - make it easier to find)
