### ISSUE TITLE
Query Problem!  When we select  team and making selection of won against mega creeps 

### ISSUE THREAD

**Issue by SohaibAnwaar** [odota/core#1845]
Hey their Hope you are in good health. I am going through some problem when I select some team and want to see they win against mega creeps or not.
![See this I select Team and according to the option only want to see wins against mega creeps](https://user-images.githubusercontent.com/29427728/52341103-8388f380-2a33-11e9-8807-9213c31d0f9c.PNG)  but its showing me their losses to see the results.
![capture](https://user-images.githubusercontent.com/29427728/52341299-0611b300-2a34-11e9-96fb-cf2909581c80.PNG) 
    .  It might be a label error and you should add label of e.g(Stats against mega-creeps) [yes/No] etc like this.  and awesome work guys I really like your work and I will keep testing your website because working for dota 2 is my dream, stay blessed.

**Comment by howardchung** [comment]
Did you try adding the Result = win filter?

**Comment by Argn0** [comment]
maybe "Won against mega creeps" should be renamed to "mega creep comeback". might be more accurate.

**Comment by howardchung** [comment]
Yeah, I agree

**Comment by howardchung** [comment]
@Argn0 are you interested in making this change?  Should just be a string update on web
