### ISSUE TITLE
How to retrieve list of matches that are 1) pub matches and 2) parsed

### ISSUE THREAD

**Issue by dk-forestry** [odota/core#1847]
I would like to do some analyses on match data using machine learning algorithms. This should be based on matches that have the following characteristics:

- only pub matches (i.e. no pro matches, no matches from leagues)
- only parsed matches (to be able to use for example gold and xp values for each player over the course of a match)

How can I find and download such matches using the API?

I (unsuccessfully) tried the following approach:

1. Use a query to retrieve a list of parsed pub-matches
2. Download detailed match data for a sample of that list 

Using the API, 2) seems to be easy. 
However, I couldn't achieve 1), probably because I don't fully understand the db scheme of the project. I tried to use the tables `player_matches`, `matches` and `public_matches`.  

This seems to return only parsed matches (good!), but only in leagues (bad):

```
select matches.match_id, matches.leagueid
from matches
where version > 0
limit 100
```

Is it correct that `matches` _only_ contains league matches? And in consequence, `player_matches` also only contains league matches?

`public_matches` seems to contain some matches that are _not_ from a league, but parsed (for example, match id 3925110408). Player-level gold charts over time are shown here: https://www.opendota.com/matches/3925110408/graphs 

However, these queries return empty results: 

```
select * 
from match_logs 
where match_id = 3925110408
```

```
select * 
from player_matches
where match_id = 3925110408
```

Where do the data for the player-level gold charts over time come from?

Thanks in advance for any help! :)

**Comment by coreymaher** [comment]
You can use GET /publicMatches ( https://docs.opendota.com/#tag/public-matches ) to get a sample of recent public matches. The explorer will only return matches in a league like you noticed.

If you want to get more data about a specific match you'll need to use the GET /matches/{match_id} endpoint ( https://docs.opendota.com/#tag/matches%2Fpaths%2F~1matches~1%7Bmatch_id%7D%2Fget )

**Comment by dk-forestry** [comment]
> You can use GET /publicMatches ( https://docs.opendota.com/#tag/public-matches ) to get a sample of recent public matches.

I was aiming to use data from at least 20.000 matches or so. GET /publicMatches doesn't really help much, because it only returns 100 matches. 

Do you know if these 100 matches are parsed? 

> The explorer will only return matches in a league like you noticed.

Is this really the case?

```
SELECT COUNT(match_id)
FROM public_matches
```
returns 41.324.737 matches. Are these all league matches?

> If you want to get more data about a specific match you'll need to use the GET /matches/{match_id} endpoint ( https://docs.opendota.com/#tag/matches%2Fpaths%2F~1matches~1%7Bmatch_id%7D%2Fget )

Yes, my initial idea was to use GET /matches/{match_id} for every match from a list of 20.000 matches that are 1) parsed and 2) not from a league. However, I don't know how to create that list. 

A possible workaround might be to create a large list of public matches (let's say 100.000), without knowing which matches on this list are parsed and which are not. I could than download data for each of these matches using GET /matches/{match_id}. After downloading all data for the 100.000, I could detect and remove unparsed matches. However, this seems very inefficient; I would very much prefer to only download data for matches that have been parsed.

**Comment by howardchung** [comment]
You are correct, public_matches is an approximately 15% sample of all matches. There is no parsed data on these rows, so you'll have to take the approach you described where you get a sample and then check for parsed matches. Alternatively, you could sample and then request parses through the API for your sample if the matches aren't too old.

**Comment by dk-forestry** [comment]
@howardchung, Thanks for this info! I'll look into the two alternatives. :)

**Comment by dota2heqiuzhi** [comment]
> You are correct, public_matches is an approximately 15% sample of all matches. There is no parsed data on these rows, so you'll have to take the approach you described where you get a sample and then check for parsed matches. Alternatively, you could sample and then request parses through the API for your sample if the matches aren't too old.

public_matches is a true random sample ?

**Comment by howardchung** [comment]
No, it's not. We pick from matches that have at least 3 players with rank data.

**Comment by dota2heqiuzhi** [comment]
> No, it's not. We pick from matches that have at least 3 players with rank data.

You mean num_rank_tier >= 3? But I find some matches in public_matches which num_rank_tier is 2.
How can I get true random sampling from OpenDota api? 
Most new players don't have rank, If it is random sampling, we can do a lot of interesting analysis.

**Comment by dota2heqiuzhi** [comment]
@howardchung

**Comment by howardchung** [comment]
You can try fetching the raw match IDs from the Steam WebAPI and then making OpenDota request for a sample of those IDs.
