### ISSUE TITLE
Is there an API endpoint to fetch current (live) game for a player?

### ISSUE THREAD

**Issue by spaghetti-** [odota/core#1860]
The information is available to the client so I was wondering if there is a way to parse this information?

**Comment by howardchung** [comment]
IIRC you have to be friends with that player to see what game they're in

**Comment by spaghetti-** [comment]
What about my own games? I couldn't find an API that was relevant to fetching live games.

**Comment by howardchung** [comment]
You might be able to do so by reading client files like server_log.txt, but OpenDota will not be able to access these files
