### ISSUE TITLE
Possible to add with or against on WL endpoint as query param?

### ISSUE THREAD

**Issue by zocheyado** [odota/core#1867]
https://docs.opendota.com/#tag/players%2Fpaths%2F~1players~1%7Baccount_id%7D~1wl%2Fget
On the WL command it is possible to get your WL with another player by using that query and the included_account_id command. Between those two things I can find out my record with Player A and B.  However it is impossible to determine if the player was on my team or the enemy team. So I might get back 10-15 as Win Loss. But it could be 7 wins as a teammate, and 3 wins as an enemy in which I won.

I propose adding a "teammate" flag that is true, false or null. Null keeps it as is, true would return the win loss as a teammate and false would return win loss as an enemy. The alternative to this is grabbing.....let's just say well over an order of magnitude worth of API calls to get the actual match histories and compare the teams. 

Edit* Furthermore it is even confusing on the opendota website itself, as you can see here it says "My Record With" https://puu.sh/CRhTW/6849ec75c0.png In which you would assume based on that I have won 3 times that I have played with this person and lost once. But really if you click on that it shows I have lost with him once, and beat him 3 times. Which has a very different meaning.

**Comment by howardchung** [comment]
I think we can achieve this by implementing with_account_id/against_account_id filters here:
https://github.com/odota/core/blob/master/util/filter.js#L41
