### ISSUE TITLE
Convert Replay to Player Perspective Video?

### ISSUE THREAD

**Issue by RylanSchaeffer** [odota/core#1902]
Is there a way to convert a replay (.dem.bz3) file into a video (e.g. .mp4, .mov) from a single player's perspective? If not, does anyone have any recommendations for how to do this?

**Comment by howardchung** [comment]
You can do so by running it on a VM with a GPU and capturing the output. It's quite expensive to do at scale though.

**Comment by RylanSchaeffer** [comment]
What tools exist to automate such a process? Is there an API to control the DotA client to sequentially open replays, select a specified player's perspective, etc.?

**Comment by howardchung** [comment]
Unfortunately I don't have details since I've never done this before. You might be able to do some actions via console commands.
