### ISSUE TITLE
Games with corrupted data

### ISSUE THREAD

**Issue by TheOriginalSoni** [odota/core#1903]
I found more than a few games which had incorrect data. barracks_status_dire and barracks_status_radiant are 0, but when you look at the log, it's obvious that it's not true.

In this example, both sides are supposed to have lost all buildings (Opendota building map also shows same), but logs do not record any radiant buildings being destroyed at all.

Other matches with this issue happened around the same time

https://www.opendota.com/matches/4216982567/log

**Comment by howardchung** [comment]
Unfortunately this is due to a Steam API bug that has since been fixed. The log information is correct, the barracks_status fields are not.
