### ISSUE TITLE
store parsed matches in ParseHistory table

### ISSUE THREAD

**Issue by howardchung** [odota/core#1907]
A common request is to get IDs of only matches that are parsed. Currently we don't index those, but we can create a new table and store the IDs there.

**Comment by dota2heqiuzhi** [comment]
> A common request is to get IDs of only matches that are parsed. Currently we don't index those, but we can create a new table and store the IDs there.

@howardchung Is it done？

**Comment by howardchung** [comment]
Not yet. public_player_matches is a sample, so we'd probably want a new table.

**Comment by dota2heqiuzhi** [comment]
Is there a schedule? This is very useful！

Howard Chung <notifications@github.com> 于2019年12月10日周二 下午2:47写道：

**Comment by howardchung** [comment]
I don't have a set target date on this feature, but happy to accept a PR for it.

**Comment by dota2heqiuzhi** [comment]
My English is not very good，so is my python.
I don't know if I can do it well

Howard Chung <notifications@github.com> 于2019年12月12日周四 上午8:03写道：

**Comment by ahi-el** [comment]
hi @howardchung, just to make sure 

what columns should the table include? only matchId? do we want to return -all- the parsed matchesIds whenever the api is called?

**Comment by howardchung** [comment]
Yes, I think matchID is sufficient.

To restrict the response size, we should probably limit to 100 per call, but allow paging back with less_than_match_id
