### ISSUE TITLE
Api endpoints for records

### ISSUE THREAD

**Issue by Stelian** [odota/core#1913]
Hi there, I was wondering if there is any api endpoint that gives the info under the records page? I browsed around the documentation but I could not find it / missed it.

**Comment by builder-247** [comment]
You mean this?
https://docs.opendota.com/#tag/records

**Comment by Stelian** [comment]
hi @builder-247 nope, I meant player records (like best APM) but I figured it out that they are extracted from the matches, e.g. matches?sort=tower_kills&limit=20
