### ISSUE TITLE
SQL explorer, only contains little subset of all played matches

### ISSUE THREAD

**Issue by heyt0ny** [odota/core#1945]
Hello, 

I need all match_ids for one day. I do the below request with `start_date = begin of the day` and `end_date = begin of next day`. This returns ~100k matches per day (+-).
```python
api_url = "https://api.opendota.com/api/explorer"
parameters = {'sql': f'''SELECT match_id, start_time FROM public_matches
                                      WHERE start_time >= {start_date}
                                      AND start_time < {end_date}'''}
```

But seems like in reality the number of matches played in a day is much biggger - so a lot of matches are not present in the response (however these matches are present in match_details)

For example let's take public `matchid=4915260776`. The `start_time` of this match is `1563663852`. But if I make the request with 

```sql
SELECT match_id, start_time FROM public_matches
WHERE start_time >= 1563663800
AND start_time < 1563663900
```
It won't return this match. And there are tons of such examples. Is it intended to be so? If so, is there way to get all matches from the day? 

Thanks

**Comment by howardchung** [comment]
The Explorer is intended for batch analytics and only includes a sample of all the matches played. This is done to prevent the SQL database from growing too rapidly.

**Comment by heyt0ny** [comment]
Ok, is there way to get all match ids?

**Comment by howardchung** [comment]
You can try the Valve endpoint GetMatchHistoryBySequenceNum

**Comment by mvrozanti** [comment]
While the Explorer only contains a few matches, does the rest of the API provide the full history?

**Comment by howardchung** [comment]
Yes, you can access any public match through the /api/matches endpoint

**Comment by mvrozanti** [comment]
Can you make equally rich questions to the API as can be done with the Explorer as well?

**Comment by howardchung** [comment]
You can get the same data per match, but there are more limited querying options to get lists of matches.

**Comment by mvrozanti** [comment]
Nice alright thanks!

**Comment by aleksandr1592** [comment]
Hello, I have pretty much the same issue, 
I have a parsed match which is perfectly viewable via web [interface.](https://www.opendota.com/matches/2521500094). So it does seem for me that this match supposed to be accesseble via query.
But I can't view any database records about this match. Same goes for most matches for my account (non-professional, low ranked). I'm not sure (and I have no proof for this), but it seemed for me, I was able to access them via queries before . 
Did anything changed?
Does it even matter if match is parced or not?
Is there is still a way to retrieve data for non-parced particular matches using opendota api?

My query for beforementioned match (does not work for me):
select * from public_matches  -- or matches
limit 10

**Comment by howardchung** [comment]
The reason is that full data for only pro matches is stored in SQL because it's not as fast but allows more query flexibility.

The regular matches are stored in Cassandra which can't be queried the same way. So unfortunately you can't access the data in explorer for most matches, except for through the /matches endpoint by match ID.
