### ISSUE TITLE
API health check page

### ISSUE THREAD

**Issue by Samuron** [odota/core#1964]
Hi! 
It seems that the API is currently down due to timeouts, so I've checked the twitter and blog and they seem to be not very active. 
Is there any endpoint with API status or health check status to monitor in such cases?

**Comment by howardchung** [comment]
Sorry about that, was performing some database maintenance. We usually answer questions on our Discord https://discord.gg/opendota

**Comment by howardchung** [comment]
There's also http://status.opendota.com/ which is somewhat automated
