### ISSUE TITLE
Request parse not working

### ISSUE THREAD

**Issue by shojimeguro** [odota/core#1991]
if you choose parse, circle loop endlessly and been waiting for whole hour without any result

https://www.opendota.com/request#5093546587
https://www.opendota.com/request#4547728509

and many more, i have around 15 replays need to be parsed and quite dissapointed that none of them works.

tested on 3-4 browsers including chrome, firefox, opera, vivaldi and no luck so far

**Comment by howardchung** [comment]
4547728509 is too old and the replay is no longer available.

5093546587 is now parsed.
