### ISSUE TITLE
Explorer does not show ranked matches of lobby_type = 7 (Ranked)

### ISSUE THREAD

**Issue by Jdash99** [odota/core#1996]
I'm trying to use the API Explorer to query only the games that are ranked with this:

```
SELECT
matches.match_id
FROM matches
WHERE matches.lobby_type = 7
LIMIT 100
```

But it does not show results, only lobby type 1 and 2.

**Comment by howardchung** [comment]
This table only includes pro matches, which are usually lobby captains mode.
