### ISSUE TITLE
API rate limit does not match docs

### ISSUE THREAD

**Issue by liampwll** [odota/core#2000]
https://www.opendota.com/api-keys states that api calls with a key allow 1200 calls per minute but only 300 are actually allowed.

https://github.com/odota/core/blob/20dc1acbe329a978ffd96ae8e225b8f5684c3f5c/config.js#L69

**Comment by howardchung** [comment]
We override the default value in the production deployment. We could change it here for consistency, but it's not required.

**Comment by liampwll** [comment]
I am getting 429s when I try to send slightly more than 300 per minute.

**Comment by howardchung** [comment]
What endpoint are you using?

**Comment by liampwll** [comment]
I was getting this with `/match`, but I seem to be unable to reproduce it.
