### ISSUE TITLE
Broken matches

### ISSUE THREAD

**Issue by liampwll** [odota/core#2001]
dire_team_id is null but dire_team exists and has an ID: https://api.opendota.com/api/matches/3613699810

replay_url and replay_salt are missing even though the game has obviously been parsed: https://api.opendota.com/api/matches/3444249178

10 players on one team: https://www.opendota.com/matches/4499511023

I'm not sure if any of these are issues with Skadi rather than OpenDota.

**Comment by howardchung** [comment]
IIRC dire_team_id was not backfilled so older matches might not have it. It shouldn't be a problem if dire_team/radiant_team exist.
