### ISSUE TITLE
Dota 2 CDN icon links for snapfire and void spirit are missing

### ISSUE THREAD

**Issue by Crazy-Duck** [odota/core#2007]
The following two links currently return a 404:
http://cdn.dota2.com/apps/dota2/images/heroes/void_spirit_icon.png
http://cdn.dota2.com/apps/dota2/images/heroes/snapfire_icon.png

The corresponding _lg/_sb/_full links resolve correctly, it seems like it's just the hero icons that are missing

**Comment by howardchung** [comment]
Leaving this issue open to track this, but I'm going to patch by dropping the icons into the odota/web repo.

**Comment by Prochy20** [comment]
It seems that those icon are still missing...

**Comment by howardchung** [comment]
Yeah, not available on https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/void_spirit_icon.png either

**Comment by Prochy20** [comment]
BUMP

**Comment by Prochy20** [comment]
Today I have accidentally found that full images are available:

https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/void_spirit_full.png
https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/hoodwink_full.png

But icons are still not, for some reason...

**Comment by howardchung** [comment]
This seems to be fixed now
