### ISSUE TITLE
Team rating

### ISSUE THREAD

**Issue by heyt0ny** [odota/core#2009]
Hello!

I try to get team rating though your API `https://api.opendota.com/api/teams/5`.

1) I was wondering how do you calculate ''rating" filed?
2) Are all the games of a team are counted? Because in dotabuff and stratz there are in total almost 2k games for this team (https://www.dotabuff.com/esports/teams/5). And in opendota there are like 1.6k.

Thanks!

**Comment by howardchung** [comment]
Rating is calculated using the standard Elo formula, with all teams starting at 1000 and a k-value of 32. We apply the formula using all the games between teams.

I believe some matches are excluded in OpenDota because we don't count games played in TI open qualifiers or amateur leagues.
