### ISSUE TITLE
Get latest matches of a player by id, up to a specific match_id

### ISSUE THREAD

**Issue by RollyPeres** [odota/core#2025]
Hi,

Is there a way of getting latest played matches of a player up to a specific match_id ? Something like `end_at_match_id` ?

**Comment by howardchung** [comment]
I don't believe so, but you can just fetch all of them and then filter on the client side.

**Comment by RollyPeres** [comment]
@howardchung Well ye, but was wondering if there's some new api allowing for a cleaner solution.
