### ISSUE TITLE
store net_worth data from GC for each player

### ISSUE THREAD

**Issue by howardchung** [odota/core#2119]

**Comment by arcanysnicomac** [comment]
Hi, do we have any updates or an ETA for this?

**Comment by howardchung** [comment]
I've been kind of busy, sorry about the delay. The work itself isn't too hard, it's just adding a column to the CQL/SQL schema and updating getGcData to insert the net_worth field for each player.

**Comment by builder-247** [comment]
I could take a look at this.

**Comment by howardchung** [comment]
Finally got to this! Data should be available in the next day or so. It should also be fairly easy to add a new column to the match table if we want to display it in the UI
