### ISSUE TITLE
Send api_key in header

### ISSUE THREAD

**Issue by Samuron** [odota/core#2128]
Hi, guys!

I think it would be really convenient to send api_key in some kind of header and not only in query parameter. Is it possible as documentation does not mention such possibility?

**Comment by howardchung** [comment]
Currently it is not, although we could add support for the Authorization HTTP header.

Is there a technical reason you'd like to do this?

**Comment by Samuron** [comment]
Today I've been investigating large production issue and it turned out I've made mistake in adding api_key to other query parameters in one of the calls. As a result api_key was not detected by opendota and it led to rate limiting and feature degradation in our application. I thought that header will make it more foolproof. And the other concern is accidently sending sensitive information to http endpoint instead of https.
