### ISSUE TITLE
allMmr.js is a valid js module or not?

### ISSUE THREAD

**Issue by wqbill** [odota/core#2182]
I didn't saw other js requires allMmr.js.
Function generateJob doesn't have 'mmr' type in options.
Just wonder is this used somewhere?

**Comment by howardchung** [comment]
Files in `dev` are one-off scripts and not run regularly. I keep them around in case they might come in useful in the future.

**Comment by wqbill** [comment]
Thank you for responding so quickly.I'll close this.
