### ISSUE TITLE
Add image_path to the Hero object

### ISSUE THREAD

**Issue by jezer07** [odota/core#2191]
Hi,

Is it possible to put the image path of the hero on the `Heroes/` API?

```
[
  {
    "id": 0,
    "name": "string",
    "localized_name": "string",
    "primary_attr": "string",
    "attack_type": "string",
    “image_path: “string”, // add this
    "roles": [
      "string"
    ]
  }
]
```

Or is there an alternative way on how to easily get the image of any given hero?

Thanks

**Comment by howardchung** [comment]
https://github.com/odota/dotaconstants/blob/master/build/heroes.json has the image paths.

You can use the hostname http://steamcdn-a.akamaihd.net/

**Comment by jezer07** [comment]
@howardchung cool thanks! That's exactly what I'm looking for.
