### ISSUE TITLE
Combos feature not working

### ISSUE THREAD

**Issue by minu-aswanth** [odota/core#2196]
I'm assuming this is because the hero_search table isn't being updated?

**Comment by howardchung** [comment]
If you're looking for the daily community prediction, Valve has disabled that match's data from showing up in the API until after the prediction is over.

Otherwise, you might just be getting back older matches since the API doesn't return results in order.

**Comment by minu-aswanth** [comment]
Ah, got it. But none of the previous community prediction matches don't seem to be showing up either.

**Comment by howardchung** [comment]
That's because we don't backfill the data afterward (although if you request a parse for the match ID, we can get the regular match data afterward)

**Comment by minu-aswanth** [comment]
Thanks, understood. Closing this issue.
