### ISSUE TITLE
Data Explorer SQL getting team names 

### ISSUE THREAD

**Issue by tarasevich-dmitry** [odota/core#2227]
Hello,

I'am trying to get pro matches results using Data Explorer with SQL, but for some reason team names from `matches` table are null's. Am I doing something wrong or is it a bug? 

Here is my SQL code: 
```
SELECT
        
matches.match_id,
(matches.radiant_win) win,
matches.radiant_team_id,
matches.radiant_team_name,
matches.dire_team_id,
matches.dire_team_name
FROM matches
WHERE TRUE
AND matches.start_time >= extract(epoch from timestamp '2019-12-31T22:00:00.000Z')
LIMIT 50
```

The result I get:
![Screenshot from 2020-08-31 20-21-43](https://user-images.githubusercontent.com/26335004/91761382-72877080-ebdd-11ea-9ae7-74e6d902f4d1.png)

Thanks in advance

**Comment by howardchung** [comment]
You can try joining with the team table to get the names. I don't think they're stored in the matches table, as team names sometimes change.

**Comment by tarasevich-dmitry** [comment]
Ok, thanks for explanations!
