### ISSUE TITLE
game_mode, hero_id, player_slot and lobby_type coding documentation

### ISSUE THREAD

**Issue by argv1** [odota/core#2229]
Hi Folks,
I just creates a small script to fetch my matches via the API and would like to resolve the hero_ids, game_mode, lobby_type, etc.
So that game_mode 5 resolves in "All Random" and  hero_id 10 becomes  morph.
Could not find anything in the documentation.

**Comment by howardchung** [comment]
Refer to https://github.com/odota/dotaconstants
