### ISSUE TITLE
Different result in different end points

### ISSUE THREAD

**Issue by e1ektr0** [odota/core#2261]
https://api.opendota.com/api/matches/5670826238
return the match, but
https://api.opendota.com/api/explorer?sql=select * FROM public_matches where match_id=5670826238 LIMIT 1

what im doing wrong? and how to get history of matches

**Comment by howardchung** [comment]
Explorer is only for pro matches

**Comment by e1ektr0** [comment]
> Explorer is only for pro matches

sad, thx for unswer, do you know how get full match histroy.

when i use get matches by seq in stam api, it have not all matches to, get histroy return last 500 or im doing some thing wrong.
