### ISSUE TITLE
Mapping of Steam account_id from steam_id

### ISSUE THREAD

**Issue by 9tailStudios** [odota/core#2263]
Since Steam web api only provides steam_id(17 digit Id).  There is no way to get the account_id.
All the opendota api requires steam account_id to be passed and not the steam_id.
Is there any workaround for this, or any api which maps steam_id to account_id.

**Comment by howardchung** [comment]
Look for the function convert64to32:
https://github.com/odota/core/blob/e34261b36b00175e94d022f7952472d5a433b6ff/util/utility.js#L32

**Comment by 9tailStudios** [comment]
@howardchung, Thanks a lot!
