### ISSUE TITLE
Issuing parse request (POST) does not really parse the match

### ISSUE THREAD

**Issue by hanktrizz** [odota/core#2275]
Hi there!

I've tried to parse a particular match via the POST API endpoint (/request/{match_id}) and it issues a job id in response, which is great. But when I query the GET endpoint to see the status of the parse (/request/{jobId}), it always returns a `null`.

Thinking that a `null` maybe meant the job has finished I headed over to the Open Dota site to view the match but it's still not parsed so I'm quite certain the request didn't get processed. 

Can someone please help? Many thanks.

**Comment by howardchung** [comment]
What is the ID of the match you are trying to parse? One possible reason is that the match is too old (we could probably do a better job of surfacing parse errors in the job)

**Comment by hanktrizz** [comment]
@howardchung The match ID is 5471343934. It's 4 months old and I picked it at random to parse. Is there a set threshold in which after it gets a few months old, it is no longer parse-able?

**Comment by howardchung** [comment]
Yes, it's generally only 10 days of replay retention

**Comment by hanktrizz** [comment]
Well, I guess that clears it up - you can close this. Thank You! However, I do agree that a more meaningful response to these two particular endpoints would be great.
