### ISSUE TITLE
Swagger api spec issue - purchase log key data type

### ISSUE THREAD

**Issue by Schoolboy215** [odota/core#2300]
**Issue with routes/spec.js** (line 625? Permalink below)
https://github.com/odota/core/blob/bcb1b4808fe6d5bf2675d89c01b3428ea2aa1c04/routes/spec.js#L625

Swagger spec says that the data type for the key on a purchase_log element is "integer", but responses coming back from a match query seem to be strings. Causes error on deserialization.

Sample response:
`'purchase_log': [{'charges': None,
                                'key': 'orb_of_venom',
                                'time': -89},`

**Comment by howardchung** [comment]
Yeah I think that's a typo. Feel free to submit a PR to fix?

**Comment by Schoolboy215** [comment]
Can do! Thanks for the quick response.
