### ISSUE TITLE
Matches API return the same hero in the pick list and the ban list

### ISSUE THREAD

**Issue by gerynugrh** [odota/core#2305]
`https://api.opendota.com/api/matches/5784873432?`

When opening one of my match, I found a strange case in the UI where arc warden is both picked and banned, after further investigation it seems this originates from the API response.

```js
"picks_bans":[{"is_pick":true,"hero_id":85,"team":1,"order":0},{"is_pick":true,"hero_id":27,"team":1,"order":1},{"is_pick":true,"hero_id":98,"team":0,"order":2},{"is_pick":true,"hero_id":25,"team":0,"order":3},{"is_pick":true,"hero_id":83,"team":0,"order":4},{"is_pick":true,"hero_id":16,"team":1,"order":5},{"is_pick":true,"hero_id":44,"team":0,"order":6},{"is_pick":true,"hero_id":70,"team":1,"order":7},{"is_pick":true,"hero_id":113,"team":1,"order":8},{"is_pick":true,"hero_id":106,"team":0,"order":9},{"is_pick":false,"hero_id":113,"team":0,"order":10},{"is_pick":false,"hero_id":1,"team":0,"order":11},{"is_pick":false,"hero_id":22,"team":0,"order":12},{"is_pick":false,"hero_id":44,"team":0,"order":13}]
```

**Comment by howardchung** [comment]
I'm not sure what's going on here, this matches the data from the Valve endpoint. Maybe it's reporting all attempted bans, even if not 100% of those selections actually get banned?

**Comment by gerywahyunugraha** [comment]
Let me verify this by downloading the replay and parse it manually, if that's the case then it should be non issue for open dota and this issue can be closed
