### ISSUE TITLE
Dawnbreaker img tag on /heroStats not working

### ISSUE THREAD

**Issue by malcolndandaro** [odota/core#2331]
Hello,   
currently [/heroStats](https://api.opendota.com/api/heroStats) returns the `"img":"/apps/dota2/images/heroes/dawnbreaker_full.png?` which is not working for Dawnbreaker.
The working path from opendota match page is:  `/apps/dota2/images/dota_react/heroes/dawnbreaker.png`

**Comment by howardchung** [comment]
we probably need to update dotaconstants to use the new path. However that also means losing the multiple sizes that the old path has
