### ISSUE TITLE
Ability Draft matches from after April 19 2021 are not parsing

### ISSUE THREAD

**Issue by personjerry** [odota/core#2335]
Looks like there was some change in the replay data. Successfully requested parse of this replay https://www.opendota.com/matches/5953621203 from April 19 today (April 25), but newer replays like https://www.opendota.com/matches/5955137492 or https://www.opendota.com/matches/5963530066 aren't parsing.

**Comment by builder-247** [comment]
I don't think this is an issue with the parser - for some matches the replay just never becomes available.

**Comment by howardchung** [comment]
I think I forgot to download the replay from the linked match and it's now expired. Can we get a newer example?

**Comment by personjerry** [comment]
Looks like since May it is no longer an issue. I cannot reproduce the bug at this time.
