### ISSUE TITLE
Wrong format in docs in GET /players/{account_id}/rankings

### ISSUE THREAD

**Issue by angary** [odota/core#2409]
The documentation [here](https://docs.opendota.com/#tag/players%2Fpaths%2F~1players~1%7Baccount_id%7D~1rankings%2Fget) says that `GET /players/{account_id}/rankings` returns 

```
[
  {
    "hero_id": "string",
    "rank": 0,
    "card": 0
  }
]
```

but it returns

```
[
  {
    "hero_id": "string",
    "score": 0,
    "percent_rank": 0,
    "card": 0
  }
]
```

**Comment by howardchung** [comment]
I think we just have to update the spec.js file
