### ISSUE TITLE
A way to get hero names via "hero_id"

### ISSUE THREAD

**Issue by JakeJackson99** [odota/core#2427]
When getting data on heroes, it would be nice to get data on a single hero in order to retrieve the name of the hero.

This comes from a need to get hero names when gathering data on a user's data via *"/players/{account_id}/heroes"* and not having the heroes' names included in the returned data. Thus, I turn to fetching data on heroes via *"/heroes"* as it includes the hero names, but it returns all the heroes, and it doesn't give the option to retrieve data on a single hero/set of heroes.

Or maybe there is actually an easy way to doing what I am trying to do and I just don't know it, so feel free to let me know  (I am new to the API).

**Comment by howardchung** [comment]
There are only ~100 heroes--you should probably just cache that list somewhere and do a lookup against it?

**Comment by JakeJackson99** [comment]
Yeah, that's what I have been doing now. I thought it would be a nice feature, but it isn't much of an issue tbh.
