### ISSUE TITLE
Running the project with docker results in npm install error

### ISSUE THREAD

**Issue by DMzda** [odota/core#2431]
Cloning the repo and running `docker compose up` results in the following error:
```
npm ERR! Could not install from "node_modules/steam/steam-resources@github:seishun/node-steam-resources#v1.2.0" as it does not contain a package.json file
```

This can be fixed by deleting `package-lock.json`

**Comment by builder-247** [comment]
I spent some time trying to find a fix for this, updating to a newer node (and npm) version that uses the packageLock 2 format seemed to be the easy fix. @howardchung are there reasons for using node 12 or can we upgrade?

**Comment by howardchung** [comment]
No, we can definitely upgrade
