### ISSUE TITLE
Are there any webhook registration limits for criteria?

### ISSUE THREAD

**Issue by DEV-ONI** [odota/core#2455]
Hi! We're looking to using webhooks for our project.
The webhook registration details registering criteria for subscription, such as `players` and `teams`.

Are there any limits to the amount of criteria you can add to a particular webhook? 
For example, would it be possible to add hundreds OR thousands of `player` ids for a single subscription? 
Or is this something limited to 'Premium Tier' access. 

Thanks so much!

**Comment by howardchung** [comment]
I wouldn't advise using webhooks except for hobby projects. It's no longer well maintained/supported. However, I don't think we have set limits on how many things you can subscribe to.

**Comment by DEV-ONI** [comment]
I see. However the API is still being maintained I presume?
Does odota expose any kind of webhook for parsed matches or is the only other alternative to poll the API through the players endpoint to get their matches?

**Comment by howardchung** [comment]
If you're only looking for parsed matches, there's a "parsedMatches" endpoint that only lists IDs of recently parsed matches. However most of these would not be matches of the players you're interested in.
