### ISSUE TITLE
Invalid Match ID/500 API error on some matches

### ISSUE THREAD

**Issue by howardchung** [odota/core#2468]
Hello,

If you find match IDs that have this error, please post the IDs here. Thanks!

**Comment by TheGAFF** [comment]
There are 100s of matches currently that return 500 errors. Here are a select few:

`6008584967`
`6002264814`
`6000502377`
`5991529462`
`5966597290`

 `https://www.opendota.com/matches/:matchId` 
`https://api.opendota.com/api/matches/:matchId`

I don't know if it is related, but I also get a lot of 429 errors even with an active `api_key` and a 200ms delay between calls.

**Comment by howardchung** [comment]
I've fixed these and set up auto-fixing, let me know if you find more IDs with issues.
