### ISSUE TITLE
429 rate limit with API Key

### ISSUE THREAD

**Issue by TheGAFF** [odota/core#2540]
I'm getting 429 errors pretty consistently despite using an API Key. `X-Rate-Limit-Remaining-Minute` resets to 60. 

Example request:

`/api/matches/{matchId}?api_key={apiKey}`

I can verify that my api call usage increases.  Please advise, thanks!

A few other things:

- Your first 50K using an api key are not free, despite what https://github.com/odota/core/blob/461a5cb51cf3508e04edd6dd0b0498bc776f86b0/config.js#L67 says
- The only thing the api key let's you do is exceed the 50K limit. However, it's a struggle to go over the limit when you can only make 60 requests a minute. Basically, it's very hard to give your money away in it's current state.
- `https://www.opendota.com/api-keys` says 1200 calls per minute, yet the `config.js` file is set to 300 `https://github.com/odota/core/blob/461a5cb51cf3508e04edd6dd0b0498bc776f86b0/config.js#L69`. Still doesn't explain the 60/min I'm receiving.
- This was working fine several years ago. I think a recent change to `web.js` in the last year broke the rate limit functionality.

**Comment by howardchung** [comment]
The 50k limit refers to users not using an API key.

The config.js is a default value overwritten by configuration on the actual servers, so it should still be 1200.

If you email more info to api@opendota.com we can debug your specific case further

**Comment by TheGAFF** [comment]
Thanks for the clarification. Details sent.
