### ISSUE TITLE
Game played yesterday does not show up on profile

### ISSUE THREAD

**Issue by joshuapalicka** [odota/core#2591]
I played a game yesterday - match 6723230180 [Dotabuff link](https://www.dotabuff.com/matches/6723230180) that shows up on Dotabuff, but not in OpenDota & I'm not sure why. Is this a bug? Searching for the match id on OpenDota [Here](https://www.opendota.com/search?q=6723230180) yields no results & it doesn't show up on my [profile](https://www.opendota.com/players/185924306).

**Comment by howardchung** [comment]
You can go to opendota.com/request and request it. Sometimes the Steam API misses a game

**Comment by joshuapalicka** [comment]
Ah interesting. That works, thank you!
