### ISSUE TITLE
OpenDota web failing because gold_t returns null instead of array

### ISSUE THREAD

**Issue by aadittmk** [odota/core#2665]
1. Opening any match on OpenDota Web results in the page stuck in the 'loading' state
2. Debugging console errors point to reading the gold_t[10] value
3. The API response is presently returning null instead of an array

Images attached below are in the order of the statements above

![image](https://github.com/odota/core/assets/35492632/58b8a243-f287-4b08-a8f8-d129b548f2ed)

![image](https://github.com/odota/core/assets/35492632/f0d0adce-fe02-412a-be29-9d0cf71b2605)

![image](https://github.com/odota/core/assets/35492632/8c1631a3-9353-42dc-a343-0295add5999d)

**Comment by howardchung** [comment]
Looks like an issue with the new winner display. I've added a check to ensure gold_t exists.
