### ISSUE TITLE
Can I see a list of {player_id} item ids in /api/players/{player_id}/matches?

### ISSUE THREAD

**Issue by ddgryaz** [odota/core#2689]
Hello! I'm working on a small CLI application to process Dota 2 match statistics. I'm using open-dota-api as one of the data providers.

One of the endpoints I call is `/api/players/{player_id}/matches?significant=0&limit=100`

Please tell me, can I somehow see a list of item ids that were in the player’s inventory ({player_id}) at the end of the match? Perhaps using query param - "project"?

For example, I want to get the id of the items to use them, as used here - https://www.dotabuff.com/players/93106537/matches

Or for me the only way to do this is to call each `/matches/{match_id}` separately - I think this is a bad idea, since the number of calls will be too large.

Thanks for the answer!

**Comment by howardchung** [comment]
Yes, you can project item_0 through item_5

**Comment by ddgryaz** [comment]
> Yes, you can project item_0 through item_5

Thank you for your answer, it actually worked for me, I used a call like this - 
`/api/players/64015685/matches?significant=0&project=item_0&project=item_1&project=item_2&project=item_3&project=item_4&project=item_5&project=hero_id&limit=100`

Can it be shortened somehow?

**Comment by howardchung** [comment]
Unfortunately not. I guess we could add support for comma separated array params. . .
