### ISSUE TITLE
replay link requests

### ISSUE THREAD

**Issue by doctorfrankly** [odota/core#2699]
hey there I hope this is the right place to comment. I was chatting to some friends about getting some data for my research project and they could not help me themselves.. but they suggested i ask here. I need to download a lot of replays to analyze how players move their cameras. I found some games which had the replay links but others did not have a replay link. I was told there was some issue with making lots of "parse requests" for these games because it is wasteful on your side to download and clarity-parse the whole game. Is there a better way to just get the download links for the replays without making a parse request? I need to get about 1k-2k replays a day and will be using clarity myself to get my data out. 
regards

**Comment by howardchung** [comment]
If you just want a list of match IDs that have already been parsed (and so will have the replay link data), use the /parsedMatches endpoint and then request just those IDs. It won't be a random sample, though

**Comment by doctorfrankly** [comment]
thanks for the reply. i already collect match ids i want from another api so i just want to get the replays for those. about 10% of them already have the replay link on the open dota api i just dont want to spam your api to parse the other 90% when i just want the links. if that makes any sense.

**Comment by howardchung** [comment]
If you have a specific set of IDs you want data for then you will need to do a request for the ones that don't already have it available.

1-2k per day sounds pretty reasonable, it's only when it's hundreds of thousands that it starts causing problems.
