### ISSUE TITLE
Method 'GetGameItems' not found in interface 'IEconDOTA2_570'

### ISSUE THREAD

**Issue by OneTrueSum95** [odota/core#2743]
I want to get some items' name and lore in different languages, but the official api is not available, and the OPENDOTA's api is English only.

**Comment by builder-247** [comment]
You can use the new official APIs:

Item List
https://www.dota2.com/datafeed/itemlist?language=English

Item Details (Blink Dagger id: 1)
https://www.dota2.com/datafeed/itemdata?language=english&item_id=1

**Comment by OneTrueSum95** [comment]
> You can use the new official APIs:
> 
> Item List https://www.dota2.com/datafeed/itemlist?language=English
> 
> Item Details (Blink Dagger id: 1) https://www.dota2.com/datafeed/itemdata?language=english&item_id=1

Thanks, that's what I wanted! And are there any more types of APIs?

**Comment by builder-247** [comment]
> Thanks, that's what I wanted! And are there any more types of APIs?

Here is the full list that I know of:

Item List
https://www.dota2.com/datafeed/itemlist?language=English

Item Details (Blink Dagger id: 1)
https://www.dota2.com/datafeed/itemdata?language=english&item_id=1

Hero List
https://www.dota2.com/datafeed/herolist?language=English

Hero Details (Anti-Mage id: 1)
https://www.dota2.com/datafeed/herodata?language=english&hero_id=1

Ability List
https://www.dota2.com/datafeed/abilitylist?language=English

Ability Data
https://www.dota2.com/datafeed/abilitydata?language=English&ability_id=5007

Unique Users
https://www.dota2.com/datafeed/uniqueusers?language=English

Patch Notes List
https://www.dota2.com/datafeed/patchnoteslist?language=English

Patch Notes (7.29d)
https://www.dota2.com/datafeed/patchnotes?language=English&version=7.29d

**Comment by OneTrueSum95** [comment]
Awesome! By the way, are these APIs temporary or long-term? I wouldn't want Valve to suddenly stop using these APIs one day, just like what they did with the old ones on that TF2 page.

**Comment by howardchung** [comment]
It's Valve so you should probably consider all APIs potentially short-term and subject to unannounced change
