### ISSUE TITLE
detailed (aggregated) player timelines

### ISSUE THREAD

**Issue by eblis** [odota/core#392]
This will probably be hard to explain, but here goes:
I think it would be very nice if we had a page that provided all the things a player did during a game, and maybe offer the ability to show up to 2 players so you could comparisons, for example radiant hard carry vs dire hard carry, radiant support vs dire support, etc.

The page would be just a huuuge chart that spans the entire game length from start to finish (X axis) and show XP and Gold graphs for a particular player, (Y axis left is gold for example, Y axis right is XP) ([area chart ?](http://c3js.org/samples/chart_area.html))
Underneath the chart (or as tooltips at various intervals) we can see *interesting* things the player has done at that particular point in time. Items being bought, kills being made, suicides, deaths, aegis pick-ups, etc.
The information is mostly there, but in different pages and needs to be manually compiled, I believe this chart would help with that.

[Example match](http://yasp.co/matches/1427524173):
I select to view the chart for Anti-Mage, I can see that at -1:08 he bought his starting items, then went on farming like crazy, at minute 13 he killed Sniper, at minute 15 he had 78 LH when he bought battle fury, then his last hits went up, his experience starting going up, started doing kills, etc.

This is basically a combination of the timelines page with the graphs page into a single graph, per player.

**Comment by howardc93** [comment]
This seems like it'll require quite a bit of work.  c3 doesnt seem to have much out of the box support for this.  Perhaps we can employ another library. . . will keep this open for now but not on roadmap.

**Comment by howardchung** [comment]
Highcharts appears to have better support for things like this:

http://www.highcharts.com/docs/chart-and-series-types/flag-series

**Comment by howardchung** [comment]
More generally I think the request is simply to provide a tab where we create an aggregated timeline that merges together all of the relevant player data from all the tabs.

**Comment by howardchung** [comment]
This is strictly a UI issue and should be reopened in UI repo if desired.
