### ISSUE TITLE
scrubbable ward timeline

### ISSUE THREAD

**Issue by howardchung** [odota/core#502]
Requested via Reddit, have parser output all wards on map every minute or so and save this data in an array.  Then on match pages allow the user to "scrub" through a timeline to find ward state at X minute.

Challenges:
If using existing heatmaps, how to distinguish between Radiant/Dire wards?
Should probably wait for Source 2 to avoid re-doing work.

TODO
- [ ] figure out how to detect deward
- [ ] figure out the data storage
- [ ] build the UI

**Comment by alexbarrett** [comment]
Would it be possible to store discrete ward events with time data instead of a scrubbable timeline? A structure something like this is what I have in mind:

```javascript
ward_events: [
    {
        team: TEAM_ID,                  // Radiant or Dire
        player: PLAYER_ID,              // ID of the player tha placed the ward
        time: 123456,                   // time the ward was placed
        item: "item_ward_observer",     // observer or sentry
        dewarded: {                     // dewarded not set for wards that last their full duration
            player: PLAYER_ID,          // ID of the player that destroyed the observer
            time: 234567                // time the player dewarded
        }
    }
]
```

This would provide more information with less duplication of data. It would also be possible to build a scrubbable timeline from such a data structure.

**Comment by howardc93** [comment]
We actually already store ward placement data similar to this (with time).  However, I haven't figured out how to detect dewarding, so this data can't be used to generate a scrubbable heatmap (wards would never disappear).

I suppose it would be possible to have the parser emit a "ward disappeared" event when a ward entity that was previously detected is no longer on the map.  However I don't know how to determine the cause (whether it expired or was killed by a player)

**Comment by alexbarrett** [comment]
When a ward is destroyed it shows up in the combat log if that helps. I'm not familiar enough with replay parsing to know exactly how to do it though.

**Comment by howardc93** [comment]
As far as I know the combat log only tells you that a hero killed a ward, but not which ward.

**Comment by alexbarrett** [comment]
Hmm that's a shame. If you know the position of all the wards on the map at a particular time and you know the time a player destroyed a (any) ward is that enough to build the dewarding ward data? The chance of 2 wards being destroyed at the exact same time is extremely small.

**Comment by howardc93** [comment]
We would have to guess the ward the player destroyed based on their spatial locality (which we emit from the parser once a second).

It's prone to errors, though.

**Comment by howardc93** [comment]
With this kind of data we could also compute a "ward-minute" stat which measures the amount of vision each team has.  However, it would not take into account high ground (although maybe we can extract the Z-coordinate from the ward and take that into account), or overlapping wards.

**Comment by howardchung** [comment]
@spheenik implemented OnEntityEntered and OnEntityLeft events, so it's a little easier for us to detect wards being placed and removed.  We could actually build a scrubbable heatmap with that data now, but we still don't have a good way detecting the reason a ward left (expired or killed by unit?)

**Comment by ironapple** [comment]
Could it be possible determine whether the ward expired or was killed by looking at the time which the ward was placed ? If it has left before the expire time then you could assume it was killed by the closest player. Guess the challenges would be to determine which player killed it if multiple player are around or some other unit?

**Comment by howardchung** [comment]
That's still quite a bit of guesswork involved, and is prone to breakage if the ward duration changes.  I'd want something a little more reliable.

**Comment by ironapple** [comment]
I see, you are quite right in it involves alot of guessing. Well I really admire you work on this project, thx for the feedback

**Comment by howardchung** [comment]
I'll investigate further to see what's possible.

Information we want to add on ward entry:
* Position
* Entity handle

Then when we get a onentityleft event (clarity fires these), we can check the entity handle again.  We still don't know why the ward disappeared (without some guesswork), but something's better than nothing.

**Comment by micaelbergeron** [comment]
This is something I would like to work on.

I think using a threshold for a ward lifetime would be a good enough point to rely on. There are already some hard-coded values that changed over the patches (buying items stacks for example) so I don't know how frequent this change would need to be done.

Observer wards now give a 100 gold bounty and 25 experience, could we make use of that to detect who last hit the ward? 

De-warding is a much more important for observers anyway, that is the goal and I think the analysis should be focused toward observers.

Feel free to guide me if you have some ideas.

**Comment by howardchung** [comment]
actually, I added "left" events for wards.

See:
http://api.opendota.com/api/matches/2623329905

Note obs_log and obs_left_log (and corresponding keys for entries).

By matching the ehandle for a ward placed and its corresponding "left" event, we can know exactly when each ward was placed and when it disappeared.

However this doesn't solve the problem of knowing what caused it to leave.  I do not think there is a completely reliable link between these events.  There are entries in the combat log for gold/xp gain, but you would have to rely on temporal locality to link it to a ward left event.

**Comment by howardchung** [comment]
I would also suggest building the UI for this in the new SPA repo rather than this existing one.

**Comment by micaelbergeron** [comment]
Alright here is my approach. I've looked at the obs_left_log from a couple replays and it seems that wards stays for at least their complete duration: I've seen 366 and 367 seconds (is the ward "fade-out" animation timeout adding +6/7 seconds, idk) unless dewarded. 

I'll simply correlate the obs_left_log with the obs_log to find out which ward has been CW. 

I'll then make a table to inspect every ward by itself, so it can be spotted on the ward map.
Here is what I think I'll include in the table:

| Player (icon) | Time | Ward type | Duration | Countered? (by if possible) |

A two-pin slider will enable you to select a slice of the game's timeline, and the table will follow this behavior.

**Comment by howardchung** [comment]
created issue in UI repo
