### ISSUE TITLE
Text summaries of a game

### ISSUE THREAD

**Issue by albertcui** [odota/core#663]
End goal: "Antimage bought a Manta Style [time], Heart [time], and Abyssal Blade [time], farming [# of creeps] in [duration], participating in zero team fights. He then proceeded to announce that 'I've finished farming' and achieved a rampage, taking down two sets of racks [bottom and top]."

**Comment by howardchung** [comment]
Can we just merge the issues :P

**Comment by albertcui** [comment]
Honestly they're not even that similar. One is a summary, one is performance analysis.

**Comment by howardchung** [comment]
My guess is that this is going to be too much work for @albertcui to follow through with, so moving to backlog.

**Comment by howardchung** [comment]
The closest thing to this is probably going to be the "log" feature in the new UI which aggregates several types of log events together (and in the future, allows filtering on them).
