### ISSUE TITLE
Match/player commenting

### ISSUE THREAD

**Issue by howardchung** [odota/core#67]
Add Disqus to match/player pages?

**Comment by albertcui** [comment]
This is actually super easy with disqus.

**Comment by howardc93** [comment]
including the tagging?

**Comment by albertcui** [comment]
Tagging isn't. But I don't know if it's really necessary.

**Comment by howardc93** [comment]
@albertcui do you want to implement disqus for 3.0 or hold off?

**Comment by enche** [comment]
Now that reborn is the norm, you might notice that in game, on a match details/replay page, you can add comments there (as well as like/dislikes as before). Could that be added or is that not an available part of the Valve API?

**Comment by howardchung** [comment]
Any interaction with the client is non-official and not part of the API.  If it's in the client, it's probably possible to interact with it programmatically, but requires reverse-engineering and figuring out how to do it with zero documentation.

**Comment by howardchung** [comment]
@albertcui this might be a fun and pretty easy thing to do, if you want to play with it.

**Comment by howardchung** [comment]
This is likely to cause more negativity than it adds positivity.
