### ISSUE TITLE
Excess decimal digits in magnetize (ES ult)

### ISSUE THREAD

**Issue by Jemsuper** [odota/core#800]
http://imgur.com/yWsKPUT

ES ult costs 100.000000000 mana

**Comment by howardchung** [comment]
Also from http://www.dota2.com/jsfeed/abilitydata.

EIther need to manually patch the "cmb" field, ask Valve to do it, or stop using jsfeed as data source in favor of game file data.

**Comment by howardchung** [comment]
Reopening in dotaconstants since this is an issue with the data source.
