### ISSUE TITLE
incorrect ability images

### ISSUE THREAD

**Issue by eblis** [odota/core#807]
The attributes level up for Invoker doesn't have an icon; example match 2055026043
When Invoker reached level 25 he leveled up his attributes, but there's no icon for that "skill".

Affected:
- [ ] Invoker lvl25 (no ability icon, shows up as ability_id)
- [ ] doom infernal blade http://cdn.dota2.com/apps/dota2/images/abilities/doom_bringer_infernal_blade_md.png
- [ ] riki tricks of the trade
- [ ] faceless void backtrack
- [ ] death prophet witchcraft
- [ ] beastmaster ability 5580 (boar)

**Comment by Derek-Li** [comment]
"invoker_attribute_bonus": {
        "dname": "invoker_attribute_bonus",
        "affects": "ABILITY: <span class=\"attribVal\">Passive<\/span><br \/>",
        "desc": "DOTA_Tooltip_ability_invoker_attribute_bonus_Description",
        "notes": "",
        "dmg": "",
        "attrib": "",
        "cmb": "",
        "lore": "",
        "hurl": "Invoker"
    }

Should be this, I believe

**Comment by eblis** [comment]
Tooltip is missing too, just says "DOTA_Tooltip_ability_invoker_attribute_bonus_Description"

**Comment by Derek-Li** [comment]
https://yasp.co/matches/2055026043
![selection_006](https://cloud.githubusercontent.com/assets/3705478/12100903/f3818be2-b2ff-11e5-9514-d1b61a638c0f.png)

Yeah, I'm actually not too sure how the icon for Invoker's level 25 stat icon should look like, but I'm guessing it'll look like the regular plus icon?

**Comment by eblis** [comment]
Maybe a + icon with multiple + signs in it ? Like 3 + signs stacked one over the other, diagonally ? ⁺+₊

**Comment by Derek-Li** [comment]
On the same topic, Lone Druid's Savage Roar icon does not show up either. 

![selection_007](https://cloud.githubusercontent.com/assets/3705478/12101813/c09f4246-b304-11e5-9558-3154693c3382.png)

**Comment by howardchung** [comment]
The base for data comes from http://www.dota2.com/jsfeed/abilitydata

We would need to manually modify the `desc` field for invoker_attribute_bonus and set the image to the attribute_bonus image.

For savage roar, the tooltip data looks correct, but the image does not appear to be on the Dota 2 servers.  The name is usually something like: http://cdn.dota2.com/apps/dota2/images/abilities/disruptor_static_storm_md.png

However replacing the ability name with lone_druid_savage_roar doesn't work:
http://cdn.dota2.com/apps/dota2/images/abilities/lone_druid_savage_roar_md.png
(404 not found)

**Comment by howardchung** [comment]
It is possible that Valve will end up fixing this themselves at some point, so if it's a major issue we can just not do anything and see if Valve does it for us.

**Comment by eblis** [comment]
I'll log a bug on the dota2 platform.

**Comment by howardchung** [comment]
They should also fix the item ids for the new items.

**Comment by howardchung** [comment]
reopened in UI
