### ISSUE TITLE
Track alchemist aghs

### ISSUE THREAD

**Issue by waitwhereami** [odota/core#815]
Thought it would be a nifty feature to be able to see who received an Aghanim's Scepter from Alchemist. We can currently see how many he purchased over the course of a match, but since they do not show in the inventory of the receivers, it seems to be impossible to determine who got one from the current data.

TODO:
We may want to dump the existing data (we don't do anything with it) and start only tracking modifiers applied to heroes.

Can also create a new field modifier_received.

Candidates:
modifier_item_ward_true_sight (doesn't seem to be present?)
modifier_item_dustofappearance (looks like this is applied to all units in range, not just invis ones.  That limits its usefulness)
modifier_item_ultimate_scepter_consumed (applied when receiving aghs from alchemist?)
modifier_legion_commander_duel_damage_boost (received when winning a duel, seems likely to only be applied once though)
modifier_silencer_int_steal
modifier_pudge_flesh_heap

List:
https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Scripting/Built-In_Modifier_Names

**Comment by howardchung** [comment]
It might be possible to look at modifier_applied to determine who received the buff.

**Comment by howardchung** [comment]
So currently we have modifier_applied for each player, which tracks the modifiers applied by a player and the count of that modifier applied, but not WHO it was applied on.  So to support this we would need to add modifier_received to each player which counts the modifiers received by each player.

**Comment by howardchung** [comment]
I think what we can start with is making a whitelist of modifiers applied we care about, and display that data.  We could report how many times alchemist granted the aghs buff (although not to whom).

Stuff like LC duel might also be able to be counted.

**Comment by howardchung** [comment]
Status: Code in processExpand adds this modifier to the modifiers_applied object.  We'll probably wait until after kube migration, roll out the update to parse nodes, then build the frontend to display it and roll that out.

**Comment by TrentBartlem** [comment]
Latest [patch](http://store.steampowered.com/news/24295/):

>  Post Game screen changes:  
- Added a column for Permanent Buffs. This currently tracks Pudge’s Flesh Heap, Legion Commander’s Duel Damage, Silencer’s Intelligence Stolen, Consumed Moon Shard and Consumed Aghanim’s Scepter.

Hopefully there's API support for that.

**Comment by howardchung** [comment]
I took a quick glance at the GetMatchDetails call and it does not seem to return this data.  Perhaps @Crazy-Duck can comment on progress toward implementing this call in node-dota2.

**Comment by Crazy-Duck** [comment]
@howardchung I've pushed an update of the protobufs to the staging and dev branches. The player info in the match now contains a permanent buffs array, which looks like this:
```
"permanent_buffs" : [{
						"permanent_buff" : 1,
						"stack_count" : 0
					}
				],
```
This is for a match where I consumed a moonshard. So from now on you should be able to retrieve the info from the match details. If I find the time this weekend I'll look into starting on a new major release

**Comment by howardchung** [comment]
Is `permanent_buff` a key to some mapping of IDs to abilities?

**Comment by Crazy-Duck** [comment]
I'm afraid not, you'll either have to play a game with silencer, alch and pudge, eat some moonshards and hand out some aghs or analyze some existing matches to determine the ID's :) 
```
message CMatchPlayerPermanentBuff {
	optional uint32 permanent_buff = 1;
	optional uint32 stack_count = 2;
}
```

**Comment by howardchung** [comment]
Backlogging for now.  If someone wants to do the grunt work of mapping IDs to abilities, we can revisit :)  I assume the mapping must be stored somewhere since the client can display it, but not sure if it's dumped as part of GameTracking.

**Comment by Crazy-Duck** [comment]
Grunt grunt
Moon shard: `{ "permanent_buff" : 1, "stack_count" : 0}`
Alchemist aghs:  `{ permanent_buff: 2, stack_count: 0 }`
Silencer passive: `{ permanent_buff: 3, stack_count: 62 }`
Pudge flesh heap stacks: `{ permanent_buff: 4, stack_count: 11 }`
LC duel damage: `{ permanent_buff: 5, stack_count: 208 }`

Did I miss any?

**Comment by howardchung** [comment]
Thanks!  This should probably go into odota/dotaconstants.

**Comment by howardchung** [comment]
Data should now be collected and stored per player in a permanent_buffs field in the matches endpoint.  Need to build UI for this.

**Comment by howardchung** [comment]
Opening a new issue in UI for display.
