### ISSUE TITLE
Show how long wards are held in inventory prior to being placed

### ISSUE THREAD

**Issue by micphi** [odota/core#844]
This seems like a good thing to track, as one of the bigger issues I've seen with supports in 3k MMR and below is buying wards and just stockpiling them for much longer than necessary. 

Could possibly go between the "Placed" & "Destroyed" columns on the Vision tab?

**Comment by howardchung** [comment]
Interesting.  Might need to dump items held by an entity every second to support this though.

Will keep in backlog.

**Comment by vamo89** [comment]
To get sum or average time held, one could just watch buy and place time

**Comment by howardchung** [comment]
One thing is that watching for use events is no longer completely accurate because uses of the ward dispenser object count too.

**Comment by howardchung** [comment]
I'm going to consider this too specific to be a targeted issue, but am happy to accept a pull request if someone wants to do it.
