### ISSUE TITLE
Winrates in specific scenarios/custom queries

### ISSUE THREAD

**Issue by Jacob29** [odota/core#855]
Would be interesting to see for me personally. Maybe you can do it even more advanced and have it sort via team composition too?

Examples:
Win rates of first Tower / Rosh / Barracks
Win rates with certain drafts (1 carry 1 mid 1/2 supports etc, 5 carries, etc)
Win rates in certain MMR brackets

**Comment by howardchung** [comment]
Could be added.  Might make player pages slower due to having to do more computation per match.

**Comment by Jacob29** [comment]
Perhaps have it as it's own separate page then as opposed to player stats? Where it just shows the total for the entire patch / week / month etc.

**Comment by howardchung** [comment]
Sure, that would probably have less impact on performance.  We could probably just add a script that runs it on the last 100,000 matches every day or something.  Might even been a good beginner project!  If someone wants to write the JS I can show you how to integrate it into our timed jobs system (worker.js)

**Comment by howardchung** [comment]
In practice, this will need to be limited to a recent subset of matches in order to have reasonable response times.

**Comment by howardchung** [comment]
merge with #1264 .

I don't know how many dimensions we will be able to keep track of, but it's all very similar:
* Data stored in postgres, queried with SQL
* Filtering options (MMR, date range)
