### ISSUE TITLE
March data dump

### ISSUE THREAD

**Issue by klop** [odota/core#881]
Is there any way to get a dump of 6.86 matches only? All I could find were the 500k Dec 2015 and 3.5M dumps.
- Large dataset (torrent seeded by @waprin ) and posted to academic torrents
  - Contains every match played to March 2016
  - Skill data for most of the matches after May 2015
- Small dataset (created from large files by @waprin , these are 4GB samples of the large data set files)
  https://storage.googleapis.com/dota-match-dumps/matches_small.csv
  https://storage.googleapis.com/dota-match-dumps/player_matches_small.csv
  https://storage.googleapis.com/dota-match-dumps/match_skill.csv

**Comment by albertcui** [comment]
We'll probably do another dump in March.

**Comment by howardchung** [comment]
Maybe with skill data this time!

**Comment by klop** [comment]
With skill data would be awesome.

**Comment by howardchung** [comment]
do we want to make this a quarterly or semiannual thing?

**Comment by albertcui** [comment]
Pushing back because we're doing import right now.

**Comment by onelivesleft** [comment]
Posting to say this would be good quarterly (unless you get the BigQuery thing updating live).  Will you post a blog post when the next dump happens?

**Comment by howardchung** [comment]
If it were up to me I'd probably do semiannual but if @albertcui wants to do it quarterly I won't say no (he's the one having to export/upload the data anyway).

Regarding future dumps:
I think at some point after we complete the import we will do a massive pg_dump (this would produce a PostgreSQL-specific dump) with every match ever played (~1.2 billion matches, mostly unparsed).  This will also aid us in doing a data migration if we need to move our match data somewhere else (possibly because of Google getting too expensive).  Then we can do periodic "addendum" dumps to keep updated records exported.  It is up to @albertcui if he wants to continue doing the more generic JSON dumps as well.

ETA for import is 10-15 days.

**Comment by onelivesleft** [comment]
That'd be great: I'd love to be able to query a db about matches (like the official api, but not limited to the last x hundred games).  If I have to download a massive file first that's not really a problem.

I take it opening up an api of your own would have too high a bandwidth overhead?

**Comment by howardchung** [comment]
Yeah, APIs are expensive to operate.

**Comment by mikkelam** [comment]
I'm very interested in using the MMR data for machine learning, is this added in this data dump? I suspect one can estimate a players MMR up to a very high accuracy.

**Comment by howardchung** [comment]
@albertcui are you planning to dump player_ratings?  Or perhaps export a "snapshot" of current MMR data?

**Comment by paulodfreitas** [comment]
I think would be nice if dumps are somewhat synchronized with Majors. This way they could be release in "know" intervals and somewhat related with big updates.

**Comment by howardchung** [comment]
import is done.  Been talking with @albertcui about doing a full dump this time (with every match ever played).

We'd dump matches, player_matches, and player_skill as CSV.

**Comment by onelivesleft** [comment]
Sounds good

**Comment by howardchung** [comment]
@albertcui I put sample queries in the OP.  You may want to try them locally on your devbox first to make sure they work properly.

**Comment by albertcui** [comment]
```
yasp=# COPY matches TO PROGRAM 'gzip > /var/lib/postgresql/data/pgdata/matches.gz' CSV HEADER;
ls
COPY 1191768403
yasp=# COPY match_skill to PROGRAM 'gzip > /var/lib/postgresql/data/pgdata/match_sill.gz' CSV HEADER;
COPY 132447335
```

`matches.gz` is 146 GB. Currently exporting player_matches.

**Comment by howardchung** [comment]
Update:
So we encountered some kind of exception while trying to dump player_matches.

Apparently a fix is to perform a vacuum on the table, so @albertcui did this.  It's been running for weeks :(

**Comment by albertcui** [comment]
Started player_matches export again.

**Comment by albertcui** [comment]
`COPY 11720437356`

**Comment by howardchung** [comment]
From @albertcui :

if someone has the hard drive space, ~1TB, if you could help download our data dump and test it, that would be great. https://www.amazon.com/clouddrive/share/2tSLvE98SNMmuv6wwUaPjYLaYA4Rw16ISzW38yAu8yU?ref_=cd_ph_share_link_copy

the large files are split up into 10 GB pieces because of an amazon limitation. You can cat them back together: 

http://askubuntu.com/questions/54579/how-to-split-larger-files-into-smaller-parts

@fhoffa , perhaps you could help us do this (since you'll probably want the data to upload to BigQuery?)

**Comment by rossengeorgiev** [comment]
If I may make a suggestion for future dumps. Consider doing them incrementally, and ideally split by date. That would make the data much more accessible while also minimizing costs for generation, storage and distribution.

**Comment by howardchung** [comment]
Moving to August, since that's likely when we'll be able to distribute the files (unless someone wants to create a torrent now)

**Comment by xgfs** [comment]
I am slowly but surely downloading the files from the Amazon cloud. I finished matches_split, and am currently downloading player_matches_split. When I finish and verify the files (btw, md5 would help), I will put up a torrent. It moves rather slowly as Amazon closes the session (and the link) after some time, so I have to use a download manager.

**Comment by dracovich** [comment]
I don't know if it's practical or just creates more problems, but i figured i'd throw this out there:

Would it be more practical to do smaller dumps of data but do it regularly? Personally i can't even download such large files, let alone do much meaningful work with it, i'm usually working with between 25-100k matches i've streamed from the JSON, and find that's usually enough for meaningful data.

If that is more practical, i think it could add a lot of value to have these smaller dumps, but regularly, so there's up-to-date data to work with.

**Comment by howardchung** [comment]
Yeah, I think any future dumps will be "incremental" dumps on top of this one.  We don't want to do another one of these full dumps (all together, it ended up costing nearly $800)

**Comment by dracovich** [comment]
Sounds great! Is the plan to do a "500.000 most recent games" dump alongside the full dump, like you did in December? Or will it only be the 1TB file?

**Comment by howardchung** [comment]
Only the big one.  We may just delete the older ones to prevent confusion.

**Comment by paulodfreitas** [comment]
As the 1TB file huge. I think would be nice to keep smaller samples of the database, at least the december 500k matches. It's easier to start to work with the matches.

**Comment by xgfs** [comment]
Started creating .torent file. 508GB gzipped files total.

**Comment by howardchung** [comment]
@nicholashh , can you download and verify the torrent?

**Comment by waprin** [comment]
@howardchung I am interested in getting the latest data into BigQuery (I work with Felipe, he will help me with BigQuery but he doesn't play dota so more interesting to me). Here are my questinos:

1. High level summary of the 3 tables and their relationship to what Felipe put in BigQuery last time - https://bigquery.cloud.google.com/table/fh-bigquery:public_dump.dota2_yasp_v1?pli=1

2. If I want to peek at some rows, is it impossible without downloading the whole thing? Seems like it is because it's gzipped then split up and I think that means you need to cat the whole thing before unzipping but correct me if I'm wrong

3. Do you still need help hosting or seeding the torrent? Current link looks broken. I will look into my options for doing so.

Thanks, awesome project, hoping to dive into it!

**Comment by howardchung** [comment]
1.  You might want to look at the schema to see what the tables contain (`sql/create_tables.sql`).  This dump contains a superset of the data in the previous dump.  Last time, we combined the data from multiple tables into JSON match objects.  This time, we opted to dump CSV since it's more flexible.

2.  You could potentially download the first few, streaming unzip it, and process the data you can unzip before it fails.

3.  Albert will be back in about a month.  The data is still hosted in Amazon cloud drive.  We need a torrent made, verified, and seeded.

**Comment by benlee** [comment]
This is a wonderful set of data, I've got it downloaded and have been poking at it -- in the first segment it seems like a large amount of matches do not have skill levels when I do the join, is this expected?

**Comment by howardchung** [comment]
Yes, we only started collecting skill data in May 2015 and this data contains every match (starting in 2011).  Dotabuff/Dotamax likely have more skill data since they have been running longer but I am not sure if they will do data dumps.

**Comment by howardchung** [comment]
Re: smaller dump, perhaps someone who downloads the full data set can grab the tail end of each of the 3 files and make a "mini" data set.

**Comment by albertcui** [comment]
@xgfs Could you rehost the torrent file? I can put it on academic torrents then we can actually promote the data dump.

Sorry for the delay; I just recently got home and to a stable internet conneciton.

@waprin We'd really appreciate it if you could possibly host/seed the torrent. I probably can't do it until I get my housing situation sorted out in the next few weeks. On a side note, I'm going to be starting at Google on the 8th, so see you soon!

**Comment by xgfs** [comment]
There were some server issues, they are resolved. The link is up again:
http://xgfs.ru/yasp_06_2016.torrent

**Comment by albertcui** [comment]
Thanks, can you set the announce URL to http://academictorrents.com/announce.php ?

**Comment by albertcui** [comment]
Sorry, nevermind I've done it! Thanks a lot!

**Comment by albertcui** [comment]
I've uploaded the torrent to [Academic Torrents](http://academictorrents.com/details/16e0a94411661da6dc57eef22e4681f61c933c4c). Unfortunately, I  won't have a computer with enough disk space to seed for another week :(

**Comment by howardchung** [comment]
File sizes seem too small (player_matches). Can we wc it and confirm the count?

Also it should be March not June. I believe that is the end of the data.

**Comment by xgfs** [comment]
Correct: for some reason ln created a weird half-sized symbolic link (I use the data from the other disk). I will re-create the torrent now. Sorry for the inconvenience. I'll edit the wc to this post as it is ready.

**Comment by chudooder** [comment]
Any chance for that smaller dataset containing recent matches? I don't think I can store the whole 1TB file on my computer and I'd like to be able to work with a more recent dataset than the December one.

**Comment by waprin** [comment]
Have most of the data downloaded, uploaded it to bucket, still need to import it to BigQuery, will looking into seeding torrent and making smaller dataset. 

@albertcui what location are you starting at?

**Comment by albertcui** [comment]
@waprin I'm going to be in MTV.

**Comment by benlee** [comment]
@albertcui im in MTV, we should get lunch after you're settled

**Comment by xgfs** [comment]
Torrent and lengths updated.

**Comment by howardchung** [comment]
Could we get the line counts of the decompressed data?  They should match the COPY output from above.

Also, could you remove _split from the file names?

something like `cat match_skill.gz | gunzip | wc -l`

**Comment by SomeSnm** [comment]
@waprin Hi! Any updates on the torrent?

**Comment by waprin** [comment]
Sorry for big delay, sidetracked by other things.

Byte count on the gzip is the same for matches.gz but not for player_matches.gz. ALso included decompressed sizes:

```
waprin@unix-instance2:~$ wc -c matches.gz
155941971528 matches.gz

waprin@unix-instance2:/mnt/disks/extra-disk/Downloads$ wc -c player_matches.gz 
542664372161 player_matches.gz

waprin@unix-instance2:/mnt/disks/extra-disk/Downloads$ wc -c player_matches.csv 
2200436749690 player_matches.csv

waprin@unix-instance2:/mnt/disks/extra-disk/Downloads$ wc -c ~/matches.csv 
1253950283105 /home/waprin/matches.csv
```

I have 4GB truncated files for matches and player_matches as GCS buckets if that helps. Currently putting both small and full dumps into bigquery.

https://storage.googleapis.com/dota-match-dumps/matches_small.csv
https://storage.googleapis.com/dota-match-dumps/player_matches_small.csv
https://storage.googleapis.com/dota-match-dumps/match_skill.csv

Will try to get line count next as well.

I am also now trying to seed the torrent using transmission, not sure if I'm using transmission wrong or nobody else is seeding currently.

**Comment by howardchung** [comment]
If it's being seeded, can we put it on academic torrents and write a release blog post?  @albertcui ?

**Comment by howardchung** [comment]
Moving to September

**Comment by SomeSnm** [comment]
If it's been seeded can I already download it or its not fully ready yet?

**Comment by howardchung** [comment]
I believe @waprin has the only copy right now.

**Comment by SomeSnm** [comment]
So all I need is for him to start seeding?

**Comment by howardchung** [comment]
Yes, and I think we need to put it on a tracker (academictorrents)

**Comment by howardchung** [comment]
bumping--any update?  @waprin are you still seeding?  @albertcui can we get it on academictorrents?

**Comment by nicholashh** [comment]
(i can also seed it if i have it or if it goes on academictorrents)

**Comment by howardchung** [comment]
Bump again for visibility :)

Moving to October

**Comment by waprin** [comment]
I was never seeding the torrent because I never had the file downloaded. I could seed the files I downloaded which seems slightly different (byte size) which I got from the Amazon Drive.

**Comment by howardchung** [comment]
Could you check line counts?  If they match the values from the original export I think we can be reasonably sure you have an accurate copy of the data.

Torrents cannot be updated after creation.  You'll have to create a new one.

**Comment by waprin** [comment]
wc -l is taking forever, not sure if there is a way to parallelize it (it's already decompressed). Either way the matches.gz byte count matches but the player_matches.gz doesn't (542664372161 vs 542664373941 xgfs reported).

**Comment by howardchung** [comment]
A difference of 1800 bytes seems pretty small.  I imagine it can't be due to incorrectly assembled files since the decompression would have failed otherwise.  It's probably something at the tail end of the file?

**Comment by waprin** [comment]
I don't know any way to be sure. Are you suggesting I just create a new torrent with the files I have?

**Comment by howardchung** [comment]
Yeah, if you were able to upload them to bigquery etc I think we can be reasonably sure you have valid data.  It would be nice to have the line counts to check, though.

**Comment by waprin** [comment]
Will try to see if I can figure it out later this week.

**Comment by rossengeorgiev** [comment]
@waprin you could use the [torrent from academictorrents](http://academictorrents.com/details/16e0a94411661da6dc57eef22e4681f61c933c4c) to verify the file integrity. Just setup the file structure exactly the same, add the torrent pointing to that location and run verify local data/force recheck depending on your bt client.

**Comment by howardchung** [comment]
That file is incorrect and should not have been posted.  @albertcui needs to delete it so we stop confusing people :)

**Comment by albertcui** [comment]
I've deleted the torrent.

**Comment by albertcui** [comment]
@waprin if you can create a new torrent I can upload it to academictorrents. It needs the the announce URL set to http://academictorrents.com/announce.php

**Comment by albertcui** [comment]
And unfortunately I still don't have a computer that I can seed from. My desktop got messed up during the move :(

**Comment by howardchung** [comment]
Updated the OP with the files we are planning to release (large and small datasets)

**Comment by ChristianSimon** [comment]
Fetched the dump from the amazon drive (https://www.amazon.com/clouddrive/share/2tSLvE98SNMmuv6wwUaPjYLaYA4Rw16ISzW38yAu8yU?ref_=cd_ph_share_link_copy) and got these line counts:

```bash
==> matches_split.gz.wc <==
1191768404

==> match_skill.gz.wc <==
132447336

==> player_matches_split.gz.wc <==
11720437357(edited)
```
Waiting for the bit counts. Will post here then they finish. Let me know if you had the same numbers in order to verity the download.

**Comment by howardchung** [comment]
Line counts from postgres (copied from earlier posts):

```
yasp=# COPY matches TO PROGRAM 'gzip > /var/lib/postgresql/data/pgdata/matches.gz' CSV HEADER;
COPY 1191768403
yasp=# COPY match_skill to PROGRAM 'gzip > /var/lib/postgresql/data/pgdata/match_sill.gz' CSV HEADER;
COPY 132447335
player_matches
COPY 11720437356
```

It looks like you have one additional line on each one, which is probably just an added newline at the end.  I think you have a valid copy of the data.  If you're able to get a torrent up before @waprin is, we could get it distributed earlier.

**Comment by waprin** [comment]
@howardchung apparently academic torrents requires an edu address? Any alternatives you can suggest?

**Comment by howardchung** [comment]
You'll have to ask @albertcui , he set up the torrents.  However I don't think you need to create an account, you just need to set the announce URL on your torrent.  I could be wrong though

**Comment by waprin** [comment]
Yeah I see now he said I just need to set the announce URL when creating the torrent and then he'll upload it. Creating it now and I guess when he comes back we can sort out the details. I am a bit confused what the difference between the announce URL and uploading is. Anyway seems it will take a while to create the torrent anyway so I'll check back in when it's done.

**Comment by albertcui** [comment]
The announce URL I believe sets academic torrents as a tracker. Uploading it to academic torrents is just so that they host the torrent for us. (And I'm not sure if you can use them as a tracker if you don't upload to them? Not super clear on bittorrent technology). Thanks!

**Comment by rossengeorgiev** [comment]
@albertcui Fairly certain you have to upload the torrent to academictorrents to use them as a tracker

**Comment by klop** [comment]
Perhaps the dataset can be divided into multiple torrents by date?

**Comment by rossengeorgiev** [comment]
@klop probably won't happen since someone will need to sort of rows first :frowning_face:

**Comment by klop** [comment]
@rossengeorgiev what about by map version?

**Comment by howardchung** [comment]
Any updates here?

**Comment by waprin** [comment]
It was never clear to me how to upload the torrent. I can set the announce URL but then not sure what to do with it. If someone gives me instructions on how to get it onto a tracker I will do that.

**Comment by howardchung** [comment]
@albertcui can correct me, but you should be able to share the torrent file here like @xgfs did previously, then Albert can put it on academic torrents.  Then you just need to seed it.

**Comment by rossengeorgiev** [comment]
@waprin would it be possible to split the various files into smaller pieces? Possibly by line, although that would only be useful for seeding part of the torrent as the lines are not ordered. Either way, having smaller pieces means people can help seed parts without having to download the whole thing. Should make for a healthier torrent.

**Comment by howardchung** [comment]
Perhaps the lines could be sorted by match ID or start_time?  Does BigQuery support exporting data in sorted order?

**Comment by waprin** [comment]
I don't think Bigquery can do it but I could look into writing a map reduce job to do it or something. I am still just most confused by the actual process of creating the torrent and seeding it, but I'll try to figure it out. 

Basic gameplan is to use the top answer here:
http://askubuntu.com/questions/32024/how-to-create-a-torrent-using-the-command-line

Set the announce URL to http://academictorrents.com/announce.php, then upload the torrent file I create here. Let me know if that makes sense.

**Comment by howardchung** [comment]
That sounds correct.  Any update?

**Comment by howardchung** [comment]
Moving to November.

**Comment by ZKingUK** [comment]
Joined the discord channel and have begun asking questions regarding the best way to get some of the data (All TI6 matches) out of the API into tabular format (currently throwing around the idea of using Postgres to replicate the database and pull it in) . If anyone has a solution to share I would greatly appreciate it.

If this is the wrong place to ask this I apologize. Just trying to get started on a project and OpenDota seems like my best chance at getting it up and running. I would love to begin contributing if there are things that need to be done. Thanks

**Comment by howardchung** [comment]
@waprin any update on seeding?

**Comment by waprin** [comment]
I have been swamped by work/life but with the holidays coming up I should have some more free time to loop back on this.

**Comment by howardchung** [comment]
Moving to December.  I believe @waprin is sorting the data now so it can be chunked (batches of 100 million match_ids?)

**Comment by howardchung** [comment]
@waprin any update?

**Comment by howardchung** [comment]
@waprin did the match split  complete successfully?

(As an update the player_matches data was split into chunks of 10,000,000 player_matches, resulting in ~119 files).  The plan is to put all the chunks in the same torrent.  Users who don't want the full data set can selectively download certain chunks.

**Comment by waprin** [comment]
I am still really banging my head against these torrent clients. I am sure I am close to having something working. But I figure the obvious test is to seed a a file from one instance and download in another. I am testing with a small text file and the clients seem to see the files they need to download, but not actually start downloading them.

If anyone has crystal clear permissions on how to seed a file and download it from another using the CLI on Debian/Ubuntu instances using an open tracker, it will simplify things greatly. Otherwise I will figure it out eventually, but that's currently the holdup.

**Comment by waprin** [comment]
And yeah I split the files successfully and created a torrent, just not very confident others will actually be able to download until I figure out the correct ctorrent or transmission settings.

**Comment by howardchung** [comment]
Maybe you can post the torrent file/magnet link and we can see if we can download successfully?

**Comment by waprin** [comment]
The torrent itself is 256 MB which seems really big, even given the size of the data. Here is link:

https://storage.googleapis.com/dota-dumps/dota.torrent

I created it by doing

`ctorrent -t -u " http://academictorrents.com/announce.php" -s dota.torrent dota_dump`

Now, when I do 

```
ctorrent -x dota.torrent 
error, "dota.torrent" is really a metainfo file???
error, initial meta info failed.
```

which is weird, because it can't even read the metadata.

I can also try again by compressing first, but if I compress, then people can't cherry-pick the files as requested (I think).

I tried similarly with `transmission-create` but have run into different sort of problems.

These are all from GCE instances, I am realizing it's way, way more expensive than just buying a cheap external hard drive, I am traveling for the holidays but I think once I get back I will rebuild a desktop and then maybe be able to seed from there using GUI tools. Until then, I don't mind swinging the cost of seeding from an instance, I just need to figure out how to actually do it.

**Comment by waprin** [comment]
Also, while we'll eventually get this seeded as a torrent, in the meantime, if a few people are dying for the entire dataset, I can send private links to the GCS buckets with the whole thing to help split the cost between that and the Amazon links. It does seem like the majority of people only want recent or high tier matches anyway. 

Speaking of which, are you going to create a dump with recent matches any times?

**Comment by howardchung** [comment]
@albertcui can you help?  256MB seems way too big.  Can you paste your transmission-create command?

No plans to create a new dump at this time.  The API is available for users who need recent data, and based on this effort it takes a lot of time and cost to get a dump out.

**Comment by waprin** [comment]
Here was my transmission command

`transmission-create -o dota-dump.torrent -t " http://academictorrents.com/announce.php" dota_dump/` 

that creates a 32MB torrent file instead. 

https://storage.googleapis.com/dota-dumps/dota_dump.torrent

No idea why there is such a difference in size between ctorrent and transmission. 

It also has the same problem where ctorrent fails to read the metainfo. 

Understand this is a painful process. Maybe I can run the project myself and start trying to put together dumps, eventually I will understand it and torrents better and the initial pain will be lower. Ideally I'd like to stream new data to the bigquery tables. 

Like I said, I'm traveling for the holidays and back early January, then I want to build a new desktop with a big external hard drive. So I'll take another shot at it on that with some GUI tools. So ETA on that would probably be another month.

In the meantime, if Albert or anyone else can offer any insight into what I might be doing wrong trying to create/seed the torrent, I'm happy to try. Like I said, I think just instructions on how to create/seed a tiny file purely from the CLI with a public tracker would be a helpful starting point. I've tried a bunch of tutorials and seem to be getting close, but haven't gotten things quite working.

**Comment by howardchung** [comment]
So doing some quick searching on the subject it looks like the torrent size is based on the number of pieces the data is split into.  If we want a smaller torrent, we probably need to pass an option specifying the number of pieces.  The two commands probably have different defaults.

I assume you have the seeding working as described here? https://lists.freebsd.org/pipermail/freebsd-questions/2009-June/201753.html

Perhaps try another tracker--wasnt there a public one that you were going to try?

**Comment by waprin** [comment]
Just got too frustrated and wanted to take a break from this, especially since I was traveling. Getting back home tomorrow, going to build a new PC with a bigger disk, will loop back around on this and learn more about torrents sometime this month. I might even try to host my own torrent tracker, might be a good learning experience.

**Comment by howardchung** [comment]
If you just put the blobs on Google Cloud Storage and shared the download links, would you be able to pay for the download bandwidth/storage on your personal account?  Or should we wait until we get a torrent working before making a blog post/public announcement?

**Comment by rossengeorgiev** [comment]
I know you guys haven't finish dealing with the original dump, but any chance for a fresh one? Like the last month or something. It would be really useful given the dramatic changes of 700.

**Comment by howardchung** [comment]
unfortunately the old code we used for dumps doesn't work anymore since the move to Cassandra.  No telling when we'll be able to get a new migration script working.

I think @waprin wants to eventually get something set up where match data is directly streamed to BigQuery.  If we get that working then it would probably be the best place to obtain fresh data dumps.

**Comment by rossengeorgiev** [comment]
I'm unfamiliar with Cassandra, but there seems to be CAPTURE command that would export the result of queries. Couldn't find any details about performance. Maybe that could do it?

I really like the idea of streaming data to BigQuery, but does seem to be happening any time soon. The original issues was about just a slice of data. I'm looking for the same thing a year later and it seems to be even further from happening.

**Comment by howardchung** [comment]
Depending on how many matches you need, you can use the API to fetch the
match data for randomly selected matches in the time window you want.

**Comment by waprin** [comment]
I just ordered a new HDD so I can just seed from home as soon as it arrives. Torrent does seem like the best option.

Would like to stream matches directly from API into Bigquery so will look into that.

**Comment by rossengeorgiev** [comment]
I've recently scrapped all dota matches for January and I'm making it available as a torrent. It's 33mil matches without the dark moon ones.

http://static.rgp.io/dota2_matches_jan2017.torrent

**Comment by bippum** [comment]
Downloaded and created torrent files for player_matches and match_skill from https://github.com/odota/core/issues/881#issuecomment-226920743. 

Files:
 - [x] [match_skill.gz](https://cdn.discordapp.com/attachments/144629812982448128/286601256070545418/match_skill.gz.torrent) 1.60 GB (1643 pieces at 1 MB/piece)
- [x] [player_matches.gz](https://cdn.discordapp.com/attachments/144629812982448128/286601349737742336/player_matches.gz.torrent) 505.4 GB (258,763 pieces at 2 MB/piece)
- [ ] matches.gz (not uploaded yet)

**Comment by bippum** [comment]
Downloaded and created torrent files from https://github.com/odota/core/issues/881#issuecomment-226920743. I'll have player_matches up by tomorrow and matches up by as soon as it finishes downloading from Amazon. 

Files:
 - [x] [match_skill.gz](https://cdn.discordapp.com/attachments/255083632149004301/286611162768998401/match_skill.gz.torrent) 1.60 GB (1,643 pieces at 1 MB/piece)
- [ ] player_matches.gz (not uploaded yet
- [ ] matches.gz (not uploaded yet)

Thanks Discord Nitro.

**Comment by bippum** [comment]
@albertcui, I believe my links should be good to go as long as you upload the files to academictorrents. It should resolve this error in my client: 
![image](http://puu.sh/uykf2/a9a8bb8350.png)

**Comment by jvanhees** [comment]
Is there anyone seeding the files from @bippum , and is there some sample data available? I've got plenty of space and a home server that can seed 24/7 at 200mbit/s, but I first need to download the data :) . I will leave the torrents provided above running for now, hoping that someone can share them. If there are other torrents available, please let me know.

**Comment by howardchung** [comment]
The OP has small sample datasets.

@albertcui can you please upload the torrents to academic torrents?

**Comment by albertcui** [comment]
I've uploaded matches + match_skill. It won't let me update player_matches:

"Sorry, the piece length is too small. The torrent file must be less than 2MB. Increase your piece length to lower the file size"

**Comment by bippum** [comment]
I'll attempt to create the torrent again within the day.

**Comment by albertcui** [comment]
Thanks, sorry for the delay. Did uploading the other ones fix the error?

**Comment by bippum** [comment]
Yes it did.

**Comment by jvanhees** [comment]
Great, thanks guys, I'm currently downloading the files and will continue to seed them :). Good work!

**Comment by bippum** [comment]
Glad to hear you are able to download them OK. I switched torrent clients (from Transmission to Deluge) after having difficulty getting Transmission to do anything, let alone upload. Now I wake up to see that match_skill and matches are seeding! I updated the player_matches link with a 4 MiB piece torrent, @albertcui if you could upload that one to academictorrents? Thanks.

**Comment by howardchung** [comment]
Awesome, once they're all up we can write a release blog post and then we can finally close this! :)

**Comment by albertcui** [comment]
I've uploaded it here: http://academictorrents.com/details/1a0c5736bb54610ad00a45306df2b33628301409

**Comment by howardchung** [comment]
Blog post published:
http://blog.opendota.com/2017/03/24/datadump2/

**Comment by viniciusmr** [comment]
Hi there guys!
Isn't there anywhere else where the files are available?

I'm currently downloading the "OpenDota - All Matches from March 2016 - Matches"
(matches.gz , 155.94GB)
However the torrent availability is less than 1 (0.781) which means even if I leave this downloading forever, I won't be able to finish the download, cause there are missing pieces in the stream.
(and actually there is only **one seeder** =/ )

**Comment by bippum** [comment]
Hi, I'm currently seeding all 3 files with 100% completion, so it should complete eventually.

![seeding](https://o.lol-sa.me/091121.png)

**Comment by pranavchintala** [comment]
Hello, would anyone be willing to seed player_matches.gz? Haven't been able to find a seeder for a week now and could really use this data for a project! Thanks in advance!

**Comment by bippum** [comment]
The copy I had got corrupted during a transfer between hard drives. I no longer have the original files from the amazon cloud drive location, and they aren't obtainable either. Sorry for the inconvenience.

**Comment by pranavchintala** [comment]
Alright no problem, thanks for the response!
Would anybody else have even a subset of this data available? Perhaps something larger than the 4GB samples above would do the trick.

**Comment by hanisaf** [comment]
I wonder if anyone can still seed matches.gz and player_matches.gz? I'm interested in the data for a research project. Thanks.

**Comment by zubinmehta** [comment]
I am willing to seed it if I can get a copy of it
