### ISSUE TITLE
Image batching

### ISSUE THREAD

**Issue by albertcui** [odota/core#952]
Improve site speed by batching images into spritesheets, reducing HTTP connections.

https://github.com/selaux/node-sprite-generator

**Comment by aeosynth** [comment]
http2 prefers smaller files over bundles. https://blog.cloudflare.com/http-2-for-web-developers/#stopconcatenatingfiles:

> In HTTP/1.1, web developers often combined all of the CSS for their entire website into a single file. Similarly, JavaScript was also condensed into a single file, and images were combined into a spritesheet. ...

> However, concatenating files is no longer a best practice in HTTP/2. While concatenation can still improve compression ratios, it forces expensive cache invalidations. ...

> In addition, not every page in your website uses all of the declarations or functions in your concatenated CSS or JavaScript files. After it’s been cached, this isn’t a big deal, but it means that unnecessary bytes are being transferred, processed, and executed in order to render the first page a user visits. While the overhead of a request in HTTP/1.1 made this a worthwhile tradeoff, it can actually slow down time-to-first-paint in HTTP/2.

improve site speed by enabling http2

**Comment by howardchung** [comment]
so we actually shouldn't do this and keep what we are doing now (individual http requests for images?)

**Comment by aeosynth** [comment]
this should be benchmarked, but yes, making a request per image is fine; http2 combines multiple requests (http pipelining). i'm not sure about the details because i haven't actually used it myself; the server might need some configuration.

**Comment by howardchung** [comment]
For optimal SPA performance, I think we'd want to load a copy of the images into the SPA repo, and let github's CDNs take care of optimizing image loads.  The disadvantage is that this means another step to do when a new hero is added.

**Comment by howardchung** [comment]
I don't think we will be doing this.  Either we'll load the images into the SPA, or just let cloudflare handle caching.
