### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by albertcui** [odota/core#953]
This is what you get when you search YASP on Google. This should be better.
![ss 2016-04-02 at 07 51 47](https://cloud.githubusercontent.com/assets/3838552/14229808/61b99814-f90c-11e5-9a51-afbd44067f34.png)

**Comment by leovarmak** [comment]
@albertcui you mean meta desc ?

**Comment by howardchung** [comment]
This code will only provide data to consumers and will not be directly linked to.  Reopen in UI if we decide we need this.
