### ISSUE TITLE
r/dota2 bot

### ISSUE THREAD

**Issue by howardchung** [odota/core#956]
@albertcui forked this, we can investigate allowing it to request/return parse data.

https://github.com/yasp-dota/dotamatch

**Comment by NNTin** [comment]
https://github.com/NNTin/Reply-Dota-2-Reddit

I would also love to display some Yasp data. [/u/AnalyzeLast100Games](https://www.reddit.com/r/dota2/user/analyzeLast100games). (Current botname but I plan on changing it soon since it can now analyze more than 100 games. Also am planning to add other functionalities to it.)

**Comment by albertcui** [comment]
Awesome! We've love it! We have an api (work in progress) here: https://yasp.co/api/matches/2249420676

How can we help?

**Comment by NNTin** [comment]
Ah that's awesome. I didn't know Yasp already provided an API. :)
I will look into it and see what I can display on Reddit. If I need something I will message you guys! I can try and display their MMR if it is available on Yasp and if they are registered on Yasp. 
Match's chat and player's word cloud is also interesting. I can put it in a Reddit post and make it hover to view.

**Comment by howardchung** [comment]
The tricky bit is having to support requests.  We'll need to issue a key to allow the bot to submit parse requests since we may not have parsed data yet.

**Comment by dotamatch** [comment]
If y'all want to fork this and add the functionality, go ahead, but I have a feeling there are a number of additional improvements that would need to be made. The code is very messy and personally refactoring it is a bit of a burden for me at this point.

In general I'm not really maintaining the bot anymore for drastic changes, so if YASP wants to host it, let me know (it's barely resource heavy).

**Comment by howardchung** [comment]
It'll probably come down to @albertcui then.  I can provide the API but can't commit to maintaining any external code

**Comment by albertcui** [comment]
We can host in in the future after we make the changes :) Thanks!

**Comment by howardchung** [comment]
@NNTin if you want us to expose a parse request endpoint:

We can probably give you a key that will bypass the captcha check (with some kind of rate limit).  The request endpoint returns a job, which you have to poll for status.  On complete, you can then pull the match data from the regular matches endpoint.

The end user on Reddit presumably would use some flag like "--yasp-parse" or something to tell the bot to request a parse.

**Comment by NNTin** [comment]
Thanks. My semester is starting on Monday and I just moved to a new city. I don't think I need a parse key for now.

I will do this: https://github.com/NNTin/Reply-Dota-2-Reddit/issues/11 when I have time. For now I don't need the in depth replay analysis.  
Currently I'm working on this: 
https://github.com/NNTin/Reply-Dota-2-Reddit/issues/13

Dotabuff has this: https://i.imgur.com/88WbdQr.png which I think is very neat. If possible I also would like to provide links to the pro player's twitter, twitch, youtube etc. I don't have a database that contain those information and I also don't know how to make one. Maybe you add it in the future and I can extract those information from your site.

**Comment by howardchung** [comment]
I believe it has to be user supplied (user has to link their social media profile to their steam ID).  You can try scraping it from Dotabuff profiles (probably best to ask permission before doing it at scale though)

**Comment by dotamatch** [comment]
Keep in mind the information density at hand here

**Comment by howardchung** [comment]
@albertcui is unlikely to take this on as he prefers to do PM work instead of SDE.  Will leave open in case a community developer wants to maintain a r/dota2 bot.

**Comment by howardchung** [comment]
Continue this issue in the fork:
https://github.com/odota/dotamatch

**Comment by dotamatch** [comment]
Ping me when you need me to do something.

On Oct 6, 2016 8:28 AM, "Howard Chung" <notifications@github.com> wrote:

Continue this issue in the fork:
https://github.com/odota/dotamatch

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/odota/core/issues/956#issuecomment-251946945>, or mute
the thread
